### PR TITLE
Introduce a base lexer for PHP per target runtime

### PR DESCRIPTION
**Pull request by thierrymarianne**
Addresses https://github.com/antlr/grammars-v4/issues/1482

### CODE REVIEW

**Comment by KvanTTT** [comment]
Also, you can add a line with your name and email to the copyright notice.

**Comment by teverett** [comment]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ php ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /home/travis/build/antlr/grammars-v4/php/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/antlr/grammars-v4/php/target/generated-sources/antlr4/PhpLexer.java:[299,52] ';' expected
[ERROR] /home/travis/build/antlr/grammars-v4/php/target/generated-sources/antlr4/PhpLexer.java:[313,48] ';' expected

**Comment by thierrymarianne** [comment]
While working on the CSharp base lexer, I've encountered the issue mentioned in https://github.com/antlr/antlr4/issues/2289, the solution provided at https://github.com/antlr/antlr4/issues/2289#issuecomment-389323572 also worked like a charm so I've added a comment about the need to import the static variables from the fully qualified of the PhpLexer class carrying the static variables declarations.

**Comment by KvanTTT** [comment]
Ok, so I guess we are ready to merge this PR?

**Comment by thierrymarianne** [comment]
I think so, yes.

**Comment by thierrymarianne** [comment]
Thank you!

**Pull request merged**
