### PR TITLE
[MySQL] Support CAST AS DEC

### PR DESCRIPTION
**Pull request by vjuranek**
CLI example:

    > SELECT CAST('1' AS DEC);
    +------------------+
    | CAST('1' AS DEC) |
    +------------------+
    |                1 |
    +------------------+

### CODE REVIEW

**Comment by vjuranek** [comment]
Add also support for `CAST (UN)SIGNED INT`

**Comment by kaby76** [comment]
Tests timed out, more than 300s. We need to split up the tests for the Go target for this grammar.

**Comment by kaby76** [comment]
```
fullColumnName
    : uid (dottedId dottedId? )?
    | .? dottedId dottedId?
    ;
```
Who the heck wrote this `.?`?? This is terrible.

**Review by KvanTTT — APPROVED** [review]

**Comment by vjuranek** [comment]
@kaby76 removed. Thanks for digging into this issue and for your findings!

**Comment by teverett** [comment]
@vjuranek  thanks!

**Pull request merged**
