### PR TITLE
Add Cpp target support for PhpLexer

### PR DESCRIPTION
**Pull request by halx99**
Notes: the cpp `PhpLexerBase` was translate from c#, java line by line.

### CODE REVIEW

**Comment by halx99** [comment]
dependent patch: https://github.com/antlr/antlr4/pull/4125

**Comment by parrt** [comment]
ping @marcospassos.  @halx99 I think this goes in https://github.com/antlr/antlr-php-runtime

**Comment by halx99** [comment]
> ping @marcospassos. @halx99 I think this goes in https://github.com/antlr/antlr-php-runtime

Not php runtime which for PHP target, this PR is for Cpp target.

**Comment by parrt** [comment]
Oh sorry. I think you meant this for grammars-v4 repo then.

**Comment by halx99** [comment]
Yes, so please open it

**Comment by parrt** [comment]
Sorry

**Comment by teverett** [comment]
@halx99 good to merge this now?

**Comment by halx99** [comment]
> @halx99 good to merge this now?

Yes, plz merge it, thanks.

**Comment by teverett** [comment]
@halx99 thanks!

**Pull request merged**
