### PR TITLE
[python3] Remove obsolete grammar python3

### PR DESCRIPTION
**Pull request by kaby76**
This is a fix for #3833.
* The tests from python3 have be copied into python3_12_0. Everything parses with the new grammar, apparently correct, although I have not checked expression.
* The directory python/python3/ containing grammar has been removed.
* The super pom.xml has been updated.

To do:
* Bring python3_12_0/ grammars into standard target agnostic format.
    * Rename "self" to "this".
    * Include comments for Cpp target.
* Add ports for Cpp, Dart, Go, JavaScript, PHP, TypeScript.
* Add missing `Reset()` methods to parser and lexer base classes to reinitialize. Critical for standard template drivers `-tokens` argument.

### CODE REVIEW

**Comment by kaby76** [comment]
> Hi, I work on ports and modifications, I hope I have more time lately.

Not necessary. I'll be done with the remaining ports by the end of the weekend.

Also, I want to review this grammar more carefully. For example, I noticed my static checks flagged [there were useless parentheses](https://github.com/antlr/grammars-v4/actions/runs/7054706053/job/19204001804#step:21:85). I was going to correct that, but then realized that those parentheses included negative lookahead checks that were in the PEG grammar that you didn't add. Did you check these cases carefully? I also noticed there are no .tree files to test parse trees.

**Comment by RobEin** [comment]
Sorry, but I don't know what you mean by testing  .tree files.

**Comment by kaby76** [comment]
The .tree files are the parse trees as represented by the `toStringTree()` method in the Antlr runtime. The presence of the files test consistency of the tree across targets, OSes, between versions of the grammar, and between versions of the Antlr tool and runtime.

**Comment by RobEin** [comment]
I understand. So comparing the text-tree of the same input with an older Python parser and the current python3_12_0.
In principle, they should be the same.
Good idea. I haven't done this yet, but I'll check it out.

**Comment by RobEin** [comment]
Unfortunately, this is not a feasible way, because the Python parser rules in older versions have different names than the rule names in python3_12_0.

**Comment by kaby76** [comment]
> Can I help something about translations?

@RobEin I'm working on the C++ port. I haven't had time to visit this lately because of the many issues with the builds for the repo. I am planning to continue this port soon.

**Comment by RobEin** [comment]
I may start the javascript port if it does not cause collision.

**Comment by kaby76** [comment]
> I may start the javascript port if it does not cause collision.

That'll be great. Thanks.

**Comment by RobEin** [comment]
The JavaScript port is [ready](https://github.com/RobEin/ANTLR4-parser-for-Python-3.12/tree/main/port_JavaScript).
In addition:
 - `self` references renamed to `this` in the [parser grammar](https://github.com/RobEin/ANTLR4-parser-for-Python-3.12/blob/04fbc3d79928b0e7d50e778293e603c48d961eae/PythonParser.g4#L874) and transformGrammar.py added to [Python3 port](https://github.com/RobEin/ANTLR4-parser-for-Python-3.12/tree/main/port_Python3)
 - added reset() methods to the PythonLexerBase.*

I will also make a PR to the antlr/grammars-v4 soon.
I continue the porting with TypeScript.

**Pull request closed without merging**
