### PR TITLE
Master

### PR DESCRIPTION
**Pull request by xnappy**
Add sybaseIQ grammar and few examples

### CODE REVIEW

**Comment by KvanTTT** [comment]
Even not renamed from "tsql" to "sybaseiq".

**Comment by parrt** [comment]
Can you add a note that you derived from the tsql grammar and then name the grammar appropriately inside the file? As @KvanTTT says, name is wrong.

**Comment by xnappy** [comment]
sorry! I didn't pay enough attention yesterday was a long night watching the oscars ;-)

**Comment by teverett** [comment]
@xnappy are we closing this pull?

**Pull request closed without merging**
