### PR TITLE
Reworking SQLite grammar

### PR DESCRIPTION
**Pull request by Marti2203**
Issue #250 mentioned the grammar has an issue and I started to poke it around. I saw that many things were not very structurally okay - there were a little inconsistencies of the names, a strange prefix, some repetitions. Another issue was that the grammar was big so I split it into a lexer and parser. There are still things to be done, but I think that this is a bit better than before.

### CODE REVIEW

**Comment by Marti2203** [comment]
@KvanTTT I am sorry to bother you, but I am still new with the tests in the system. Can you tell me where the test is located so I can see what it expects?

**Comment by KvanTTT** [comment]
You should add sqlite to the [global pom.xml](https://github.com/antlr/grammars-v4/blob/master/pom.xml) and change [local pom.xml](https://github.com/antlr/grammars-v4/blob/master/sql/sqlite/pom.xml) with considering of your improvements. After that, you will be able to run maven tests by the following command: `mvn test`.

**Comment by Marti2203** [comment]
@KvanTTT this is strange, I ran the file in `grun` (the ANTLR testrig) and it parsed without issues, but when I tried to do it in `mvn test`, I get a `no viable alternative`.

**Comment by KvanTTT** [comment]
Maybe @teverett can give a piece of advice because he knows maven better :)

As I understand there are some errors during parsing with SQLite grammars, see https://github.com/antlr/grammars-v4/pull/1808/checks?check_run_id=948130080#step:4:9861

**Comment by Marti2203** [comment]
The parser says there are no alternatives while grun shows a perfectly built tree that is strange and I am not experienced with maven a lot such that I can get info.

**Comment by teverett** [comment]
I'm just a wee bit busy with work.  Can i take a look on the weekend?

**Comment by Marti2203** [comment]
Yeah, not a problem. I will make some more pull requests until then

**Comment by teverett** [comment]
@Marti2203  whats the root rule name in your grammar?

**Comment by Marti2203** [comment]
The original author named it parse

**Comment by KvanTTT** [comment]
Yes, and it's the first.

**Comment by Marti2203** [comment]
Okay, it breaks on my machine now. I can fix it and test it!

**Comment by Marti2203** [comment]
@KvanTTT I think it is fixed. It has passed all checks and conforms to the diagrams the SQLite website

**Pull request merged**
