### PR TITLE
Improved tsql structure, added grant statement

### PR DESCRIPTION
**Pull request by KvanTTT**

### CODE REVIEW

**Comment by parrt** [comment]
heh, cool!  Hmm...Something is strange because it is not running the tests... @teverett  any ideas?

**Comment by teverett** [comment]
I had this problem yesterday; travis didn't do the build for a number of hours.  Let's leave it for maybe a day and see what happens.

**Comment by parrt** [comment]
strange.  the other PR just had the tests execute but this one still does not execute them.

**Comment by teverett** [comment]
Maybe add a space and commit.  perhaps that will trigger travis.


On Mon, May 23, 2016 at 5:35 PM, Terence Parr <notifications@github.com>
wrote:

> strange. the other PR just had the tests execute but this one still does
> not execute them.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/grammars-v4/pull/390#issuecomment-221126566>
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by KvanTTT** [comment]
Generally this is a very strange pull request. During some time I was not able to create it, because of disappearing. Moreover I was not able to navigate over github. After some romp I created it and now tests are not running.

**Comment by teverett** [comment]
If you look in travis; you'll see that travis never saw the pull request.

On Tue, May 24, 2016 at 7:09 AM, Ivan Kochurkin <notifications@github.com>
wrote:

> Generally this is a very strange pull request. During some time I was not
> able to create it, because of disappearing. Moreover I was not able to
> navigate over github. After some romp I created it and now tests are not
> running.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/grammars-v4/pull/390#issuecomment-221262977>
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by parrt** [comment]
Still no tests. hmm...does `$ mvn test` work for you? If so I can merge.

**Comment by teverett** [comment]
I suggest pulling from antlr trunk into the merge branch, and committing
that to the merge branch. I've done that before and it results in travis
kicking off a build.


On Tue, May 24, 2016 at 10:08 AM, Terence Parr <notifications@github.com>
wrote:

> Still no tests. hmm...does $ mvn test work for you? If so I can merge.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/grammars-v4/pull/390#issuecomment-221321466>
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by KvanTTT** [comment]
Please close it. I created another one: https://github.com/antlr/grammars-v4/pull/392

**Pull request closed without merging**
