### PR TITLE
Issue 2929

### PR DESCRIPTION
**Pull request by kaby76**
Preliminary changes to bring python/python3 grammar up to date with 3.11 and Spec.

https://github.com/antlr/grammars-v4/issues/2929

### Renamings
* Renamed `simple_stmt` to `simple_stmts` to be the plural of `simple_stmt`, corresponding to the Spec grammar.
* Renamed `small_stmt` to `simple_stmt`, corresponding to the Spec grammar.
* Renamed `suite` to `block`, corresponding to the Spec grammar.
### Reordering
* Reordered keywords in lexer grammar so you can find them. It is ridiculous finding and adding a new keyword without some basic sanity. Note, this is possible because Antlr lexer rules match (1) maximum-lengthed strings, (2) match the first lexer rule if multiple lexer rules match the string. Fortunately, all keyword rules were already grouped together prior to this PR.
### Added rules
* Added `match_stmt` to `compound_stmt` as in the Spec.
* Added rules associated with `match_stmt`.
* Added '_' to `atom` in order to back support for-statement. __I'm not sure if the underscore should be a different token, but I'm tending toward this in order to support patterns in match statements.__
* Added rule `name : NAME | .....;` rule in order to allow certain keywords as identifiers. Renamed applied occurrences of `NAME` to `name`.
* Removed mutual-left recursion in `attr` and `name_or_attr` present in Spec grammar, via unfolding of `name_or_attr` into RHS of `attr`.
### Other grammar changes
* Removed useless parentheses.
## Code changes
* Added reset()/Reset() to Java/CSharp base class lexer code.
* Added parser base classes for semantic predicates. Those predicates currently are stubs returing true.
* Untabified target code because tabs expand to a variable number of spaces per editor.
## Git changes
* Added "Grammars*" to .gitignore for new trgen target directories, in which trgen can generate drivers for all targets for side-by-side comparison without moving Generated/ code around.
## Test changes
* match.py
* match2.py
* Added the JavaScript testing of python/python3.
* Added test-parsing.sh to test parser against entire cpython source code. 156 failed to parse out of 1897 total, which is about 8% failed. The total time for an unloaded Ryzen 7 2700, 16GB machine to parse with C# was 25.75m.
## Ignored
* Note, no attempt was made to update python/python. That is a "unified" grammar for Python2 and Python3. I really don't understand how one can deal with all the similarly named rules and conflicts in merging rules for similar syntax between Python2 and Python3. In my opinion, this is extremely difficult to do correctly, which is why I will not touch that grammar.
* I did not attempt to update the target-specific Python3 grammars, like [python3-cpp](https://github.com/antlr/grammars-v4/tree/master/python/python3-cpp), [python3-py](https://github.com/antlr/grammars-v4/tree/master/python/python3-py), [python3-ts](https://github.com/antlr/grammars-v4/tree/master/python/python3-ts). Those are old and should just be removed. Whoever wrote them should determine whether to delete or not.
## To do
* Semantic predicates will need to be added, but there are already many in the python/python3 grammar.
* The generated parser is slow. This is specifically due to the rules for expressions. I will fix this and the expressions in the grammar to use optimized Antlr rules in another PR after this.
* I am still working on Dart, Go, and PHP ports. Those will be in another PR after this.

### CODE REVIEW

**Comment by hasii2011** [comment]
attaching as per your [instructions](https://stackoverflow.com/questions/74563209/python-3-10-antlr-parser?noredirect=1#comment131636403_74563209)
[Archive.zip](https://github.com/antlr/grammars-v4/files/10097393/Archive.zip)

**Comment by kaby76** [comment]
My new grammar parses these files. I had to pitch much of the old grammar and use the Spec grammar. It will be in the next PR after this is merged.

**Comment by hasii2011** [comment]
I'll keep my eyes open for the merge

**Comment by teverett** [comment]
@kaby76 thanks!

**Comment by hasii2011** [comment]
Ok,  this update works great with Python 3.10 code;  For me other than a minor file edit to Python3LexerBase to account for my package structure, it was essentially a drop-in replacement once I generated the new code.  Thanks for this work

**Pull request merged**
