### PR TITLE
[Sq][Hive]  _id supports more keyword parsing

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by caicancai** [comment]
Hive SQL seems to lack example cases

**Comment by caicancai** [comment]
cc @kaby76

**Comment by caicancai** [comment]
> Please add some tests to [examples](https://github.com/antlr/grammars-v4/tree/af3d5f7397685bfead506defe96643d3971abbbd/sql/hive/v4/examples) that tests at least some of the changes.

I passed the local test and submitted a PR

**Comment by kaby76** [comment]
> I passed the local test and submitted a PR[.]

You added and pushed the change (https://github.com/antlr/grammars-v4/pull/4156/files#diff-3741f3effc3078a16de28abba95b6c098095ae2ddc543fb8b65960576e037a3b), but you then closed the PR. Nothing will be merged if you don't re-open the PR.

**Comment by caicancai** [comment]
> > I passed the local test and submitted a PR[.]
> 
> You added and pushed the change (https://github.com/antlr/grammars-v4/pull/4156/files#diff-3741f3effc3078a16de28abba95b6c098095ae2ddc543fb8b65960576e037a3b), but you then closed the PR. Nothing will be merged if you don't re-open the PR.

Because I found that the cli failed, but I didn't reproduce it locally

**Comment by kaby76** [comment]
> Because I found that the [CI -- Continuous Integration testing, also know as "the build" or "the Github Action Build"] failed, but I didn't reproduce it locally

Generally, submit new PRs as "draft", or change the PR to "draft". There is no need to close the PR, then reopen another PR. Besides, generally speaking, Tom will not merge a PR if the build fails. But, it's best to make the PR a draft so he doesn't need to look at the build for the PR. Sometimes builds fail because of time outs, not because of a problem with the code that was checked in.

**Pull request closed without merging**
