### PR TITLE
informix-sql:add support of rename index.

### PR DESCRIPTION
**Pull request by hellozrh**
informix-sql:add support of rename index.

### CODE REVIEW

**Comment by kaby76** [comment]
Go build failed due to "antlr4" not being robust. https://github.com/antlr/antlr4-tools/issues/13. This is caused because the version of Antlr for the Go target is always the tip, so the "antlr4" script tries to find out what is the latest version of Antlr4. I will try redoing the Go target templates so that it works against 4.13.0 explicitly, which will avoid all this unrobust code in the Python3 script.

Otherwise, the build passed on your changes.

**Comment by hellozrh** [comment]
> 

I see, and this problem also appeared last time, it has been solved after I resubmited something.

**Comment by hellozrh** [comment]
Oh, it failed again.  That's it , wait for you to specify the version.

**Review by KvanTTT — APPROVED** [review]

**Comment by kaby76** [comment]
@teverett I think this is good to merge.

**Review by KvanTTT — APPROVED** [review]

**Comment by kaby76** [comment]
@KvanTTT Thanks!

**Pull request merged**
