### PR TITLE
Recognise for in and for of iteration statements without NoViableAltException

### PR DESCRIPTION
**Pull request by spencerxiao**
This PR tries to fix the issue #1636, let me know your thoughts

### CODE REVIEW

**Comment by KvanTTT** [comment]
Could you please add a code sample that was parsed incorrectly before your changes and is parsed correctly after?

**Comment by spencerxiao** [comment]
The parser although can recognise the following code snippet but it also outputs error message saying that  `line 2:11 no viable alternative at input 'of'. `
```javascript
var fibonacci = [1, 3];
for (var n of fibonacci) {
  console.log(n);
}
```

You can verify with the following unit test. Note that the `ctx.exception` is not null when it parses the for statement and thus the parser outputs the above error message. With this patch, the test case passes. 

```java
    @Test
    public void testForInAndForOfStatements() {
        String programStr = "var fibonacci = [1, 3];\n"+
                "for (var n of fibonacci) {\n" +
                "    console.log(n);\n" +
                "}";
        JavaScriptLexer lexer = new JavaScriptLexer(CharStreams.fromString(programStr));
        lexer.setUseStrictDefault(true);
        CommonTokenStream tokenStream = new CommonTokenStream(lexer);
        JavaScriptParser parser = new JavaScriptParser(tokenStream);
        ParserRuleContext program = parser.program();

        new JavaScriptParserBaseVisitor<Void>() {
            @Override
            public Void visitVariableDeclaration(JavaScriptParser.VariableDeclarationContext ctx) {
                super.visitVariableDeclaration(ctx);
                assertNull(ctx.exception);
                return null;
            }
        }.visit(program);
    }
```

**Comment by KvanTTT** [comment]
Do we have the same sample in Iteratos.js file? https://github.com/antlr/grammars-v4/blob/master/javascript/javascript/examples/Iterators.js#L21-L25

**Comment by spencerxiao** [comment]
Yes, we already have the example, actually the above code snippet is an excerpt from that file.

**Comment by KvanTTT** [comment]
Ok then. Thanks.

**Pull request merged**
