### PR TITLE
Updated PHP Grammar Documentation about Python Runtimes

### PR DESCRIPTION
**Pull request by dkazantzas**
Added a section in the `README.md` of the PHP Grammar so that users can address the issue that is reported in #2730

### CODE REVIEW

**Comment by dkazantzas** [comment]
I've followed the suggestion by @kaby76 in the discussion of #2730 and added a script to transform the Grammar

**Comment by kaby76** [comment]
Please also remove [the "php" line from the skip-python3.txt file](https://github.com/dkazantzas/grammars-v4/blob/4d1a0dc07d8c05e14df681cd10a7034bc74650a2/_scripts/skip-python3.txt#L63). The file tells the build script to "skip" doing the build for the "php/" grammar. When the line is removed, the build will attempt to run regression tests on the grammar.

**Comment by dkazantzas** [comment]
Ok done.

**Comment by kaby76** [comment]
Almost there.

* The directory php/Python/ should be renamed php/Python3/. There really isn't a "Python" target, but either "Python2" or "Python3". The build script checks for the directory in the source, then copies that code for that target in with the rest of the code (where the .g4's reside). After renaming, it fails with several other errors.
* There are two syntax errors in PhpLexer.py. To correct, update transformGrammar.py with the a few lines to change "true" to "True". Context is added because there is a grammar option with "true" that shouldn't be changed.
```
$ diff dkazantzas/php/Python/transformGrammar.py dkazantzas2/php/Python/
30,33d29
<         if '_scriptTag = true;' in x:
<             x = x.replace('_scriptTag = true;', '_scriptTag = True;')
<         if '_styleTag = true;' in x:
<             x = x.replace('_styleTag = true;', '_styleTag = True;')
```
* The PhpParserBase.py file looks like it always contained errors, which wouldn't be detected because the compiler doesn't flag it until executed unless you run the test suite in examples/.
```
$ diff dkazantzas/php/Python/PhpLexerBase.py  dkazantzas2/php/Python/
121c121
<             self._channel = self.SKIP
---
>             self.channel(SkipChannel)
```

**Comment by dkazantzas** [comment]
Made those changes too. I really appreciate your help in this.

**Comment by teverett** [comment]
@kaby76  thanks.  Let's fix the Dart issue before it gets pulled.

**Comment by kaby76** [comment]
> @kaby76 thanks. Let's fix the Dart issue before it gets pulled.

@teverett 

I created a Github Issue for this https://github.com/antlr/grammars-v4/issues/2743

As I explained there, we've been getting a "Connection closed before full header was received" on Window and Macos. I think it's because the network connection for the Github Actions servers or (more likely) the Dart servers are boxes of unreliable junk. It could be both.

To work around this problem I will submit a separate PR to retry the "dart pub get" until the return code is zero or some could like 10x's.

Could you invoke the action for this PR again in order to test the non-determinism of the machines?

**Comment by teverett** [comment]
@kaby76  yup!

**Comment by kaby76** [comment]
@teverett  Thanks. It happened again. I'll check it out locally on my machines to see what I can do.

**Comment by kaby76** [comment]
@teverett I created a PR to wrap the "dart pub get" in a loop to repeat on error. It doesn't hurt the build, may help in these dart connection drops, but who knows. Once merged, maybe this PR can be rebased and checked?

**Comment by teverett** [comment]
@github rebase

**Comment by kaby76** [comment]
@dkazantzas Please fast forward your repo so it can be rebuilt.

**Comment by dkazantzas** [comment]
@kaby76 Done

**Comment by kaby76** [comment]
@dkazantzas That looks good. @teverett Build? Let's see if this works.

**Comment by kaby76** [comment]
@dkazantzas Please fast forward your repo so it can be rebuilt with the latest fixes for Go builds. Thanks.

**Comment by dkazantzas** [comment]
@kaby76 I've synced my repo, it should now be ok

**Comment by kaby76** [comment]
@teverett This is ready to rebuild. Could you set a build going? I think we should no longer have Dart and Go build errors, but let's just see. Thanks.

**Comment by teverett** [comment]
@kaby76  done, thanks for the reminder.

**Comment by kaby76** [comment]
@teverett Works perfectly.

**Comment by teverett** [comment]
@dkazantzas  @kaby76  thanks

**Pull request merged**
