### PR TITLE
Add support to Objective-C generics (2015)

### PR DESCRIPTION
**Pull request by Cmejia**
Added support in the grammar, and added a sample declaration in the test files

### CODE REVIEW

**Comment by parrt** [comment]
Hi! I can't figure out the "Merge branch 'refs/heads/antlr/master'" commit. what is that pulling in? it seems huge.

**Comment by Cmejia** [comment]
I merged from the antlr4/master.  because my own branch was 200 commits behind. 
Did I do it on the wrong order ?

**Comment by parrt** [comment]
ah. ok, let me check real quick manually.

**Comment by parrt** [comment]
looks good. thanks.

**Pull request merged**
