### PR TITLE
Add support for parse tree verification in tests

### LINKED ISSUE #2837: Add support for parse tree verification in tests
In [ANTLR discussion 3321](https://github.com/antlr/antlr4/discussions/3321#discussioncomment-3642335), @kaby76  wrote:

> The [line for calling the parser](https://github.com/antlr/grammars-v4/blob/553522db0536ca80e0535351a19bdd8cbcc14e77/_scripts/templates/Java/test.sh#L14) doesn't do anything with doing tree diffs. It should be fixed.

I've got a change in progress that will do this.

### PR DESCRIPTION
**Pull request by RossPatterson**
The `antlr4test-maven-plugin` tool used in the Maven build system supports test cases where success is not based just on being able to parse a file, but also to generate a parse tree that matches an expected parse tree.  This expected tree is supplied as a file, in the same directory as the test case, with `.tree` appended to the name (_e.g._, `example1.txt` and `example1.txt.tree`).  It compares the tree produced by `org.antlr.v4.runtime.tree.ParseTree.toStringTree()` against the contents of the file, and if they are identical, the test succeeds.  Otherwise, it fails.

This change adds similar support to the `trgen` test system used in the continuous integration system (among other places).  It uses the same expected tree files, and the same ANTLR code to produce the test case's tree.

As with `antlr4test-maven-plugin`, the verification of the parse tree is skipped if there is no expected tree file.

Fixes #2837

### CODE REVIEW

**Comment by RossPatterson** [comment]
The `build-cpp`  CI job is failing.  Obviously I used the wrong method call to generate the tree file.  I'll check that out and push a fix soon.

**Comment by RossPatterson** [comment]
More CI failures:
- [build-csharp](https://github.com/antlr/grammars-v4/actions/runs/3119850523/jobs/5060065698#logs),[build-php](https://github.com/antlr/grammars-v4/actions/runs/3119850523/jobs/5060065622#logs): Various tests failing, but now with `diff` output, so they can be diagnosed.  It appears they may all be due to missing newlines at the end of the reference files (`whatever.tree`).
- [build-pwsh (*, Java)](https://github.com/antlr/grammars-v4/actions/runs/3119850523/jobs/5060066128#logs): As noted above, the `grammars-v4\php` parser throws a NPE from `org.antlr.v4.runtime.misc.Utils.escapeWhitespace(Utils.java:63)` when trying to format tree strings, due to  [`antlr4` issue #2677](https://github.com/antlr/antlr4/issues/2677)).  "Fixed" by adding php to `grammars-v4/_scripts/skip-java.txt` and `grammars-v4/_scripts/skip-java.why` until the bug gets fixed.
- [build-pwsh (windows-latest, Java)](https://github.com/antlr/grammars-v4/actions/runs/3119850523/jobs/5060066128#logs): `grammars-v4\unicode\graphemes` examples `emoji.txt` and `udhr.txt` failed tree verification.
- [build-cpp](https://github.com/antlr/grammars-v4/actions/runs/3119850523/jobs/5060065947#logs): `grammars-v4/antlr/antlr4` example `three.g4` generares an expected error ("_line 4:0 mismatched input '<EOF>' expecting {'lexer', 'parser', 'grammar'}_").  The test ends saying "_Parse failed._", but the test fails saying "_Expected parse fail._", so something's confused about the test status.

**Comment by RossPatterson** [comment]
Today's CI errors:

- [build-cpp](https://github.com/antlr/grammars-v4/actions/runs/3131603578/jobs/5083107695): `grammars-v4/antlr/antlr4` example `three.g4` generares an expected error ("_line 4:0 mismatched input '<EOF>' expecting {'lexer', 'parser', 'grammar'}_").  The test ends saying "_Parse failed._", but the test fails saying "_Expected parse fail._", so something's confused about the test status.  The fix in commit 23342fad6d60254ed749379de6d52ae73b6e4dfc missed a return of the status in the call chain.  Fixed by commit faf2027cbd86398c2cf1925286a5912e6b713e86.
- [build-pwsh (*, CSharp)](https://github.com/antlr/grammars-v4/actions/runs/3131603578/jobs/5083108925): Typo in CSharp comment.  Fixed by commit 4e42a87dc9be4b8517a2ebe78b1236f36bb9ab81.
- [build-pwsh (macos-latest, Go)](https://github.com/antlr/grammars-v4/actions/runs/3131603578/jobs/5083108367):  A bunch of [weird errors processing the `grammars-v4/b` grammar](https://github.com/antlr/grammars-v4/actions/runs/3131603578/jobs/5083108367#step:17:980).  I cannot reproduce these on my Windows machine, and the line numbers in error are part of the `serializedATN` data, which is generated by ANTLR itself.  I'm going to ignore it this one time, and see if it recurs.  The errors are:
```
Error: parser/b_parser.go:86:45: syntax error: unexpected ., expecting expression
Error: parser/b_parser.go:87:133: syntax error: unexpected ] in composite literal; possibly missing comma or }
Error: parser/b_parser.go:88:1: syntax error: unexpected <, expecting }
Error: parser/b_parser.go:93:196: invalid character U+0023 '#'
Error: parser/b_parser.go:93:247: invalid character U+005C '\'
Error: parser/b_parser.go:100:196: invalid character U+0023 '#'
Error: parser/b_parser.go:100:247: invalid character U+005C '\'
parser/b_parser.go:107: invalid character U+0023 '#'
parser/b_parser.go:107: invalid character U+005C '\'
parser/b_parser.go:114: invalid character U+0023 '#'
parser/b_parser.go:114: too many errors
```

**Comment by RossPatterson** [comment]
At this point, I believe this work is complete, and ready to merge.

- Java CI builds now skips `grammars-v4/php`, due to [`antlr4` issue #2677](https://github.com/antlr/antlr4/issues/2677).
- All templates now send tree output to stdout, and everything else to stderr.
- All bash test drivers now correctly report successful parses that were expected to fail as test failures.    The PowerShell test drivers already did so.
- All test drivers now create tree output, and if there is a reference file, compare against it.
- All PowerShell test drivers now correctly process UTF-8 tree data.  The bash test drivers already did so.
- The Java and Python3 test drivers now correctly process UTF-8 tree data.  The other target test drivers already did so.
- The Cpp test driver now correctly reports when a test generates lexer or parser errors.    The other target test drivers already did so.
- The strange behaviour of the [`grammars-v4/b` macos Go test](https://github.com/antlr/grammars-v4/actions/runs/3131603578/jobs/5083108367#step:17:980) is not reproducible.  Since the errors appear within a block that was generated by the `antlr4` tool, I'm not going to dig into it.
- All non-skipped tests are succeeding.

**Comment by teverett** [comment]
@KvanTTT @kaby76  any concerns before I merge this?

**Comment by kaby76** [comment]
@teverett These are good changes, fixing a number of problems.

**Comment by KvanTTT** [comment]
I have no objection.

**Comment by teverett** [comment]
@RossPatterson thanks!

**Pull request merged**
