### PR TITLE
Fixed lexer handling of [..arg actions..]. 

### PR DESCRIPTION
**Pull request by grosenberg**
Lexer emitter now ignores '@header' and similar actions from setting the current token type.

Formatted java files to spaces only.

### CODE REVIEW

**Comment by parrt** [comment]
hmm...looks like some of the tests fail.

**Comment by teverett** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project antlr4: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/antlr/grammars-v4/antlr4/target/generated-sources/antlr4/org/antlr/parser/antlr4/ANTLRv4Lexer.java:[13,35] cannot find symbol
[ERROR] symbol: class LexerAdaptor
[ERROR] /home/travis/build/antlr/grammars-v4/antlr4/target/generated-sources/antlr4/org/antlr/parser/antlr4/ANTLRv4Lexer.java:[112,9] method does not override or implement a method from a supertype
[ERROR] /home/travis/build/antlr/grammars-v4/antlr4/target/generated-sources/antlr4/org/antlr/parser/antlr4/ANTLRv4Lexer.java:[118,9] method does not override or implement a method from a supertype
[ERROR] /home/travis/build/antlr/grammars-v4/antlr4/target/generated-sources/antlr4/org/antlr/parser/antlr4/ANTLRv4Lexer.java:[127,17] cannot find symbol
[ERROR] symbol:   variable _interp
[ERROR] location: class org.antlr.parser.antlr4.ANTLRv4Lexer
[ERROR] /home/travis/build/antlr/grammars-v4/antlr4/target/generated-sources/antlr4/org/antlr/parser/antlr4/ANTLRv4Lexer.java:[127,27] no suitable constructor found for LexerATNSimulator(org.antlr.parser.antlr4.ANTLRv4Lexer,org.antlr.v4.runtime.atn.ATN,org.antlr.v4.runtime.dfa.DFA[],org.antlr.v4.runtime.atn.PredictionContextCache)
```

**Comment by grosenberg** [comment]
The errors make no sense - at least that I can make out. LexerAdapter.java is plainly present. The variable '_interp' is not used/does not appear anywhere in the files.  The test itself appears borked.

**Comment by grosenberg** [comment]
Under https://travis-ci.org/antlr/grammars-v4/requests the build is reported as having completed correctly!  Github is borked!

**Comment by teverett** [comment]
I'll take a look.

**Comment by teverett** [comment]
ok there are two problems.  The first problem is that LexerAdaptor.java needs to be copied into target/ so that maven can compile it.  Just add this into the pom.xml

<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/target/generated-sources/antlr4/org/antlr/parser/antlr4</outputDirectory>
							<resources>
								<resource>
									<directory>${basedir}</directory>
									<includes>
										<include>LexerAdaptor.java</include>
									</includes>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

The second problem is that LexerAdaptor.java includes "import net.certiv.antlrdt4.core.parser.gen.AntlrDT4Lexer".  @grosenberg if you have put this into a public maven repo, then we can fix that problem by including it as a maven dependency.

**Comment by grosenberg** [comment]
@teverett - thanks for the help. Have it sorted now. Should be ready for merging.

**Comment by parrt** [comment]
Ok, so I should merge this (manually) or are we still working on the /**/ issue?

**Comment by teverett** [comment]
I think the right thing to do would be for @grosenberg to pull-merge onto his branch grosenberg:master.  We can commit after than and then figure out the /**/ ambiguity.

**Comment by parrt** [comment]
btw, can we fix lexer with tweak:?
```
fragment BlockComment	: '/*' ~'*' .*? ('*/' | EOF)	;
```

**Comment by teverett** [comment]
Gimme 2 min to check.


On Sat, May 28, 2016 at 11:22 AM, Terence Parr <notifications@github.com>
wrote:

> btw, can we fix lexer with tweak:?
>
> fragment BlockComment   : '/*' ~'*' .*? ('*/' | EOF)    ;
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/antlr/grammars-v4/pull/382#issuecomment-222319589>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABK1ZpM1xzYDu_6ldMJEtFsAmm4a3FXAks5qGHnegaJpZM4Iht_P>
> .
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by teverett** [comment]
same issue:

Parsing :/Users/tom/projects/grammars-v4/antlr4/examples/three.g4

[@0,0:24='/**/\ngrammar three;\n/* */',<4>,1:0]

[@1,25:25='\n',<53>,channel=2,3:5]

[@2,26:25='<EOF>',<-1>,4:0]

line 4:0 no viable alternative at input '<EOF>'




On Sat, May 28, 2016 at 11:23 AM, Tom Everett <tom@khubla.com> wrote:

> Gimme 2 min to check.
>
>
> On Sat, May 28, 2016 at 11:22 AM, Terence Parr <notifications@github.com>
> wrote:
>
>> btw, can we fix lexer with tweak:?
>>
>> fragment BlockComment   : '/*' ~'*' .*? ('*/' | EOF)    ;
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/antlr/grammars-v4/pull/382#issuecomment-222319589>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABK1ZpM1xzYDu_6ldMJEtFsAmm4a3FXAks5qGHnegaJpZM4Iht_P>
>> .
>>
>
>
>
> --
> A better world shall emerge based on faith and understanding  - Douglas
> MacArthur
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by parrt** [comment]
crap. ok it's the EOF after `.*?`, which is totally justified in consuming up until EOF.  perhaps we split into correct and error rules.

```
fragment BlockComment   : '/*' .*? '*/' ;
UnterminatedBlockComment   : '/*' .*? EOF    ; // put this rule last in grammar so low priority
```

**Comment by teverett** [comment]
@grosenberg could you please fix the merge conflicts so we can merge this?

**Comment by teverett** [comment]
@grosenberg this pull request has been stale for quite a new months now.  Can I close it?

**Comment by teverett** [comment]
@grosenberg closed.  If you still wish to pull, please fix the merge errors and resubmit the pull.

**Pull request closed without merging**
