### PR TITLE
[Postgres][Imporve] Change the var keyword to the Java base class ProxyErrorListener

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by caicancai** [comment]
@kaby76 PATL, thank you

**Comment by kaby76** [comment]
Please explain why "var" was changed to the explicit type. Thanks.

**Comment by caicancai** [comment]
> Please explain why "var" was changed to the explicit type. Thanks.

Java 8 does not support the var keyword. The var keyword is supported starting from Java 10. When using some older Java 8 versions, the var keyword may report an error.
image

**Comment by kaby76** [comment]
You are right. Java 10 introduced "var". We don't have a way specifying in the desc.xml the minimum version of Java, or any other target language, required. This is all hardwired in the testing templates.

https://github.com/antlr/antlr4/releases#:~:text=class%20files%20for%20the%20ANTLR,bumping%20up%20from%20Java%207).

The PR looks fine.

**Comment by teverett** [comment]
@caicancai  thanks!

**Pull request merged**
