### PR TITLE
antlr4 LexerAdaptor.js

### PR DESCRIPTION
**Pull request by cancerberoSgx**
added LexerAdaptor.js to antlr4 grammar to easily support JavaScript target

### CODE REVIEW

**Comment by teverett** [comment]
@cancerberoSgx could you please close this PR, pull from TRUNK and re-submit?

**Comment by cancerberoSgx** [comment]
@teverett Sorry, I'm not following, what's TRUNK ? is there another repo / branch I should use ? Thanks

**Comment by teverett** [comment]
@cancerberoSgx all good.   Please just pull from https://github.com/antlr/grammars-v4.git and then resubmit your pull request.

**Comment by KvanTTT** [comment]
Why not rebase on master?

**Pull request closed without merging**
