### PR TITLE
[postgresql] Fix for #4354 (#4354)

### PR DESCRIPTION
**Pull request by be-happy4**
Add hex and binary literal support for iconst node, so that it can be used in param and array index.
Some databases distinguish between lowercase 'b' and uppercase 'B', and the uppercase will cause compilation errors. For example, clickhouse. PostgreSQL has no such problem.

image
image

### CODE REVIEW

**Comment by kaby76** [comment]
Please add your test to examples/.
```
select 0x10, 0b10, 0X10, 010, 0 x10, 0 b10;
```

And, please add the .tree file produced by using the Trash toolkit.
```
(root (stmtblock (stmtmulti (stmt (selectstmt (select_no_parens (select_clause (simple_select_intersect (simple_select_pramary select (target_list_ (target_list (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0x10))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0b10))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0X10))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 010))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0)))))))))))))))))))))))) (bareColLabel (identifier x10))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0)))))))))))))))))))))))) (bareColLabel (identifier b10))))))))))) ;)) <EOF>)
```
There is no newline character at the end of the parse tree.

This is to make sure there are no regressions when someone changes the grammar later on. And, while the serialized tree produced by ["toStringTree()"](https://github.com/antlr/antlr4/blob/67228355c5bfd1ed5ebb89e726992ec43dda7b53/runtime/Java/src/org/antlr/v4/runtime/tree/Trees.java#L48) doesn't output the token type of tokens, at least it will be better than having no tree to fallback on.

Thanks!

**Comment by be-happy4** [comment]
> Please add your test to examples/.
> 
> ```
> select 0x10, 0b10, 0X10, 010, 0 x10, 0 b10;
> ```
> 
> And, please add the .tree file produced by using the Trash toolkit.
> 
> ```
> (root (stmtblock (stmtmulti (stmt (selectstmt (select_no_parens (select_clause (simple_select_intersect (simple_select_pramary select (target_list_ (target_list (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0x10))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0b10))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0X10))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 010))))))))))))))))))))))))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0)))))))))))))))))))))))) (bareColLabel (identifier x10))) , (target_el (a_expr (a_expr_qual (a_expr_lessless (a_expr_or (a_expr_and (a_expr_between (a_expr_in (a_expr_unary_not (a_expr_isnull (a_expr_is_not (a_expr_compare (a_expr_like (a_expr_qual_op (a_expr_unary_qualop (a_expr_add (a_expr_mul (a_expr_caret (a_expr_unary_sign (a_expr_at_time_zone (a_expr_collate (a_expr_typecast (c_expr (aexprconst (iconst 0)))))))))))))))))))))))) (bareColLabel (identifier b10))))))))))) ;)) <EOF>)
> ```
> 
> There is no newline character at the end of the parse tree.
> 
> This is to make sure there are no regressions when someone changes the grammar later on. And, while the serialized tree produced by ["toStringTree()"](https://github.com/antlr/antlr4/blob/67228355c5bfd1ed5ebb89e726992ec43dda7b53/runtime/Java/src/org/antlr/v4/runtime/tree/Trees.java#L48) doesn't output the token type of tokens, at least it will be better than having no tree to fallback on.
> 
> Thanks!


Thanks for your guidance. I am new here. I have followed the steps to generate the .tree file, but don't know how to "add the .tree file produced by using the Trash toolkit.". Can you describe it a little more specifically? Or any guide I can follow will be appreciated. Thank you.
image

**Comment by be-happy4** [comment]
Another question is, the modification of rule `iconst` may cause user code broken. If there was a such java code:

```java
ParserRuleContext root = parser.iconst();
int v = Integer.parseInt(root.getText());
```
They may got a mistake, if there are hex or binary literals. They must distinguish `HexadecimalIntegral` and `BinaryIntegral` rule, and use different radix respectively.

**Comment by kaby76** [comment]
> Another question is, the modification of rule `iconst` may cause user code broken. If there was a such java code:
> 
> ```java
> ParserRuleContext root = parser.iconst();
> int v = Integer.parseInt(root.getText());
> ```
> 
> They may got a mistake, if there are hex or binary literals. They must distinguish `HexadecimalIntegral` and `BinaryIntegral` rule, and use different radix respectively.


An `iconst` comes directly out of the Flex and Bison grammars for the PostgreSQL server. That code creates a "unified token" to represent all the possible radix for the literal. That code is here: https://github.com/postgres/postgres/blob/9be4e5d293b554d8a0800790c57fc707a3b5cf0f/src/backend/parser/scan.l#L1371-L1390.

In converting the Flex/Bison grammars to Antlr, some liberty of how to do the lexing was taken. So, instead of a token "Iconst" is a parser rule, with separate token types for each radix. That's fine. Or you could change the Antlr grammar to reflect the Flex/Bison grammars more closely.

But, people who use this Antlr grammar need to write robust code. They are responsible not make poor assumptions. They should have checked the underlying tree for `iconst`.

**Comment by kaby76** [comment]
Looking great. Just add this file [numbers.sql.tree.txt](https://github.com/user-attachments/files/18118978/numbers.sql.tree.txt) to examples/ renamed as just numbers.sql.tree.

**Comment by be-happy4** [comment]
Sorry for the late reply, I found there are some obscure things to learn and the contribution tutorial here doesn't seem to be clear.
I believe things are progressing and the code could be accept. There are indeed some difficult things that cannot be done easily, such as numeric literals containing underscores, which python can parse but java cannot.
Anyway, thank you for your review and guidance, and I appreciate it again.

**Comment by teverett** [comment]
@be-happy4  thanks!

**Pull request merged**
