### PR TITLE
added handling for binary digits

### PR DESCRIPTION
**Pull request by timeraider4u**
binary literals now supported, see also https://gcc.gnu.org/onlinedocs/gcc/Binary-constants.html

### CODE REVIEW

**Comment by teverett** [comment]
The example BinaryDigits.c is not a valid C program.  Try this

<pre>
main()
{
  +int i = 0b0011;
   +int j = 0B1010;
   printf("Hello World");
}
</pre>

**Comment by parrt** [comment]
I thought C99 allowed init of globals?

**Comment by teverett** [comment]
I'm not an expert on C99..  However the version of the grammar which is on master doesn't parse the BinaryDigits.c either:

<pre>
Compiling grammar files...
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.modules.PatchedPublicProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.ServiceProviderProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NamedServiceProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NbBundleProcessor' less than -source '1.7'
4 warnings
Arguments: [C, primaryExpression, -tokens, -tree, -gui, /Users/teverett/Desktop/x.c]
[@0,0:0='+',<71>,1:0]
[@1,1:3='int',<32>,1:1]
[@2,5:5='i',<105>,1:5]
[@3,7:7='=',<89>,1:7]
[@4,9:9='0',<106>,1:9]
[@5,10:14='b0011',<105>,1:10]
[@6,15:15=';',<87>,1:15]
[@7,17:17='+',<71>,2:0]
[@8,18:20='int',<32>,2:1]
[@9,22:22='j',<105>,2:5]
[@10,24:24='=',<89>,2:7]
[@11,26:26='0',<106>,2:9]
[@12,27:31='B1010',<105>,2:10]
[@13,32:32=';',<87>,2:15]
[@14,34:33='<EOF>',<-1>,3:0]
line 1:0 no viable alternative at input '+'
(primaryExpression + int i = 0 b0011 ; + int j = 0 B1010 ;)
</pre>

**Comment by parrt** [comment]
i'll wait for @timeraider4u  to comment.

**Comment by timeraider4u** [comment]
@parrt  and @teverett : 
for me it is possible to parse the file BinaryDigit.c locally with both version (the one upstream and the suggested improved version). The only difference for me (locally) is how this file gets parsed. With the version upstream I get the following warning: "line 1:9 extraneous input 'b0011' expecting" which is then handled correctly by the modification made. I am using the following commands to test it locally:
CP="../../libs/antlr-4.5.1-complete.jar:."
java -cp ${CP} org.antlr.v4.Tool C.g4 && \
javac -cp ${CP} *.java && \
cat ./examples/BinaryDigit.c | java -cp ${CP} org.antlr.v4.runtime.misc.TestRig C compilationUnit -gui
So I do not know what exactly caused the test to fail (at the moment)

**Comment by teverett** [comment]
@timeraider4u, the bug here is mine.  It's in the pom.xml.  I have specified the grammar entry point as primaryExpression when it should have been compilationUnit.  Would it be possible to change pom.xml from this:

```
<configuration>
					<verbose>false</verbose>
					<showTree>false</showTree>
					<entryPoint>primaryExpression</entryPoint>
					<grammarName>C</grammarName>
					<packageName></packageName>
					<exampleFiles>examples/</exampleFiles>
				</configuration>
```

to this:

```
<configuration>
					<verbose>false</verbose>
					<showTree>false</showTree>
					<entryPoint>compilationUnit</entryPoint>
					<grammarName>C</grammarName>
					<packageName></packageName>
					<exampleFiles>examples/</exampleFiles>
				</configuration>
```

and update your pull request?

**Comment by timeraider4u** [comment]
@teverett: Thank you for this information. I have now tested the proposed change locally by executing mvn test and it now works like a charm ;-).

**Comment by teverett** [comment]
The automated tests pass now.  Thanks for the help with the fix @timeraider4u .

**Comment by timeraider4u** [comment]
Thank your time and thanks merging!

**Pull request merged**
