### PR TITLE
Hypertalk

### PR DESCRIPTION
**Pull request by defano**
Initial draft of HyperTalk grammar, README and tests.

### CODE REVIEW

**Comment by defano** [comment]
A couple mysql and plsql lexer files appear to have been spuriously picked up by a merge. Seems wrong to me...? Happy to remove them if you like. Please advise.

**Comment by teverett** [comment]
@defano  thanks for the commit.  Did you mean to commit

mysql/MySqlLexer.tokens
plsql/PlSqlLexer.tokens
tsql/TSqlLexer.tokens

?

**Comment by teverett** [comment]
@defano yes, pls remove. and thanks.

**Comment by teverett** [comment]
@defano thanks

**Pull request merged**
