### PR TITLE
plsql: pragma autonomous_transaction was not recognized as pragma

### PR DESCRIPTION
**Pull request by bedorlan**
No error fixed. The pragmas were not recognized correctly.

### CODE REVIEW

**Comment by KvanTTT** [comment]
Can you add PL/SQL code sample with incorrectly recognized pragmas?

**Comment by bedorlan** [comment]
before & after
before
after

**Comment by KvanTTT** [comment]
@madams51703 are you agree with these changes?

**Comment by madams51703** [comment]
Yes, that change looks good.

On Dec 12, 2017 05:39, "Ivan Kochurkin" <notifications@github.com> wrote:

@madams51703 <https://github.com/madams51703> are you agree with these
changes?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/antlr/grammars-v4/pull/1011#issuecomment-351013091>,
or mute
the thread

**Pull request merged**
