### PR TITLE
Add drop column support for SQLite

### PR DESCRIPTION
**Pull request by PadraigK**
Recent versions of SQLite support this feature
https://www.sqlite.org/lang_altertable.html#alter_table_drop_column

### CODE REVIEW

**Comment by KvanTTT** [comment]
Could you please add a test example to the `examples` subdirectory?

**Comment by PadraigK** [comment]
@KvanTTT Done!

**Comment by KvanTTT** [comment]
Thank you for the contribution and welcome to the ANTLR grammars repository!

**Comment by PadraigK** [comment]
Thanks!

**Pull request merged**
