### PR TITLE
informix-sql: add support of set dataskip stmt.

### PR DESCRIPTION
**Pull request by hellozrh**

### CODE REVIEW

**Comment by hellozrh** [comment]
The CI checks was successful in my local test in ANTLR Preview tool, why it's failed on website CI?
image

**Comment by kaby76** [comment]
> The CI checks was successful in my local test in ANTLR Preview tool, why it's failed on website CI? @KvanTTT Please help me, thank you. image

It's not failing your change, which is to informix-sql, but for plsql. First, it's testing plsql because your branch on your cloned repo is "dev14". That needs to be updated to the latest because the test scripts check the diff from the tip of "master", not the point of where you created the branch. That's a minor bug which I will fix. https://github.com/antlr/grammars-v4/issues/3651

Why it's failing plsql is another issue.

For now, just "fast-forward" your branch. It'll then test only informix-sql, and then pass.

**Comment by kaby76** [comment]
@hellozrh 

OK, I made an error. I assumed that you didn't change plsql because you supposedly are only working on informix-sql. But, I was wrong.

Why are you changing the SQL tests with [this commit](https://github.com/hellozrh/grammars-v4/commit/7cb81f001fd5131ec7df272c222fced6e1e11aef). Aren't you only changing informix-sql???

**Comment by hellozrh** [comment]
> @hellozrh
> 
> OK, I made an error. I assumed that you didn't change plsql because you supposedly are only working on informix-sql. But, I was wrong.
> 
> Why are you changing the plsql/ tests with [this commit](https://github.com/hellozrh/grammars-v4/commit/7cb81f001fd5131ec7df272c222fced6e1e11aef) which is part of this PR? Aren't you only changing informix-sql??

I see, my mistake, I fix it now. Thanks.

**Comment by teverett** [comment]
@hellozrh  thanks!

**Pull request merged**
