### PR TITLE
fix golang interpreted string literals

### PR DESCRIPTION
**Pull request by uunnii**

### CODE REVIEW

**Comment by KvanTTT** [comment]
Could you also provide an example that covers the change?

**Comment by uunnii** [comment]
> Could you also provide an example that covers the change?

Yes, I added an example in new commits.

**Comment by KvanTTT** [comment]
Unfortunately, tests are failing: https://github.com/antlr/grammars-v4/runs/4125916381?check_suite_focus=true#step:4:4431 Could take a look?

**Comment by uunnii** [comment]
> Unfortunately, tests are failing: https://github.com/antlr/grammars-v4/runs/4125916381?check_suite_focus=true#step:4:4431 Could take a look?

Yes. The logs show that the error message for this test case is different on windows and other platforms, and I added a new commit to fix it.

**Comment by teverett** [comment]
@uunnii I see a merge conflict on this PR and some test failures.  Are you planning to continue the PR?

**Comment by teverett** [comment]
@uunnii   I am closing this for now.  You are welcome to re-open it with merge fixes.

**Pull request closed without merging**
