### PR TITLE
COOL: Declaring fragment lexical rules

### PR DESCRIPTION
**Pull request by linonetwo**
Make case-insensitive rules clear.

### CODE REVIEW

**Comment by linonetwo** [comment]
This CI takes too long a time to build...

**Comment by KvanTTT** [comment]
@linonetwo you can comment out all languages except COOL and then test it locally with maven plugin.
@teverett can we leave only one oraclejdk7 and remove other oraclejdk8, openjdk7 JDKs from .travis configuration? What aspects do they check?

**Comment by linonetwo** [comment]
Hold this for a while, I'm building a code transformer, and find some bug in this grammar.  :P

**Comment by teverett** [comment]
@linonetwo- holding

@KvanTTT hm.  Well the advantage is that there have been instances in the past where a grammar worked on on JDK and not another.  I'm not sure what the justification to remove checking across JDK's would be.  It is a very long build, but actually the 3x JDK builds run in parallel.

**Comment by linonetwo** [comment]
OK, I've finished it!

**Comment by teverett** [comment]
@linonetwo  thanks and congrats

**Pull request merged**
