### PR TITLE
Support for rename index

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by teverett** [comment]
@jpechane  could you close this PR, pull from TRUNK and resubmit pls?

**Comment by jpechane** [comment]
@teverett I've force-pushed to retrigger the build and it started this time.

**Comment by teverett** [comment]
@jpechane thanks

@KvanTTT pls pull

**Comment by KvanTTT** [comment]
Why should I do it? This is not my pull request.

**Comment by KvanTTT** [comment]
You meant `to accept pull request`? :)

**Comment by teverett** [comment]
yup :)

All good?

**Comment by KvanTTT** [comment]
Yes. Sorry, I misunderstood you the first time.

**Comment by teverett** [comment]
*shrug*.  All good.  We got down to zero open PRs! :)

**Pull request merged**
