### PR TITLE
Swift3

### PR DESCRIPTION
**Pull request by artyom-razinov**
Swift 3 was released in September 2016, and it came up with a very different syntax.

iOS developers spent weeks on updating their projects to Swift 3. It is like a new language, so I've separated Swift2 and Swift3 grammars (also I noticed that Swift2 grammar have some issues that I fixed in Swift3 grammar).

Swift 2 will die soon, so I think the community will not ask to improve its grammar in ANTLR.

I've added good tests and because of the tests I've implemented multiple undocumented things in grammar.

I'm about to make a code generation tool for Swift so I want to contribute to the grammar later.

### CODE REVIEW

**Comment by teverett** [comment]
I'm happy to pull this, post-Antlr 4.7

**Comment by KvanTTT** [comment]
What is the meaning of **.tiff** files in Swift grammar? Can we replace them with **.png** at least? Also .rtf file should be replaced with Markdown (**.md**) as I guess.

**Comment by artyom-razinov** [comment]
I didn't change Swift2 grammar files, I dunno what to do with them.

**Comment by KvanTTT** [comment]
Ok, I created an issue for that: https://github.com/antlr/grammars-v4/issues/574

**Comment by artyom-razinov** [comment]
I also want to ask a question. I added lots of swift files to `examples/` folder, which is referenced in maven test artifact, and this slowed down testing time too much (it exceeded 10 mins on travis). I understand that tests shouldn't last so much for every pull request, so I deleted them (swift stdlib's files).

But I want to keep the files (or something) for manual testing, if someone want to work on swift3 grammar and test if he break something. Are there any examples of how to do it in this repo or I can "feel free"?

**Comment by teverett** [comment]
The intent of the /examples directory is to make absolutely sure that every grammar works with the current Antlr4 build.  So, if it takes 10 min more to test that, I feel like that's an acceptable cost.  I prefer that you just leave your test cases in /examples.

**Pull request merged**
