### PR TITLE
upgrate  Antlr to 4.13.0

### PR DESCRIPTION
**Pull request by hellozrh**
I found that the version number of antlr in some places is not upgrated, so I fix it to 4.13.0

### CODE REVIEW

**Comment by kaby76** [comment]
We are not ready for this. Not all the targets have 4.13.0 releases.

Also, you didn't change all the targets correctly. There are two parts to an upgrade to a major release: the numbers for the tool; the numbers for each of the targets. Your commit only has half of the target libraries being updated. Nothing will work.

**Comment by kaby76** [comment]
@hellozrh Please fix these lines:

* For the tool:

https://github.com/antlr/grammars-v4/blob/4d7389ea494054dd952cfc6cd946b61e16de1679/.github/workflows/main.yml#L84

https://github.com/antlr/grammars-v4/blob/4d7389ea494054dd952cfc6cd946b61e16de1679/.github/workflows/main.yml#L190

**Comment by hellozrh** [comment]
> @hellozrh Please fix these lines:
> 
> * For the tool:
> 
> https://github.com/antlr/grammars-v4/blob/4d7389ea494054dd952cfc6cd946b61e16de1679/.github/workflows/main.yml#L84
> 
> https://github.com/antlr/grammars-v4/blob/4d7389ea494054dd952cfc6cd946b61e16de1679/.github/workflows/main.yml#L190

It's done.

**Comment by hellozrh** [comment]
OK, let's solve this problem bit by bit.  I have submitted according to the method you suggested. But when I visit the url 'https://github.com/antlr4-go/antlr/v4', the browser responsed 'Page not found.'. What I want to say is, are you sure the URL is correct and can you access it

**Comment by kaby76** [comment]
> OK, let's solve this problem bit by bit. I have submitted according to the method you suggested. But when I visit the url 'https://github.com/antlr4-go/antlr/v4', the browser responsed 'Page not found.'. What I want to say is, are you sure the URL is correct and can you access it

The instructions for building a Go parser are here. https://github.com/antlr/antlr4/blob/master/doc/go-target.md#changes-from-antlr-4120 `go get github.com/antlr4-go/antlr`.

**Comment by teverett** [comment]
@kaby76  @hellozrh  thanks!

**Pull request merged**
