### PR TITLE
fix attrs define

### PR DESCRIPTION
**Pull request by Willam2004**

### CODE REVIEW

**Comment by KvanTTT** [comment]
Could you also please add a sample to the `examples` directory?

**Comment by Willam2004** [comment]
> Could you also please add a sample to the `examples` directory?

i modify the `examples/comment_on.sql` for add one statement for my commit.

**Comment by KvanTTT** [comment]
`postresql` and `plsql` are different grammars. Please add/change sample in `postgresql` directory.

**Comment by Willam2004** [comment]
> `postgresql` and `plsql` are different grammars. Please add/change sample in `postgresql` directory.

OK，I change `sql/postgresql/examples/alter_table.sql` and add test case.

**Comment by KvanTTT** [comment]
Thank you for the contribution and welcome to ANTLR grammars repository!

**Pull request merged**
