### PR TITLE
Support numeric values without mantissas

### PR DESCRIPTION
**Pull request by Naros**
Upstream PR related to https://github.com/debezium/debezium/pull/5388

### CODE REVIEW

**Comment by teverett** [comment]
@Naros thanks!

**Comment by KvanTTT** [comment]
@teverett we don't have `debezium` language, it's a part of PL/SQL.

**Comment by Naros** [comment]
Thanks all, sorry for the confusion with the link back to the downstream Debezium project.

**Comment by KvanTTT** [comment]
No need to sorry here, for me everything is clear.

**Comment by teverett** [comment]
> @teverett we don't have `debezium` language, it's a part of PL/SQL.

oops

**Comment by teverett** [comment]
> No need to sorry here, for me everything is clear.

You'll merge this when you're ready @KvanTTT ?

**Comment by KvanTTT** [comment]
> You'll merge this when you're ready @KvanTTT ?

You've already merged it and I've fixed labels. I warned about labels for the future.

**Pull request merged**
