### PR TITLE
 added support for preprocessor line directives with multiple lines 

### PR DESCRIPTION
**Pull request by timeraider4u**
added support for preprocessor line directives with multiple lines, see https://gcc.gnu.org/onlinedocs/gcc-2.95.3/cpp_1.html#SEC2

added a test case for preprocessor directives

### CODE REVIEW

**Comment by parrt** [comment]
The preprocessor commands are so complex that typically the preprocessor is run before sending the input to the actual compiler. On the other hand, doesn't seem to hurt anything to include those. Users of this grammar should note that the preprocessor allows non-C code. Imagine:

```C
#define FOO int i;
FOO
```

`FOO` is not valid C code.

Hmm... I'm wondering if this really belongs here or in a separate grammar call CPreproc.g4?

**Comment by timeraider4u** [comment]
I totally agree with you that it would be better to run this ANTLR grammar on an intermediate file instead of parsing C files which include (probably nasty) preprocessor directives. On the other hand, a user might want to deal with them independently after parsing the C file, e.g. show me all expressions where an identifier, which has been defined in a preprocessor statement with the name "foo", is used.

**Comment by parrt** [comment]
Hmm...in general preproc and C parsing have to be done separately and then info shared between them. How about creating separate cpreproc grammar?

**Comment by timeraider4u** [comment]
Yes, I think you are right. Okay, I will give it a try, but I can not guarantee for anything ;-).

**Comment by parrt** [comment]
ok, great! thanks for all your help!

**Pull request closed without merging**
