### PR TITLE
Fix for #2136

### PR DESCRIPTION
**Pull request by kaby76**
* Fix compilation errors in golang/ for Go target.
* Fix indentation of all source code in golang/.
* Fix golang/ sources for target-specific base classes so they are similar.
* Use trgen, which is basically "dotnet-antlr" renamed, and moved over from [Antlr4BuildTasks](https://github.com/kaby76/Antlr4BuildTasks) to [Trash](https://github.com/kaby76/Domemtech.Trash). The newest version of the tool is required to test golang/ because go_parser_base.go must be copied into parser/.
* Fix trgen templates to allow spaces in test file names.
* Fix trgen Go target template makefile so that GO111MODULE=auto is set. Otherwise, you get a strange Go compiler error.
* Coordinate regtest.sh and test.ps1 so that they have the same lists of tests.
* Update _scripts/readme.md for with new trgen information.

### CODE REVIEW

**Comment by kaby76** [comment]
* Updated regtest.sh and test.ps1 to use the same lists, which are now refactored from the two CI scripts and placed in "skip-....txt" files, one per target.

**Comment by kaby76** [comment]
This PR is now ready for review.

@Marti2203 The golang/ grammar has been updated for Go, along with a small number of minor changes for the other sources in golang/.

@studentmain I modified the _script/test.ps1 file to share the same lists of grammars to skip. These are now in _scripts/*.txt so not to hardwire them into the test.ps1 and regtest.sh, and to have common lists.

I'm going to add folks into my PRs more often now. This is because I want backup on these changes. For a recent change to fortran77/, I'm not sure if someone was complaining that symbols were renamed in the grammar--which was done to make the grammar target-independent--or whether the person was looking for permission from me to make a change to it. In any case, changes should have broader support. The next large change I will likely make will be a rename of all the remaining grammar symbol conflicts using a 10-line script using [trrename](https://github.com/kaby76/Domemtech.Trash/tree/main/trrename). I will likely add a script for people to rename symbols back(wards) to the old conflicting values if people don't want to fix their visitor/listener/tree walking code.

--Ken

**Review by Marti2203 — APPROVED** [review]
I really like the changes and it is good to finally see which languages can be tested. I think that it would be very useful to have a document that explains this, especially for newcomers who want to add more things and people like me, who never knew about this.

**Comment by kaby76** [comment]
@Marti2203 I will try to create a document to describe how to use trgen and the scripts.

I have a script I'm crafting that does a rename of the target-specific keywords to a name ending in '_' or back. But, I am surprised the list of reserved words is very large: ~100 lines, many with multiple symbols per line (see https://github.com/antlr/antlr4/tree/master/tool/src/org/antlr/v4/codegen/target). It's clear this has to be done methodically from the sources, rather than an ad-hoc, experimental trial-and-error on the grammars in this repository as it has been up to this point (https://github.com/antlr/grammars-v4/issues?q=label%3Asymbol-conflict). The script should be able to do that likely 15 minutes or so. I am planning to add a check for all possible conflicts, and insert that into the CI builds at some point.

**Comment by teverett** [comment]
Is this ready?

**Comment by kaby76** [comment]
It's okay to merge. There's always more work to do, of course. -K

**Review by studentmain — APPROVED** [review]

**Pull request merged**
