### PR TITLE
Added TOML Grammar

### PR DESCRIPTION
**Pull request by benkonz**
I created a TOML ANTLR parser for a an IDE plugin and figured it might be useful to add it to this repo

### CODE REVIEW

**Comment by teverett** [comment]
@benkonz  closed?

**Comment by benkonz** [comment]
Yeah, sorry. I ran some of my tests on the grammar and noticed a few inconsistencies that I don't remember being there. I'll re-open once I fix them.

**Comment by benkonz** [comment]
Ok, it looks like the build is fixed. The code should be ready for review now.

**Comment by teverett** [comment]
@benkonz thanks!

**Pull request merged**
