### PR TITLE
Remove functionDeclaration from anonymousFunction rule (antlr#3387)

### PR DESCRIPTION
**Pull request by ris58h**
Fixes https://github.com/antlr/grammars-v4/issues/3387

### CODE REVIEW

**Comment by kaby76** [comment]
Looks like the build will fail on this because there's a bug in the build code generator. I will have a PR shortly, and will let you know when you can sync with master.

**Comment by ris58h** [comment]
@kaby76 should I do anything to fix the issue?

**Comment by kaby76** [comment]
> @kaby76 should I do something to fix the issue?

I think all that needs to be done is to redo the build. Should work. If not, just fast forward this branch with changes from master. @KvanTTT or @teverett ?

**Comment by ris58h** [comment]
I've rebased on the current master.

**Comment by ris58h** [comment]
> 1 workflow awaiting approval 

@kaby76 could you do approve it?

**Comment by kaby76** [comment]
> @kaby76 could you do approve it?

I'm not an administrator. @teverett or @KvanTTT, please run the workflow for this PR. Ty!

**Comment by ris58h** [comment]
@kaby76 sorry for bothering you but if everything is OK could we merge the PR?

**Comment by kaby76** [comment]
> @kaby76 sorry for bothering you but if everything is OK could we merge the PR?

Sorry, I'm not an admin of this repo. I'm waiting for https://github.com/antlr/grammars-v4/pull/3469 myself.

**Comment by teverett** [comment]
@ris58h  thanks!

**Pull request merged**
