### PR TITLE
informix-sql: add support of database stmt/close stmt/close database stmt/commit grammars.

### PR DESCRIPTION
**Pull request by hellozrh**
informix-sql: add support of database stmt/close stmt/close database stmt/commit grammars.

### CODE REVIEW

**Comment by hellozrh** [comment]
My local maven test run successful, why some of the CI checks were failed?

```java
D:\Java\openlogic-openjdk-11.0.18+10-windows-x64\bin\java.exe -Dmaven.multiModuleProjectDirectory=D:\project\grammars-v4\sql\informix-sql -Dmaven.home=D:\java\apache-maven-3.6.3 -Dclassworlds.conf=D:\java\apache-maven-3.6.3\bin\m2.conf -Dmaven.ext.class.path=D:\java\idea2021\plugins\maven\lib\maven-event-listener.jar -javaagent:D:\java\idea2021\lib\idea_rt.jar=9345:D:\java\idea2021\bin -Dfile.encoding=UTF-8 -classpath D:\java\apache-maven-3.6.3\boot\plexus-classworlds-2.6.0.jar;D:\java\apache-maven-3.6.3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3 -s D:\java\apache-maven-3.6.3\conf\settings.xml -Dmaven.repo.local=D:\repo36 test
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.antlr.grammars:informix-sql >-------------------
[INFO] Building Informix SQL grammar 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- antlr4-maven-plugin:4.12.0:antlr4 (default) @ informix-sql ---
[INFO] No grammars to process
[INFO] ANTLR 4: Processing source directory D:\project\grammars-v4\sql\informix-sql
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ informix-sql ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\project\grammars-v4\sql\informix-sql\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ informix-sql ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ informix-sql ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\project\grammars-v4\sql\informix-sql\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:testCompile (default-testCompile) @ informix-sql ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ informix-sql ---
[INFO] No tests to run.
[INFO] 
[INFO] --- antlr4test-maven-plugin:1.22:test (default) @ informix-sql ---
[INFO] Evaluating Scenario: Default Scenario
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\close_stmt.sql
ANTLR Tool version 4.12.0 used for code generation does not match the current runtime version 4.11.1
ANTLR Runtime version 4.12.0 used for parser compilation does not match the current runtime version 4.11.1
ANTLR Tool version 4.12.0 used for code generation does not match the current runtime version 4.11.1
ANTLR Runtime version 4.12.0 used for parser compilation does not match the current runtime version 4.11.1
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\commit.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\create_role.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_access_method.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_aggregate.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_database.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_role.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_table.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_type.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_user.sql
[INFO] Parsing :D:\project\grammars-v4\sql\informix-sql\examples\drop_view.sql
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.096 s
[INFO] Finished at: 2023-05-22T15:09:20+08:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0

```

**Comment by kaby76** [comment]
> My local maven test run successful, why some of the CI checks were failed?

The build does not test using Maven, because it does not support testing for multiple targets. But, this isn't the problem.

The problem is that we now appear to be in the middle of an Antlr release, which typically takes a few weeks to get all the targets published. PHP usually doesn't get published until I ask because it is in a separate repo.

The Go build is not going to work because the old libraries are not back-supported via ["go get github.com/antlr/antlr4/runtime/Go/antlr/v4"](https://github.com/antlr/grammars-v4/blob/45516915017cc29cafb351264a8d52f858053548/_scripts/templates/Go/build.sh#L3). @parrt @jimidle 

The only solution, for now, is to remove testing of the Go target. When 4.13.0 is announced, and all the runtimes are published, I can add it back in.

**Comment by kaby76** [comment]
https://github.com/antlr/grammars-v4/issues/3460 https://github.com/antlr/grammars-v4/pull/3461

**Comment by hellozrh** [comment]
> 
@kaby76 Thank you very much for your patient explanation.  I will follow the updates for the new version 。

**Comment by jimidle** [comment]
4.13.0 is now released, but you need to be using the 4.13.0 tool jar as well - they go hand in hand.

If you are using the dev branch, then you need to be using the dev version of the tool of course. There are no guarantees that code generated by the tool at one release will be compatible with the runtime at a another release, and we do not follow classic semver with ANTLR4, otherwise I would have made the Go runtime be v5.

This hiccup should be worth it, although some of the published grammars are quite poorly formed and could do with some work to make them perform better.

The next go release will concentrate on memory and tree walking. The memory 'tricks' should help the poorly formed grammars.

**Comment by kaby76** [comment]
Unfortunately, not all is released.
* PHP - no 4.13.0 https://packagist.org/packages/antlr/antlr4-php-runtime (latest 0.9.0).
* Dart - no 4.13.0 https://pub.dev/packages/antlr4 (latest 4.12.0).
I can't upgrade yet because all targets are testing with the same version of Antlr. (I haven't programmed the scripts to test different versions of Antlr.)

Yes, there are a lot of bad grammars in the grammars-v4 repo, but I would like to add checks in the build to push things in the "right" direction whenever someone changes a grammar: flagging unused rules, useless parentheses, naming conventions, changes that don't include parse input that test the changes (in parser rules), etc. But, in a way, these grammars sometimes trip up Antlr, pointing to some interesting bugs.

**Comment by jimidle** [comment]
I see. However, have the Dart and PHP rutimes changed at all in 4.13.0? If
there are no codegen changes, then the tool can be upgraded anyway I
would think? PHP release number look especially strange.

Anyway, let me know if I can help.

"But, in a way, these grammars sometimes trip up Antlr, pointing to some
interesting bugs."

In fact I keep some around for this reason.

I think I might have a go at fixing the MySql grammar myself as I
should think that that might be a popular one and I don't see how it is
usable for anything as it stands.

**Comment by kaby76** [comment]
> I think I might have a go at fixing the MySql grammar myself as I should think that that might be a popular one and I don't see how it is usable for anything as it stands.

Yes, that MySQL grammar is pretty .... interesting. I think there's an "official" Antlr grammar in the Oracle Workbench.

**Comment by jimidle** [comment]
Neither the Dart nor PHP code gen templates have changed for a long time.

The Dart runtime last changed only when we bumped release to 4.12.0, when
the runtime_meta_data.daart and pubspec.yaml files change just to
increment the reported release number. I don't know who the maintainer(s)
are for Dart, but I could put that change in if we cannot get the
maintainers to do it.

**Comment by jimidle** [comment]
If there is already a better one somewhere, then I won't do any work on
that one. It will take a fair bit of work. However, I was going to pick one
and make an article about writing good grammars, with that grammar as an
example of what can be done.

**Comment by hellozrh** [comment]
I have merged branch master into my branch dev, upgrate antlr's verstion to 4.13.0, my local tests also run successfully.  Now all the test in Python3 were failing. Doesn't  Python3 support antlr 4.13.0 ?

**Comment by kaby76** [comment]
> I have merged branch master into my branch dev, upgrate antlr's verstion to 4.13.0, my local tests also run successfully. Now all the test in Python3 were failing. Doesn't Python3 support antlr 4.13.0 ?


Right. We're not ready for the upgrade to 4.13.0 because not all the targets are "out". But, it's already started in bits and pieces, which is why Python3 fails.

The GitHub "dependabot" offers updates to Antlr 4.13.0, but these updates should be ignored because there are two sides to an upgrade of Antlr. Github does not understand this. https://github.com/antlr/grammars-v4/pull/3465
https://github.com/antlr/grammars-v4/pull/3464 https://github.com/antlr/grammars-v4/pull/3462. It has to be done manually because the Gitub dependabots PRs don't upgrade all versions together. It only changes the target templates, not the tool.

@teverett Please merge in https://github.com/antlr/grammars-v4/pull/3467 after that PR is fixed after I review all the changes there.

**Comment by hellozrh** [comment]
> > I have merged branch master into my branch dev, upgrate antlr's verstion to 4.13.0, my local tests also run successfully. Now all the test in Python3 were failing. Doesn't Python3 support antlr 4.13.0 ?
> 
> Right. We're not ready for the upgrade to 4.13.0 because not all the targets are "out". But, it's already started in bits and pieces, which is why Python3 fails.
> 
> The GitHub "dependabot" offers updates to Antlr 4.13.0, but Github does not understand to update the tool version. #3465 #3464 #3462. After we fix the build, I'll change the build code so that each target works independently from each other, and the update by dependabot will select the version of the tool to use.
> 
> @teverett Please merge in #3467 after that PR is fixed after a few changes are made.

OK, the PR #3467 is fixed now.  thanks.

**Comment by hellozrh** [comment]
This PR's CI problem may be solved in #3454 .

**Review by KvanTTT — APPROVED** [review]

**Pull request merged**
