### PR TITLE
Changes for #2117.

### PR DESCRIPTION
**Pull request by kaby76**
These are changes for fixing symbol collisions for grammars that start with "b" or "c" (e.g., "bcpl") against the eight targets that dotnet-antlr test (Antlr4cs, CSharp, Java, JavaScript, Cpp, Dart, Go, Python3).

I won't be dealing with cross-target base class additions in this PR--yet. I am instead working on updating "Trash" (TRansformations for Antlr grammars Shell) as a Dotnet toolset at this point.

### CODE REVIEW

**Comment by kaby76** [comment]
* Arithmetic.g4 was being copied into Generated/--Fixed with dotnet-antlr v3.1.4.
* Clif has no examples, and failed on trying to run a test of the parser, whcih it can't. The grammar is out-of-date, and should have examples. See https://github.com/gruninger/colore/tree/master/ontologies/algebra and https://standards.iso.org/ittf/PubliclyAvailableStandards/c066249_ISO_IEC_24707_2018.zip

**Comment by teverett** [comment]
@kaby76  good to pull this?

**Comment by kaby76** [comment]
> @kaby76 good to pull this?

@teverett You bet. I took care of changing the symbol conflicts, but left the grammars that are for a specific taget alone. I or someone else will make these changes for these later. --Ken

**Comment by teverett** [comment]
@kaby76  thanks

**Pull request merged**
