### PR TITLE
Made a working LexerAdaptor

### PR DESCRIPTION
**Pull request by Marti2203**
Currently, Lexer Adaptor is the only obstacle that makes the antlr4 grammar unusable for a .Net project. The Grammar works for Java and now it works for .Net

### CODE REVIEW

**Comment by Marti2203** [comment]
The open issue is #1108

**Comment by Marti2203** [comment]
There is an issue. I forgot that the grammar has the method names with lowercase.

**Comment by teverett** [comment]
it seems that you found an issue?   Should I wait to pull this?

**Comment by Marti2203** [comment]
You can pull. I fixed it with the second commit.

**Comment by teverett** [comment]
@Marti2203 thanks

**Pull request merged**
