### PR TITLE
Generate grammars.json, but leave as artifact.

### PR DESCRIPTION
**Pull request by kaby76**
https://github.com/antlr/grammars-v4/issues/2919
https://github.com/antlr/antlr4-lab/issues/52

For now, process the grammars in the repo to create a simple list of objects that describe each grammar, but leave as an artifact. This will be a multi-step checkin for this and antlr4-lab repos.

### CODE REVIEW

**Comment by kaby76** [comment]
It seems to access the artifact, multiple accesses will be required:
* curl https://api.github.com/repos/kaby76/temp-with-actions/actions/artifacts => From the returned json output, find the latest build, then get the artifact ID, e.g., 434781932
* curl https://api.github.com/repos/kaby76/temp-with-actions/actions/artifacts/434781932 => get the link to the artifact from the returned json, 
* curl -H 'Accept: application/vnd.github+json' -H 'Authorization: token kaby76 OAUTH-TOKEN' -L https://api.github.com/kaby76/temp-with-actions/artifacts/434781932/zip => This step requires a Github userid and authorization token. The output is a zip file with the grammars.json file.

The rate-limiting step that is required here is that we must have an authorization token to access the grammars-v4 repo artifacts. I don't know how to create a public one.

**Comment by KvanTTT** [comment]
Thanks, I like idea of grammars.json as artifact much more than artificial commit.

**Comment by kaby76** [comment]
I don't have a way currently to create a public token for github.com that has simply read-only rights. It looks like the best way to move forward is to check in this code, then try to set up an authorized app.

**Comment by kaby76** [comment]
Fine-grain personal access tokens with read only access to repos are in beta in Github.com. But, yes, it does work! 

```
curl -H 'Accept: application/vnd.github+json' -H 'Authorization: token <fine-grain-PAT>' -L https://api.github.com/repos/kaby76/temp-with-actions/actions/artifacts/453691604/zip --output
foobar.zip
```

@teverett  Please merge. This will turn off the checkin, and just run the indexer leaving an artifact that we can then "curl" in lab.antlr.org clients.

**Comment by parrt** [comment]
So people are complaining that we are generating grammars.json in every dir of grammars-v4 or just in their forks?  Can they ignore an extra file?

**Pull request merged**
