### PR TITLE
fix: Add compact constructor rule to Java.

### PR DESCRIPTION
**Pull request by raghav-deepsource**
The latest java grammar doesn't yet support compact constructor definitions, so I added that as per the records JEP grammar.

This does not check for duplicated compact constructors, but hopefully, that isn't a priority with this grammar.

I also fixed an inconsistency in the statement production (an empty statement isn't a type declaration!)

### CODE REVIEW

**Comment by raghav-deepsource** [comment]
@kaby76 would you be able to enable CI for this PR?

**Comment by kaby76** [comment]
> @kaby76 would you be able to enable CI for this PR?

Sorry, I don't have the privileges. @teverett or @KvanTTT will be around to this shortly.  In the meanwhile, [this change](https://github.com/antlr/grammars-v4/pull/2987/files#diff-5f86a5fa6423f197802bb427efb809f84b296343e47307c73e0c24c16f8d1648R182) seems different from [the Spec](https://docs.oracle.com/javase/specs/jls/se19/html/jls-8.html#jls-CompactConstructorDeclaration). Are constructor modifiers recognized?

**Comment by raghav-deepsource** [comment]
Oops, missed that.

**Comment by KvanTTT** [comment]
So, I started CI build.

**Comment by raghav-deepsource** [comment]
ugh, is this because of a newline?

**Comment by raghav-deepsource** [comment]
I see why workflows need approval now; sorry about those hours of CI time wasted.

**Comment by teverett** [comment]
@raghav-deepsource thanks for this.  @kaby76  @KvanTTT  good to merge this?

**Comment by kaby76** [comment]
> @raghav-deepsource thanks for this. @kaby76 @KvanTTT good to merge this?

I'm testing this against the OpenJDK....

**Comment by kaby76** [comment]
This looks good. Before the change 27 out of 13825 failed--which is pretty good. With the PR, 24 out of 13825 failed.

**Comment by teverett** [comment]
@raghav-deepsource thanks!

**Pull request merged**
