### PR TITLE
change the antlr import address for go target.

### PR DESCRIPTION
**Pull request by hellozrh**
change the antlr import address for go target.

see as https://github.com/antlr/antlr4/blob/master/doc/go-changes.md

### CODE REVIEW

**Comment by kaby76** [comment]
https://github.com/antlr/grammars-v4/issues/3460 https://github.com/antlr/grammars-v4/pull/3461

**Comment by hellozrh** [comment]
My original target is to update the module name of ptx in the pom, because when I opened this repo in my IntelliJ IDEA, the idea tip the module name not found in "asm/ptx/pom.xml" , line 16:
image
And I find the module's directory named "ptx-isa-2.1",  so I changed the module name to "ptx-isa-2.1"。But the CI checks were not successful. The error messages show that something wrong with the go target.  After I changed the antlr import address for go target, the CI test still reported some errors with go target. I really don't know what to do now, so I restored the module name, and the CI test have passed.  
So I changed this PR's title, this PR only submit antlr import address.  And the question of module name, I push it in a new PR     #3471 .

**Comment by kaby76** [comment]
Sorry, I realized only after implementing https://github.com/antlr/grammars-v4/pull/3469 that the Go-target templates were not completely fixed (Test.go) by https://github.com/antlr/grammars-v4/pull/3467. I have the same fix to Test.go in my PR as this PR, but this PR should still be merged as it fixes some issues with the plsql grammar code. There will be a merge conflict when this and my PR are merged into master--hopefully sooner than later, and the build is still not completely fixed. @teverett

**Comment by hellozrh** [comment]
> Sorry, I realized only after implementing #3469 that the Go-target templates were not completely fixed (Test.go) by #3467. I have the same fix to Test.go in my PR as this PR, but this PR should still be merged as it fixes some issues with the plsql grammar code. There will be a merge conflict when this and my PR are merged into master--hopefully sooner than later, and the build is still not completely fixed. @teverett

I have merged the PR #3469 to this PR, and the CI checks passed now, @kaby76, @teverett .

**Comment by teverett** [comment]
@hellozrh  thanks!

**Pull request merged**
