### PR TITLE
TSql: Fix grammar for xml functions

### PR DESCRIPTION
**Pull request by pguyot**
XML functions are called on columns which may be specified with a table name.

### CODE REVIEW

**Comment by pguyot** [comment]
(will rebase once #2780 is merged)

**Comment by pguyot** [comment]
CI didn't pass. Should we revert it until test is fixed?

**Comment by KvanTTT** [comment]
Yes. Sorry, I thought the fail doesn't relate to your changes.

**Comment by pguyot** [comment]
This is bug #2768 : on Windows and on Linux, we have different trees. I will try to isolate a small case to debug that.

**Comment by pguyot** [comment]
Fix is in #2784

**Pull request merged**
