### PR TITLE
Changed "provence" to "provenance"

### PR DESCRIPTION
**Pull request by pfurbacher**
Edited on github (via browser). Corrected the typo. Not sure, but it looks like github's web-based editor may have changed the last line (whitespace?) when the single edit on line 5 was saved.

### CODE REVIEW

**Comment by kaby76** [comment]
This looks fine. The only other change I would recommend is for "commited"--it should be "committed". I'm not sure why it's not being merged. @teverett

**Comment by pfurbacher** [comment]
Is there something I'm supposed to do on my end? The change is committed in my fork.

**Comment by pfurbacher** [comment]
I just synced my fork -- maybe that's what was holding things up?

**Comment by kaby76** [comment]
> I just synced my fork -- maybe that's what was holding things up?

Likely. The previous build of this PR failed because of some changes to the TypeScript/Node.js environment. That caused the "library not loaded" problem. https://github.com/antlr/grammars-v4/actions/runs/8398752211/job/23060672270#step:24:57 . I fixed that problem with a change in PR https://github.com/antlr/grammars-v4/pull/4019

@teverett or @KvanTTT Please restart the workflow tests for this PR. Ty.

**Comment by teverett** [comment]
@pfurbacher  thanks!

**Pull request merged**
