### PR TITLE
fix #1492

### LINKED ISSUE #1492: Grammar PlSqlParser.g4 parsed uncorrect result
I found an error when parsed plsql sentences, for example

```sql
select sex, name, phone from student;
```

the selected_element of the ParseTree contains `sex, name, phone`. When I go details into PlSqlParser.g4, I found that

```antlr
query_block
    : SELECT (DISTINCT | UNIQUE | ALL)? (ASTERISK | (','? selected_element)+)
      into_clause? from_clause where_clause? hierarchical_query_clause? group_by_clause? model_clause?
    ;

selected_element
    : select_list_elements column_alias?
    ;

select_list_elements
    : tableview_name '.' ASTERISK
    | (regular_id '.')? expressions
    ;

expressions
    : expression (',' expression)*
    ;
```

the rule named `select_list_elements` has a branch `(regular_id '.')? expressions`, my problem is here. `expressions` separated by `COMMA` if `(',' expression)` exists, so all the selected_elements were parsed to a single `seleced_element`. I don't check other rules which contain `select_list_elements`, so I just rewrite `query_block` like this and solve my problem. By the way, `(','? selected_element)+)` can match pattern `sex name phone`, because we don't know when `COMMA` exists, but in `query_block` `select_element` must exist at least one,  `select_element (COMMA selected_element)*` may be more correct.

```antlr
query_block
    : SELECT (DISTINCT | UNIQUE | ALL)? selected_list                                                                                                 
      into_clause? from_clause where_clause? hierarchical_query_clause? group_by_clause? model_clause?
    ;
 
selected_list
    : ASTERISK
    | selected_list_element (COMMA selected_list_element)*
    ;
 
selected_list_element
    : tableview_name PERIOD ASTERISK
    | expression  column_alias?
    ;
```

### PR DESCRIPTION
**Pull request by small-cat**
replace characters with TOKENS definited in PlSqlLexer.g4 to fix implied definition warnings when build with -Xlog, fix #1492

### CODE REVIEW

**Comment by KvanTTT** [comment]
Have you tried the latest ANTLR 4.7.2 with fix https://github.com/antlr/antlr4/pull/2358?

**Comment by teverett** [comment]
@KvanTTT are we holding this PR until the above question is answered?

**Comment by KvanTTT** [comment]
Actually not blocking, but it would be useful to know.

**Comment by teverett** [comment]
Lets wait on an answer

**Comment by KvanTTT** [comment]
I'm closing this PR because there are a lot of style changes. Moreover, it contains merge conflicts and the original issue already has been fixed by #1600.

**Pull request closed without merging**
