### PR TITLE
[ASM] Use caseInsensitive=true for ASM grammars

### PR DESCRIPTION
**Pull request by KvanTTT**

### CODE REVIEW

**Review by kaby76 — APPROVED** [review]
Excellent. Much, much cleaner. We should probably add something to the desc.xml to indicate a minimum version of Antlr 4.10 to make sure folks understand this cannot be done with an older version of the tool. Something like:
```
<?xml version="1.0" encoding="UTF-8" ?>
<desc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../_scripts/desc.xsd">
   <targets>Antlr4cs;CSharp;Cpp;Dart;Go;Java;JavaScript;TypeScript;PHP;Python3</targets>
   <version>^4.10</version>
</desc>
```
Maybe a JavaScript npm package.json version string? What do you think?

**Comment by KvanTTT** [comment]
> We should probably add something to the desc.xml to indicate a minimum version of Antlr 4.10 to make sure folks understand this cannot be done with an older version of the tool.

It sounds reasonable.

> Maybe a JavaScript npm package.json version string? What do you think?

I suggest creating an issue for that and discussing there.

**Comment by teverett** [comment]
@KvanTTT  all good to merge?

**Comment by KvanTTT** [comment]
Yes, I think so.

@kaby76 , I've created an issue: https://github.com/antlr/grammars-v4/issues/3214

**Pull request merged**
