### PR TITLE
Updates for 4.11.1

### PR DESCRIPTION
**Pull request by kaby76**

### CODE REVIEW

**Comment by kaby76** [comment]
Swift/swift3 crashing in get(), [here](https://github.com/antlr/grammars-v4/blob/a167cc13f2b61ff5d730020d526a56e12df55d02/swift/swift3/src/main/java/SwiftSupport.java#L217-#L221). It should not be calling get(), but LA() or LT(). [This code, too, is wrong](https://github.com/antlr/grammars-v4/blob/a167cc13f2b61ff5d730020d526a56e12df55d02/swift/swift3/src/main/java/SwiftSupport.java#L215)!

**Comment by kaby76** [comment]
asm8080 and asmZ80 do not pass now under Antlr 4.11.1 for Go. Unclear why except that the code does not complete in 5 minutes, and trwdog kills the process (correctly doing so because otherwise the build would hang).

**Comment by KvanTTT** [comment]
Probably we should address @jimidle

**Comment by teverett** [comment]
@kaby76  @KvanTTT  ready to merge this?

**Comment by kaby76** [comment]
It's ready to merge.

**Comment by teverett** [comment]
@kaby76  thanks!

**Pull request merged**
