### PR TITLE
VB6 Grammar Improvements

### PR DESCRIPTION
**Pull request by lee-m**
The PR adds a bunch of fixes to the VB6 grammar to resolve parse errors found when running it against a large set of real world VB6 code. 

Each change to fix a particular set of parse errors is accompanied with a corresponding reduced test case that failed to parse beforehand to ensure that it is now accepted.

These changes have also been run against @uwol's vb6 parser test suite with only one failure that is caused by the dumped AST being different to what the test is expecting due to the name of some parser rules being changed.

### CODE REVIEW

**Comment by KvanTTT** [comment]
@uwol could you please review this pull request?

**Comment by uwol** [comment]
Yes, taking a look right now.

**Comment by uwol** [comment]
Thanks @lee-m, looking great! I reviewed the changes and I did run the test suite of [vb6parser](https://github.com/uwol/vb6parser) on the modified grammar. All tests pass, no breaking changes.

**Comment by teverett** [comment]
@lee-m @uwol  thanks!

**Pull request merged**
