### PR TITLE
modify charp gramma

### PR DESCRIPTION
**Pull request by yipple**
to match Java Language complie error

### CODE REVIEW

**Comment by KvanTTT** [comment]
Please, create new target for Java without replacing code for C#. See [this](https://github.com/prompto/prompto-grammars/tree/master/Grammars/src/antlr4/prompto/parser) approach (Actually I'am not sure, wheather possible to implement it prettily and without redundancy).

**Comment by teverett** [comment]
@yipple are we ok to close this pull request and you can submit a new one as @KvanTTT suggests?

**Comment by KvanTTT** [comment]
What exactly did you change by last commit in lexer code?
Please write comments in English.

**Comment by parrt** [comment]
@KvanTTT is this ok to merge?

**Comment by KvanTTT** [comment]
I think C# and Java versions at least should be separated as it's done in our PHP grammar: https://github.com/antlr/grammars-v4/tree/master/php
Thus this PR is not ready to merge.

**Comment by teverett** [comment]
@yipple I am going to close this pull request.

**Pull request closed without merging**
