### PR TITLE
included swift into the base build

### PR DESCRIPTION
**Pull request by teverett**
removed old examples that didn't compile.  This way we can at least automatically verify that the grammar compiles and parses the two examples

### CODE REVIEW

**Comment by parrt** [comment]
Hi. can you separate out the swift stuff? I want those bad examples so I can make 'em work :) thanks!

**Comment by teverett** [comment]
Could I negotiate to check this in, and email you the broken examples?  When you have them working you can check both them and the fixed grammar in?

**Comment by parrt** [comment]
Hi Tom, can you convince maven to compile SwiftSupport.java and run the tests now? i think grammar is decent.

**Comment by teverett** [comment]
Um... not sure.  Was this expected?

<pre>
oscar:swift tom$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.antlr.grammarsv4:swift:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.antlr:antlr4test-maven-plugin is missing. @ com.antlr.grammarsv4:swift:[unknown-version], /Users/tom/projects/grammars-v4/swift/pom.xml, line 33, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ANTLR Swift grammar 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ swift ---
[INFO] Deleting /Users/tom/projects/grammars-v4/swift/target
[INFO] 
[INFO] --- antlr4-maven-plugin:4.5.1-1:antlr4 (default) @ swift ---
[INFO] ANTLR 4: Processing source directory /Users/tom/projects/grammars-v4/swift
[INFO] Processing grammar: Swift.g4
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ swift ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/tom/projects/grammars-v4/swift/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ swift ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /Users/tom/projects/grammars-v4/swift/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ swift ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/tom/projects/grammars-v4/swift/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ swift ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ swift ---
[INFO] No tests to run.
[INFO] 
[INFO] --- antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) @ swift ---
Parsing :/Users/tom/projects/grammars-v4/swift/examples/AppDelegate.swift
isPrefixOp: '[@53,397:397=' ',<139>,channel=1,17:108]','->','[@56,400:400=' ',<139>,channel=1,17:111]' is false
Parsing :/Users/tom/projects/grammars-v4/swift/examples/avail.swift
Parsing :/Users/tom/projects/grammars-v4/swift/examples/build.swift
isPostfixOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is false
isBinaryOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is true
isBinaryOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is true
isBinaryOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is true
isBinaryOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is true
isPrefixOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is false
isBinaryOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is true
isBinaryOp: '[@5,20:20=' ',<139>,channel=1,2:10]','=','[@7,22:22=' ',<139>,channel=1,2:12]' is true
isPostfixOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is false
isBinaryOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is true
isBinaryOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is true
isBinaryOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is true
isBinaryOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is true
isPrefixOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is false
isBinaryOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is true
isBinaryOp: '[@19,71:71=' ',<139>,channel=1,5:11]','=','[@21,73:73=' ',<139>,channel=1,5:13]' is true
isPrefixOp: '[@33,114:114=' ',<139>,channel=1,8:9]','&&','[@36,117:117=' ',<139>,channel=1,8:12]' is false
isBinaryOp: '[@43,128:128=' ',<139>,channel=1,9:5]','=','[@45,130:130=' ',<139>,channel=1,9:7]' is true
isBinaryOp: '[@43,128:128=' ',<139>,channel=1,9:5]','=','[@45,130:130=' ',<139>,channel=1,9:7]' is true
isBinaryOp: '[@43,128:128=' ',<139>,channel=1,9:5]','=','[@45,130:130=' ',<139>,channel=1,9:7]' is true
isPrefixOp: '[@43,128:128=' ',<139>,channel=1,9:5]','=','[@45,130:130=' ',<139>,channel=1,9:7]' is false
isBinaryOp: '[@43,128:128=' ',<139>,channel=1,9:5]','=','[@45,130:130=' ',<139>,channel=1,9:7]' is true
Parsing :/Users/tom/projects/grammars-v4/swift/examples/GameScene.swift
isBinaryOp: '[@24,198:198=' ',<139>,channel=1,12:12]','=','[@26,200:200=' ',<139>,channel=1,12:14]' is true
isBinaryOp: '[@24,198:198=' ',<139>,channel=1,12:12]','=','[@26,200:200=' ',<139>,channel=1,12:14]' is true
isBinaryOp: '[@24,198:198=' ',<139>,channel=1,12:12]','=','[@26,200:200=' ',<139>,channel=1,12:14]' is true
isPrefixOp: '[@24,198:198=' ',<139>,channel=1,12:12]','=','[@26,200:200=' ',<139>,channel=1,12:14]' is false
isBinaryOp: '[@24,198:198=' ',<139>,channel=1,12:12]','=','[@26,200:200=' ',<139>,channel=1,12:14]' is true
isBinaryOp: '[@34,232:232=' ',<139>,channel=1,13:16]','=','[@36,234:234=' ',<139>,channel=1,13:18]' is true
isBinaryOp: '[@34,232:232=' ',<139>,channel=1,13:16]','=','[@36,234:234=' ',<139>,channel=1,13:18]' is true
isBinaryOp: '[@34,232:232=' ',<139>,channel=1,13:16]','=','[@36,234:234=' ',<139>,channel=1,13:18]' is true
isPrefixOp: '[@34,232:232=' ',<139>,channel=1,13:16]','=','[@36,234:234=' ',<139>,channel=1,13:18]' is false
isBinaryOp: '[@34,232:232=' ',<139>,channel=1,13:16]','=','[@36,234:234=' ',<139>,channel=1,13:18]' is true
isBinaryOp: '[@44,268:268=' ',<139>,channel=1,14:23]','=','[@46,270:270=' ',<139>,channel=1,14:25]' is true
isBinaryOp: '[@44,268:268=' ',<139>,channel=1,14:23]','=','[@46,270:270=' ',<139>,channel=1,14:25]' is true
isBinaryOp: '[@44,268:268=' ',<139>,channel=1,14:23]','=','[@46,270:270=' ',<139>,channel=1,14:25]' is true
isPrefixOp: '[@44,268:268=' ',<139>,channel=1,14:23]','=','[@46,270:270=' ',<139>,channel=1,14:25]' is false
isBinaryOp: '[@44,268:268=' ',<139>,channel=1,14:23]','=','[@46,270:270=' ',<139>,channel=1,14:25]' is true
isBinaryOp: '[@52,298:298=' ',<139>,channel=1,15:21]','=','[@54,300:300=' ',<139>,channel=1,15:23]' is true
isBinaryOp: '[@52,298:298=' ',<139>,channel=1,15:21]','=','[@54,300:300=' ',<139>,channel=1,15:23]' is true
isBinaryOp: '[@52,298:298=' ',<139>,channel=1,15:21]','=','[@54,300:300=' ',<139>,channel=1,15:23]' is true
isPrefixOp: '[@52,298:298=' ',<139>,channel=1,15:21]','=','[@54,300:300=' ',<139>,channel=1,15:23]' is false
isBinaryOp: '[@52,298:298=' ',<139>,channel=1,15:21]','=','[@54,300:300=' ',<139>,channel=1,15:23]' is true
isBinaryOp: '[@62,336:336=' ',<139>,channel=1,16:23]','=','[@64,338:338=' ',<139>,channel=1,16:25]' is true
isBinaryOp: '[@62,336:336=' ',<139>,channel=1,16:23]','=','[@64,338:338=' ',<139>,channel=1,16:25]' is true
isBinaryOp: '[@62,336:336=' ',<139>,channel=1,16:23]','=','[@64,338:338=' ',<139>,channel=1,16:25]' is true
isPrefixOp: '[@62,336:336=' ',<139>,channel=1,16:23]','=','[@64,338:338=' ',<139>,channel=1,16:25]' is false
isBinaryOp: '[@62,336:336=' ',<139>,channel=1,16:23]','=','[@64,338:338=' ',<139>,channel=1,16:25]' is true
isBinaryOp: '[@72,377:377=' ',<139>,channel=1,17:26]','=','[@74,379:379=' ',<139>,channel=1,17:28]' is true
isBinaryOp: '[@72,377:377=' ',<139>,channel=1,17:26]','=','[@74,379:379=' ',<139>,channel=1,17:28]' is true
isBinaryOp: '[@72,377:377=' ',<139>,channel=1,17:26]','=','[@74,379:379=' ',<139>,channel=1,17:28]' is true
isPrefixOp: '[@72,377:377=' ',<139>,channel=1,17:26]','=','[@74,379:379=' ',<139>,channel=1,17:28]' is false
isBinaryOp: '[@72,377:377=' ',<139>,channel=1,17:26]','=','[@74,379:379=' ',<139>,channel=1,17:28]' is true
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammar(GrammarTestMojo.java:248)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammars(GrammarTestMojo.java:275)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:90)
	at org.antlr.v4.runtime.Parser.match(Parser.java:229)
	at SwiftParser.class_body(SwiftParser.java:9167)
	at SwiftParser.class_declaration(SwiftParser.java:9067)
	at SwiftParser.declaration(SwiftParser.java:4814)
	at SwiftParser.statement(SwiftParser.java:431)
	at SwiftParser.top_level(SwiftParser.java:335)
	... 28 more
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
	... 34 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.526 s
[INFO] Finished at: 2015-11-19T22:04:20-07:00
[INFO] Final Memory: 22M/321M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.antlr:antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) on project swift: Unable execute mojo: InvocationTargetException: ParseCancellationException: InputMismatchException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
oscar:swift tom$ 
</pre>

**Comment by parrt** [comment]
Oh sorry. Can you comment out the print statements in SwiftSupport.java?

**Comment by teverett** [comment]
It's much closer now.  There is a problem with GameScene.swift.

<pre>
Parsing :/Users/tom/projects/grammars-v4/swift/examples/AppDelegate.swift
Parsing :/Users/tom/projects/grammars-v4/swift/examples/avail.swift
Parsing :/Users/tom/projects/grammars-v4/swift/examples/build.swift
Parsing :/Users/tom/projects/grammars-v4/swift/examples/comments-adjacent-to-ops.swift
Parsing :/Users/tom/projects/grammars-v4/swift/examples/GameScene.swift
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammar(GrammarTestMojo.java:248)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammars(GrammarTestMojo.java:275)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:90)
	at org.antlr.v4.runtime.Parser.match(Parser.java:229)
	at SwiftParser.class_body(SwiftParser.java:9167)
	at SwiftParser.class_declaration(SwiftParser.java:9067)
	at SwiftParser.declaration(SwiftParser.java:4814)
	at SwiftParser.statement(SwiftParser.java:431)
	at SwiftParser.top_level(SwiftParser.java:335)
	... 28 more
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
	... 34 more

</pre>

**Comment by parrt** [comment]
I updated the grammar.

**Comment by parrt** [comment]
it looks like we have a mixture of stuff now so maybe we should separate out the Swift into its own pull request

**Comment by teverett** [comment]
ok this should be safe to pull.  It's got swift, and some other changes,however, it fully tests, and swift now compiles as part of the base grammar.

**Comment by parrt** [comment]
great! works for me.

**Pull request merged**
