### PR TITLE
[javascript] support for Go

### PR DESCRIPTION
**Pull request by shixzie**
Port of the grammar to Go. More detailed information in the `javascript/Go/README.md` file.

### CODE REVIEW

**Comment by shixzie** [comment]
The problem is that in  #1283 the `this.` prefix was added to in-grammar actions. In Go the keyword `this` does not exist to refer to the struct (class in C#, Java) containing the parsing/lexing state. In Go I could make that _state_ global but would have to remove the `this.` prefix added in the previous mentioned pr, thus breaking the JavaScript target.

**Comment by KvanTTT** [comment]
So, we need some additional preprocessing to make universal grammars with semantic predicates...

**Comment by KvanTTT** [comment]
> I could remove the grammar files inside the Go folder and simply add a note in the README inside that folder specifying the steps to fix this problem. That way we just stick with the original grammar files.

Yes, I think this is the best solution at least for now (while CI for not-java runtimes does not work).

**Comment by KvanTTT** [comment]
Thanks!

**Pull request merged**
