### PR TITLE
added PHP grammar for Java (ported from the existing C# runtime grammer)

### PR DESCRIPTION
**Pull request by wsdookadr**
I need to use the PHP ANTLR4 grammar in a Java project. Currently, there
[is a PHP grammar that has a Lexer with code actions written in C#](https://github.com/antlr/grammars-v4/tree/master/php).

This pull request is bringing a port of the existing C# lexer to Java.

All the other tests are passing except for these two:

    examples/alternativeSyntax.php
    examples/heredoc.php

For heredoc.php [the test report is here](http://pastebin.com/raw/GbNF919k) 
For alternativeSyntax.php [the test report is here](http://pastebin.com/raw/fTTVQfNh) 

I'm currently not sure how to fix those two failed tests.

### CODE REVIEW

**Comment by KvanTTT** [comment]
I'll look at falling tests.

**Comment by wsdookadr** [comment]
@KvanTTT thank you ! :thumbsup:

**Comment by KvanTTT** [comment]
1. You should convert input char stream to lower case for PHP.
2. Correct java strings comparison: `a.equals(b)` (value) instead of `a == b` (reference).
3. Too many excess code.

I created a new pull request: https://github.com/antlr/grammars-v4/pull/470
So, this PR should be closed.

**Comment by wsdookadr** [comment]
Yeah, I agree. Looking at your PR, looks quite good.
Thanks a lot ! :+1:

**Pull request closed without merging**
