### PR TITLE
VBA Grammar updated

### PR DESCRIPTION
**Pull request by Xenios91**
Added support for line numbers. Line numbers do not appear to be common anymore, however, they are part of the VBA language. A line number acts just like a line label except it is a digit and the colon after it is optional.

The goto statement has more information

https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/goto-statement

### CODE REVIEW

**Comment by Xenios91** [comment]
got a bug to fix i just found

**Comment by Xenios91** [comment]
should be good now

**Review by KvanTTT — CHANGES_REQUESTED** [review]
Please add an example to [examples](https://github.com/antlr/grammars-v4/tree/master/vba/examples) that covers suggested changes.

**Comment by Xenios91** [comment]
Should be good now with https://github.com/antlr/grammars-v4/pull/3755/commits/34108570d68dc22dcc7c35074ca9469a3583cd4b

**Review by KvanTTT — APPROVED** [review]

**Pull request merged**
