### PR TITLE
Add Analytic Window Functions to Lexer and Parser

### PR DESCRIPTION
**Pull request by tuxmania87**
I added following Tokens to Lexer:
FIRST_VALUE
LAST_VALUE
LAG
LEAD

I also added rules to the parser in order to parse those tokens properly according to Microsoft documentation:
 https://docs.microsoft.com/en-us/sql/t-sql/functions/analytic-functions-transact-sql

### CODE REVIEW

**Comment by KvanTTT** [comment]
Could you also add a test sample for this syntax?

**Comment by tuxmania87** [comment]
```
SELECT FIRST_VALUE(InvoiceNo) OVER(PARITION BY CustomerNo ORDER BY InvoiceDate) as FirstInvoiceNoPerCustomer
FROM dbo.Invoices
```
Same goes for LAST_VALUE

for LEAD/LAG

```
SELECT LEAD(ValidFrom) OVER(ORDER BY ValidFrom) AS NextValidFrom
FROM dbo.factTable

SELECT LEAD(ValidFrom,2 ) OVER(ORDER BY ValidFrom) AS NextValidFromOffset2
FROM dbo.factTable

-- offset taken from OffsetColumn, if OffsetColumn is null take 5 as offset
SELECT LEAD(ValidFrom, OffsetColumn, 5) OVER(ORDER BY ValidFrom) AS NextValidFrom
FROM dbo.factTable
```

**Comment by KvanTTT** [comment]
You have to add them to examples directory to respective file (control flow, dml statements, etc.)

**Comment by tuxmania87** [comment]
I can sure do it, but there are also no examples for already implemented window functions

**Comment by KvanTTT** [comment]
>I can sure do it, but there are also no examples for already implemented window functions

We constantly improving this repository and grammar quality :) So, it' very desirable to have a test sample for every grammar change.

Take a look on your changes: there is something wrong with grammar or tests samples. See [errors](https://travis-ci.org/antlr/grammars-v4/builds/254786359#L4769) for details.

**Comment by teverett** [comment]
@tuxmania87 thanks for the commits.  @KvanTTT all good to pull this?

**Comment by KvanTTT** [comment]
All good.

**Pull request merged**
