### PR TITLE
Add testing for PHP target

### PR DESCRIPTION
**Pull request by kaby76**
This is a partial solution to #2488. The code "skips" the grammars that I mentioned in the comments for the issue. The PR uses a new version of trgen required for PHP and Go, templates for PHP, updated skip lists (removing some bugs). Although the Powershell version of the CI works, I chose to use the regtest.sh version because the Antlr4 PHP runtime has a restriction in PHP 7.4 that I did not anticipate, and so limited the testing of PHP just to Linux (as the older version doesn't seem available on other OSes).

### CODE REVIEW

**Comment by kaby76** [comment]
$skip = Get-GrammarSkipList -Target $Target | Resolve-Path -Relative

test.ps1 requires the skip list to be hard-core paths in the file system, while regtest.sh allows them to actually be patterns. Unfortunately, when I made the list online, "autocorrecting" mutated the names, which I transcribed to the actual skip-php.txt file.

**Comment by kaby76** [comment]
The Antlr 0.5.1 PHP runtime is compatible with PHP8.1 so I'm not sure why there is a problem. with composer. https://github.com/antlr/grammars-v4/runs/4960091050?check_suite_focus=true#step:9:5437. I will try to address this later.

**Comment by teverett** [comment]
@kaby76  is this ready to pull?

**Comment by kaby76** [comment]
@teverett Yes. This is ready to merge. If we want the grammars that are currently on the skip list for PHP to actually work with PHP, we will need to either change symbols in the grammars that cause conflicts (like "Class: 'class'" in a lexer grammar) or wait for Antlr 4.10. In the meanwhile, let's make sure people are aware of symbol conflicts for PHP. @KvanTTT 

On "target agnostic grammars", I think we are actually very close to finding a solution. I found an undocumented action attribute "$parser" that works for most targets. Antlr would need to be extended for "$lexer" to access the lexer class or "$self" to access either lexer or parser. We'd also need a change to Cpp .stg for rewrite "$parser" into "(*this)" and extending for PHP with a rewrite of "$parser." to "$this->".

**Comment by teverett** [comment]
@kaby76  thanks

**Pull request merged**
