### PR TITLE
Replace old Java grammar with the new one (Java8) and other fixes

### PR DESCRIPTION
**Pull request by KvanTTT**
* Java 8 grammar fixed and simplified.
* AllInOne8.java test files splitted on AllInOne7.java and AllInOne8.java.
* Added benchmark and correctness tests for different projects (see Benchmarks.md).

### CODE REVIEW

**Comment by parrt** [comment]
Looking great! Why have java and javascript mixed up in same PR though?

**Comment by KvanTTT** [comment]
There are small fixes in README and license notes not related to grammar itself :)

**Comment by parrt** [comment]
Ok, @teverett What do you think? the grammar changes don't seem that major and if it parses 8, i'm cool with it.  We should however keep the pure java8 grammar that is close to the spec.

**Comment by teverett** [comment]
I'm good!

**Pull request merged**
