### PR TITLE
[Snowflake]Improve table parsing

### PR DESCRIPTION
**Pull request by MasterKuat**
Replacement for ( NOT? NULL_ )? to null_not_null rule and added to column def as column nullable constraint could be explicitly set to NULL.

I also added a optional position for the if_not_exists?. Documentation specify that if_not_exists is before object_name but in real world it could be after.

 I just do that for create Table (because I get the case) but it should be same thing for other create statement. (Issue to create for tracking that ?)
if_not_exists after object_name could be a "CodeSmell"'s feature but I think it's not business of grammar 😄

### CODE REVIEW

**Comment by teverett** [comment]
@MasterKuat  please resolve the merge conflicts

**Comment by MasterKuat** [comment]
@teverett conflict  resolved.
Thanks.

**Comment by teverett** [comment]
@MasterKuat i still see a conflict?

**Comment by MasterKuat** [comment]
@teverett Yeah, because you merged another PR of mine 🤣 
I fix it right away

**Review by KvanTTT — APPROVED** [review]

**Comment by teverett** [comment]
@MasterKuat thanks!

**Pull request merged**
