### PR TITLE
fortran77: fix gotoStatement

### PR DESCRIPTION
**Pull request by BBreiden**
The gotoStatement should accept "GO TO" and "GOTO".

### CODE REVIEW

**Comment by KvanTTT** [comment]
Could you please add an example (to `fortran77/examples`) that covers suggested changes?

**Comment by BBreiden** [comment]
I have added an example. I hope this is ok. Otherwise just let me know!

**Comment by KvanTTT** [comment]
CI says there are errors on Fortran: https://github.com/antlr/grammars-v4/actions/runs/3890697712/jobs/6644788312#step:17:52

**Comment by BBreiden** [comment]
I will try to reproduce and try to fix it.

**Comment by kaby76** [comment]
The old tester.psm1/test.ps1 scripts doesn't print out the error messages for [the new test input](https://github.com/antlr/grammars-v4/actions/runs/3890697712/jobs/6644788312#step:17:48). That's will be fixed with my rewrite of the test scripts. https://github.com/antlr/grammars-v4/pull/2989
```
Java 0 ../examples/example1.txt success 0.03
Java 1 ../examples/example2.txt success 0.018
line 7:9 missing 'TO' at 'to'
line 7:12 extraneous input '20' expecting EOL
line 9:6 no viable alternative at input '10write'
line 12:6 no viable alternative at input '20goto'
Java 2 ../examples/goto-example.txt fail 0.03
Total Time: 0.229
```

**Comment by BBreiden** [comment]
The TO token was only defined as uppercase but the example uses lower case. I fixed the token file. Can we please rerun CI?

**Comment by kaby76** [comment]
> The TO token was only defined as uppercase but the example uses lower case. I fixed the token file. Can we please rerun CI?

Is it Fortran77 if lowercase is used? Fortran77 uses only uppercase for the language but can process lowercase data. I recall wasting a lot of money on buying punch cards on this issue.

**Comment by BBreiden** [comment]
Well, you're more expert than me, if you remember punch cards... :-)
But you are correct, I think. Looking at the Oracle documentation, they only use uppercase. However, the current version of the grammar allows lower case. The TO was an exception of not being defined in both (upper and lower) cases. The example2.txt also uses lower case. And GNU F77 didn't complain, when I tried to compile my example... ;-)

**Comment by kaby76** [comment]
If other keywords are accepted in lowercase in the grammar, make it consistent.  But the compiler is wrong and I do recall the CDC compiler barfing on l.c. code. It makes me wonder what else is wrong with this grammar.

**Comment by BBreiden** [comment]
I think, it is far from perfect at the moment. E.g. labels are only allowed on CONTINUE statements but not on other executable statements. Also in an ELSE IF statement you cannot use comments (I opened another PR to fix this).

**Pull request merged**
