### PR TITLE
Fix mistakes in Swift grammar and add more examples

### PR DESCRIPTION
**Pull request by Marti2203**
I just saw the new Swift grammar and began testing it. I have not had issues for now, except the problems with the lexer tokens.

### CODE REVIEW

**Comment by studentmain** [comment]
It's weird, why some test passed and other reported parse error.

**Comment by Marti2203** [comment]
I really do not know enough about the testing capabilities of the repo to give a solid reason. I just changed 3 rules and I am using the same grammar now locally.

**Comment by studentmain** [comment]
> It's weird, why some test passed and other reported parse error.

Now I know why. Those succeed tests are marked as skip in previous PR, they didn't run at all as intended... Let's just look at failed test.

**Comment by Marti2203** [comment]
> > It's weird, why some test passed and other reported parse error.
> 
> Now I know why. Those succeed tests are marked as skip in previous PR, they didn't run at all as intended... Let's just look at failed test.

I tried running the tests, but the runtime needs the SwiftSupport class

**Comment by Marti2203** [comment]
Okay, I have found an edge case in one the examples I have put. I will find a fix for it now.

**Comment by Marti2203** [comment]
I have made a huge rework - had to split into lexer and parser grammars as lexer modes are needed for interpolation. Currently I am trying to catch small edge cases.

**Comment by Marti2203** [comment]
I have made string interpolation work fully, captured some old swift constructs and added more keywords as identifiers.

**Comment by teverett** [comment]
@Marti2203 thanks

**Pull request merged**
