### PR TITLE
fix: allow java super invocations

### PR DESCRIPTION
**Pull request by devanshj**
Fixes [this downstream issue](https://github.com/urish/java-ast/issues/2). I'm no grammar expert but this LGTM.

### CODE REVIEW

**Comment by teverett** [comment]
@devanshj  Thanks for this.  Could you add an example for it pls?

**Comment by devanshj** [comment]
Was about to update the comment (you're too fast haha) that there's already a test case

https://github.com/antlr/grammars-v4/blob/eada6a136ae7189b52a2a192c6b8fa280b8cf11b/java/java/examples/AllInOne7.java#L527

**Comment by studentmain** [comment]
https://github.com/antlr/grammars-v4/blob/fe2dddcd8a945d84814caef77361e1f06c35e37e/java/java/JavaParser.g4#L465

**Comment by devanshj** [comment]
Aye haha it's already there let me see if it's stale downstream

**Pull request closed without merging**
