### PR TITLE
Updating the Scala grammar [WIP]

### PR DESCRIPTION
**Pull request by Marti2203**
This is the PR containing the work mentioned in  #1983.
@kaby76 @Vladimir-Chan @aryx

### CODE REVIEW

**Comment by Marti2203** [comment]
I am still thinking on whether to make the ScalaParser encapsulate the TokenStream it gets and puts it inside of a Scala Token Stream, but I am not sure that is good design, I would like to make the testing infrastructure understand this. @kaby76 iirc you are the one that works on it currently/

**Comment by kaby76** [comment]
@Marti2203 I'm checking out the code. So, for CI builds, you're going to need an updated pom.xml file. Rogo*.g4 should be replaced with Scala*.g4 in the antlr4-maven-plugin spec of the pom.xml, otherwise the Antlr tool isn't even run to generate a parser.

**Comment by Marti2203** [comment]
I wrote the wrong names...

**Comment by kaby76** [comment]
And, all that `@header` and action code should be yanked into a base class, and placed in grammars-v4/scala/Java. I'll write the base class code for every other target, but I gather there's going to need to be a special case driver written. I'll need that code soon so I can change the CI build to trgen a special case for this grammar.

**Comment by kaby76** [comment]
I moved around some stuff and got it to this point where it's started to go in the direction of target independence. See the attached zip. 
[scala.zip](https://github.com/antlr/grammars-v4/files/6616127/scala.zip) The actions should all go into "agnostic style", i.e., action code stuffed into a method on the base class, and replaced with "{ self.whatever_action(); }". (See the [Python doc](https://github.com/antlr/antlr4/blob/master/doc/python-target.md#target-agnostic-grammars)).

**Comment by Marti2203** [comment]
The grammar works, but now I need to make it target agnostic... This will take a day or two...

**Comment by teverett** [comment]
@Marti2203  are you planning to continue work on this PR?

**Comment by teverett** [comment]
@Marti2203  I am closing this for now.  You are welcome to re-open it with merge fixes.

**Comment by Vladimir-Chan** [comment]
I don't know scala so I can't help this issue.

**Comment by Vladimir-Chan** [comment]
I don't know scala so I can't help solve this issue.

**Pull request closed without merging**
