### PR TITLE
Restructured the repository.

### PR DESCRIPTION
**Pull request by KOLANICH**
Fixes: #2826

### CODE REVIEW

**Comment by kaby76** [comment]
As I expected, the first thing I had to do was create a Bash function to `cd` around because I'm totally lost otherwise.
```
Kenne@DESKTOP-DL44R7B MINGW64 ~/proposal/grammars-v4
$ mycd() { d=`find . -name "$1" -type d`; cd "$d"; }

Kenne@DESKTOP-DL44R7B MINGW64 ~/proposal/grammars-v4
$ mycd cpp

Kenne@DESKTOP-DL44R7B MINGW64 ~/proposal/grammars-v4/programming/mainstream/cpp
$ cd ..

Kenne@DESKTOP-DL44R7B MINGW64 ~/proposal/grammars-v4/programming/mainstream
$ cd ..

Kenne@DESKTOP-DL44R7B MINGW64 ~/proposal/grammars-v4/programming
$ cd ..

Kenne@DESKTOP-DL44R7B MINGW64 ~/proposal/grammars-v4
$ mycd abb

Kenne@DESKTOP-DL44R7B MINGW64 ~/proposal/grammars-v4/embedded/abb
$
```
It works okay for most things, but it's not fullproof: there are many directories named "java" (some of which are incorrect before this PR).

So, as expected, we going to need a script to navigate around this new structure, either give the grammar name, or the directory name associated with a grammar, or some other thing.

The build doesn't work because Maven is used to recursively descend the directory structure, which is now changed.

**Comment by teverett** [comment]
@KOLANICH  do we still need this PR?

**Comment by KOLANICH** [comment]
I have created it to make the navigation and selection (the purpose of a grammar says something about its complexity, for example identifiers are likely to be simpler than a mainstream programming language) easier. IDK if the projects maintainers do still need the changes proposed here

**Comment by teverett** [comment]
@KOLANICH  thanks for this.  I'll close it for now.

**Pull request closed without merging**
