### PR TITLE
[bcpl] Make working bcpl grammar.

### PR DESCRIPTION
**Pull request by kaby76**
Fix for issue #3435, the bcpl grammar.

### CODE REVIEW

**Comment by kaby76** [comment]
The BCPL grammar was originally scraped from the 1981 book by Richards. (I used BCPL in several classes in grad school, and helped port the compiler.) But, the language and grammar were extended through the years, and the original grammar did not work on most of the examples. Using the online [Bcplman documentation](https://www.cl.cam.ac.uk/~mr10/bcplman.pdf) from Richard's home page, I converted parts of the "railroad" diagrams into a CFG, and then modified the grammar further to parse all the examples here in this repo.

Two ports are provide: CSharp and Java. The ports required a new token stream class that allowed lookback and lookforward for off-channel tokens. The parser base class essentially throws away the CommonTokenStream created in the driver, creates a new one based on ChannelCommonTokenStream, and passes that to the parser base constructor.

**Comment by kaby76** [comment]
@KvanTTT Please look over this PR. You have a good eye for detail. Thanks.

**Comment by teverett** [comment]
Added @KvanTTT  as reviewer

**Comment by KvanTTT** [comment]
Ok, I'll review next week.

**Comment by teverett** [comment]
@kaby76  thanks

**Pull request merged**
