### PR TITLE
[lua] cleanup

### LINKED ISSUE #1824: Lua parser: incorrect parsing of function calls?
Parsing the following with the test rig
```lua
a = funcA()
```
gives
```
(chunk (block (stat (varlist (var a)) = (explist (exp (prefixexp (varOrExp (var funcA)) (nameAndArgs (args ( )))))))) <EOF>)
```

I'd expect ```funcA()``` to be parsed as a function call.

Function calls without return values in a "stat" are parsed correctly e.g.

```lua
funcA()
```
has the following tree:
```
(chunk (block (stat (functioncall (varOrExp (var funcA)) (nameAndArgs (args ( )))))) <EOF>)
```
Function calls in a "retstat" are also not parsed as function calls:

```lua
return {
    funcA()
}
```
has the following tree:

```
(chunk (block (retstat return (explist (exp (tableconstructor { (fieldlist (field (exp (prefixexp (varOrExp (var funcA)) (nameAndArgs (args ( ))))))) }))))) <EOF>)
```

Adding "functioncall" as one of the alternatives for "exp" seems to fix the problem e.g.

```diff
diff --git a/lua/Lua.g4 b/lua/Lua.g4
index 4230fe05..657505a6 100644
--- a/lua/Lua.g4
+++ b/lua/Lua.g4
@@ -112,6 +112,7 @@ exp
     | string
     | '...'
     | functiondef
+    | functioncall
     | prefixexp
     | tableconstructor
     | <assoc=right> exp operatorPower exp
```

### PR DESCRIPTION
**Pull request by kaby76**
This PR addresses #3743, #3741, #3724, #3652, #3311, #1824. While it may seem these are all distinct problems, in reality they are all closely related.

### Issues addressed

* #3743 -- This is just a wrapper issue for all the other issues.
* #3741 -- This PR fixes the issues with short and long comments.
* #3724 -- This issue should be closed because the issue raised was incorrect.
* #3652 -- This PR fixes the issues with long comments (aka "block comments").
* #3311 -- This PR fixes the problem with "retstat" aka "laststat". A semi colon must be recognized as this is acceptable with the Lau interpreter.
* #1824 -- This PR fixes the number and location of functioncall's for a parse.

### Changes
First, what was actually changed of the grammar?
* The grammar was split. This was required so that semantic predicates and actions could then be added.
* Fixed recognition of Lua's short and long comments, modeled after the lexer source code for the Lua compiler.
* Fixed special '#' first line. Here we check the Index on the CharBuffer.
* Added base class code for all targets for the grammar.  All but PHP and Swift.
* Re-did the syntax for function calls. Starting with the EBNF in the [Lua Manual](https://www.lua.org/manual/5.4/manual.html), I replaced the old rules [block](https://github.com/antlr/grammars-v4/blob/63143de6fe654e2407852b422c9cad046ce11277/lua/Lua.g4#L73-L75), [laststat](https://github.com/antlr/grammars-v4/blob/63143de6fe654e2407852b422c9cad046ce11277/lua/Lua.g4#L103-L105), [explist](https://github.com/antlr/grammars-v4/blob/63143de6fe654e2407852b422c9cad046ce11277/lua/Lua.g4#L123-L125), [prefixexp](https://github.com/antlr/grammars-v4/blob/63143de6fe654e2407852b422c9cad046ce11277/lua/Lua.g4#L146-L148), [funcioncall](https://github.com/antlr/grammars-v4/blob/63143de6fe654e2407852b422c9cad046ce11277/lua/Lua.g4#L150-L152), [varOrExp](https://github.com/antlr/grammars-v4/blob/63143de6fe654e2407852b422c9cad046ce11277/lua/Lua.g4#L154-L156), and [var](https://github.com/antlr/grammars-v4/blob/63143de6fe654e2407852b422c9cad046ce11277/lua/Lua.g4#L158-L160). The grammar derived from the manual doesn't work out of the box because of indirectly left recursion. I fixed that by refactoring `var`, `prefixexp`, and `functioncall` to fix #1824. For a detailed description of the refactoring, see https://github.com/antlr/grammars-v4/issues/1824#issuecomment-1752964931. I renamed `laststat` to `retstat` in keeping with the manual, but it's clear there is more here. There is no `continue` keyword in the Manual version 5.4.

### Added
Next, what was added?
* Added test for #3311.
* Added test for #3724, but it is not on automated test system. The Issue's test is in fact, illegal Lua code. Unfortunately, the Antlr4 Go and PHP runtimes have a bug. https://github.com/antlr/antlr4/issues/4436
* Added test for #3741. For a detailed discussion, see [this comment](https://github.com/antlr/grammars-v4/issues/3741#issuecomment-1753171566).
* Added tests from Lua testsuite https://www.lua.org/tests/
* Added a readme so people can maintain this grammar.
* Added test for #3652.

### Issues
There were several problems discovered in the ports. Two Issues were created related to the Antlr4 runtime.
* https://github.com/antlr/antlr4/issues/4437
* https://github.com/antlr/antlr4/issues/4436

### Future work
I think there is more to consider with this grammar. In particular, there is a `continue` keyword in the grammar, but it's not in the Manual EBNF. Further, the parser code diverges a bit with no `prefixexp`.

### CODE REVIEW

**Comment by kaby76** [comment]
* The grammar given in https://www.lua.org/manual/5.4/manual.html is not the same grammar in the comments in the source, e.g., there is no [suffixedexp](https://github.com/lua/lua/blob/6baee9ef9d5657ab582c8a4b9f885ec58ed502d0/lparser.c#L1103). And, likely, the grammar in the comments in the source code for the compiler probably don't match the top-down parser.
* The lua grammar in Antlr4 was probably derived from the Manual (last section of the webpage https://www.lua.org/manual/5.4/manual.html). But, the grammar was refactored in a way I cannot understand to remove the indirect left recursion involving "[var, prefixexp, functioncall]". The easiest and classic way to remove mutual left recursion is to use unfolding, two with this grammar. I did that, but it does not fix [the problem described in this comment](https://github.com/antlr/grammars-v4/issues/1824#issuecomment-765538939).
* I will try to reverse engineer the grammar by hand from the source code. This seems relatively easy because the parser is quite small.

**Comment by kaby76** [comment]
It appears that there are (at least) two entry points, or different semantic actions, for Lua.

For this input, the interpreter accepts arguments over several lines.
```
10/08-08:15:12 ~/lua-5.4.6/src
$ cat y
foo = function(a) print(a); return print; end
foo("hi") "there"

foo "hi" "there"

foo "hi"

"there"

10/08-08:15:16 ~/lua-5.4.6/src
$ ./lua.exe y
hi
there
hi
there
hi
there
10/08-08:15:24 ~/lua-5.4.6/src
$ ./lua.exe
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
> foo = function(a) print(a); return print; end
>
> foo("hi") "there"
hi
there
>
> foo "hi" "there"
hi
there
>
> foo "hi"
hi
function: 00007ffcb7cff280
>
> "there"
there
> ^Z

10/08-08:16:37 ~/lua-5.4.6/src
$ echo '"there"'
"there"
10/08-08:16:47 ~/lua-5.4.6/src
$ echo '"there"' | ./lua.exe
C:\msys64\home\Kenne\lua-5.4.6\src\lua.exe: stdin:1: unexpected symbol near '"there"'
10/08-08:16:56 ~/lua-5.4.6/src
$ ./lua.exe
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
> "there"
there
> ^Z

10/08-08:17:11 ~/lua-5.4.6/src
```

Notice, however, that when entered in "interactive mode", the interpreter evaluates `foo("hi")` then returns and prints a function pointer. It also takes a string literal and prints the value, yet we see that the interpreter does not accept the string as a valid program in non-interactive mode.

**Comment by kaby76** [comment]
Almost there. I must also output an error if a block comment ends without the closing end double=bracket pattern.

**Comment by Dongyang0810** [comment]
Waiting for a Go target

**Comment by kaby76** [comment]
> Waiting for a Go target

Sometime today I should be finished with all the targets and the PR.

**Comment by kaby76** [comment]
The Go-target is working but it does not produce identical error messages for a token recognition error. This is a bug in the Antlr4 Go runtime. Here is now the parser operates on 3724.lua vs how *it should be* with the CSharp target.

```
10/10-12:41:55 ~/issues/g4-lua-readme/lua/Generated-Go
$ ./Test.exe ../.ignore/3724.lua
line 1:4 token recognition error at: '"\C'
line 2:5 token recognition error at: '\'
line 3:4 token recognition error at: '"\"CSubs\i'
line 3:22 token recognition error at: '"
a = 'http:./.\.'
line 4:16 token recognition error at: '\'
line 4:17 token recognition error at: ''
a = "http:/.\.'
line 5:14 mismatched input '/' expecting {'function', 'nil', 'false', 'true', '~', '-', '#', '(', 'not', '{', '...', NAME, NORMALSTRING, CHARSTRING, LONGSTRING, INT, HEX, FLOAT, HEX_FLOAT}
line 5:16 token recognition error at: '\'
line 5:15 mismatched input '.' expecting {'function', 'nil', 'false', 'true', '~', '-', '#', '(', 'not', '{', '...', NAME, NORMALSTRING, CHARSTRING, LONGSTRING, INT, HEX, FLOAT, HEX_FLOAT}
line 6:6 token recognition error at: '\'
line 6:8 token recognition error at: '\'
line 7:5 token recognition error at: '\'
line 7:6 token recognition error at: '\'
line 8:6 token recognition error at: '"
'
line 9:0 mismatched input '<EOF>' expecting {'function', 'nil', 'false', 'true', '~', '-', '#', '(', 'not', '{', '...', NAME, NORMALSTRING, CHARSTRING, LONGSTRING, INT, HEX, FLOAT, HEX_FLOAT}
Go 0 ../.ignore/3724.lua fail 0.003
Total Time: 0.004 s
10/10-12:42:10 ~/issues/g4-lua-readme/lua/Generated-Go
$ pushd
~/issues/g4-lua-readme/lua/Generated-CSharp ~/issues/g4-lua-readme/lua/Generated-Go
10/10-12:42:16 ~/issues/g4-lua-readme/lua/Generated-CSharp
$ ./bin/Debug/net7.0/
Antlr4.Runtime.Standard.dll                     System.Configuration.ConfigurationManager.dll
Antlr4BuildTasks.dll                            System.Drawing.Common.dll
Microsoft.Build.Framework.dll                   System.Security.Cryptography.ProtectedData.dll
Microsoft.Build.Utilities.Core.dll              System.Security.Permissions.dll
Microsoft.NET.StringTools.dll                   System.Windows.Extensions.dll
Microsoft.Win32.SystemEvents.dll                Test.dll
runtimes/                                       Test.exe
System.CodeDom.dll
10/10-12:42:16 ~/issues/g4-lua-readme/lua/Generated-CSharp
$ ./bin/Debug/net7.0/Test.exe ../.ignore/3724.lua
line 1:4 token recognition error at: '"\C'
line 2:5 token recognition error at: '\'
line 3:4 token recognition error at: '"\"CSubs\i'
line 3:22 token recognition error at: '"\na = 'http:./.\.'
line 4:16 token recognition error at: '\'
line 4:17 token recognition error at: ''\na = "http:/.\.'
line 5:14 mismatched input '/' expecting {'function', 'nil', 'false', 'true', '~', '-', '#', '(', 'not', '{', '...', NAME, NORMALSTRING, CHARSTRING, LONGSTRING, INT, HEX, FLOAT, HEX_FLOAT}
line 5:16 token recognition error at: '\'
line 5:15 mismatched input '.' expecting {'function', 'nil', 'false', 'true', '~', '-', '#', '(', 'not', '{', '...', NAME, NORMALSTRING, CHARSTRING, LONGSTRING, INT, HEX, FLOAT, HEX_FLOAT}
line 6:6 token recognition error at: '\'
line 6:8 token recognition error at: '\'
line 7:5 token recognition error at: '\'
line 7:6 token recognition error at: '\'
line 8:6 token recognition error at: '"\n'
line 9:0 mismatched input '<EOF>' expecting {'function', 'nil', 'false', 'true', '~', '-', '#', '(', 'not', '{', '...', NAME, NORMALSTRING, CHARSTRING, LONGSTRING, INT, HEX, FLOAT, HEX_FLOAT}
CSharp 0 ../.ignore/3724.lua fail 0.0481767
Total Time: 0.1020666
10/10-12:42:32 ~/issues/g4-lua-readme/lua/Generated-CSharp
$
```


The test 3724.lua was moved to the directory ".ignore/". A bug issue should be reported to the github.com/antlr/antlr4 repo.

**Comment by kaby76** [comment]
https://github.com/antlr/antlr4/issues/4436

**Comment by kaby76** [comment]
https://github.com/antlr/antlr4/issues/4437

**Comment by kaby76** [comment]
All set.

**Comment by teverett** [comment]
@kaby76  thanks!

**Pull request merged**
