### PR TITLE
Update Antlrv4 grammar & add StringTemplate grammar

### PR DESCRIPTION
**Pull request by grosenberg**
Update Antlrv4 grammar & add StringTemplate grammar

### CODE REVIEW

**Comment by parrt** [comment]
Hi Gerald, looks interesting. sorry for delay. racing to get 4.5.1 out.

**Comment by GRosenberg** [comment]
No problem.  Was not expecting an automatic accept - the restructuring is worth looking at to see if it is appropriate for the repository version.  I would think that it should be idiomatic (whatever that means) as well as a showcase of the available features.

**Comment by teverett** [comment]
@grosenberg would it be possible for you to add a pom.xml to the STG grammar, add some test cases and reference the STG pom from the root pom?  This would allow the test suite to verify your grammar after every change. It would also allow the test suite to verify that no breaking changes to ANTLR4 are made.

**Comment by parrt** [comment]
A very interesting idea. @teverett  is the mvn expert here so I'll leave it up to him :)

**Comment by parrt** [comment]
@grosenberg  can you remind me from where you derived grammars? I think maybe I will grab the grammar I have for the intellij plug-in and insert that.  I need to get a good antlr v4 version of the StringTemplate grammar two so maybe I can use yours there.

**Comment by teverett** [comment]
If you'll do the pull @parrt, I'l do the pom.xml now and submit a pull for that.

**Comment by parrt** [comment]
ok, maybe I'll use this as a guide and create a new PR based upon Gerald's work here. let me play around a little bit.

**Comment by parrt** [comment]
actually,Pulling into a local branch now to review as it looks pretty good.

**Pull request merged**
