### PR TITLE
Added ALTER DATABASE options and an example file.

### PR DESCRIPTION
**Pull request by vijaygill**
After a few failed attempts...

### CODE REVIEW

**Comment by teverett** [comment]
Same issue as before

```
[INFO] 
[INFO] --- antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) @ tsql ---
Parsing :/home/travis/build/antlr/grammars-v4/tsql/examples/control_flow.sql
line 113:13 no viable alternative at input '@Number>100'
java.lang.reflect.InvocationTargetException
	at sun.
```

**Comment by vijaygill** [comment]
That's puzzling. I have it working on my side...let me investigate....

**Comment by vijaygill** [comment]
Another attempt..

**Comment by teverett** [comment]
@vijaygill I'll pull this, however could we add more examples?

**Comment by vijaygill** [comment]
@teverett Sure! I am going to work on adding more grammar in coming days, I will add more examples too.
Thanks.

**Pull request merged**
