### PR TITLE
Fortran77

### PR DESCRIPTION
**Pull request by teverett**

### CODE REVIEW

**Comment by parrt** [comment]
heh, cool! can we add some sample input?

**Comment by teverett** [comment]
Not yet.


On Sat, May 21, 2016 at 10:17 AM, Terence Parr <notifications@github.com>
wrote:

> heh, cool! can we add some sample input?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/grammars-v4/pull/384#issuecomment-220786507>
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by parrt** [comment]
Ok, i'll merge anyway.

**Comment by teverett** [comment]
thx


On Sat, May 21, 2016 at 12:04 PM, Terence Parr <notifications@github.com>
wrote:

> Merged #384 <https://github.com/antlr/grammars-v4/pull/384>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/grammars-v4/pull/384#event-668016133>
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by teverett** [comment]
There is a java antlr example here

https://github.com/teverett/antlr4example

**Pull request merged**
