### PR TITLE
Parse model responses

### PR DESCRIPTION
**Pull request by i-walker**
Though it is not part of the SMT spec, most solvers parse their `get-model-response` like this
```smt
(model
  (define-fun b () Int
    1)
  (define-fun a () String
    "\x00")
)
```

instead of  the following, for better readability.
```smt
(
  (define-fun b () Int
    1)
  (define-fun a () String
    "\x00")
)
```
This PR adds support for both responses

### CODE REVIEW

**Comment by i-walker** [comment]
It fails with 
```
[INFO] Parsing :/Users/ulti_mate/IdeaProjects/Arrow_with_Access/Smt/grammars-v4/smtlibv2/examples/test12.smt2
line 2:3 no viable alternative at input '(model(define-fun'
com.khubla.antlr.antlr4test.AssertErrorsException: found 1 errors, but missing file test12.smt2.errors
        at com.khubla.antlr.antlr4test.AssertErrorsErrorListener.assertErrors(AssertErrorsErrorListener.java:70)
        at com.khubla.antlr.antlr4test.ScenarioExecutor.testGrammar(ScenarioExecutor.java:180)
        at com.khubla.antlr.antlr4test.ScenarioExecutor.testGrammars(ScenarioExecutor.java:82)
        at com.khubla.antlr.antlr4test.GrammarTestMojo.testScenarios(GrammarTestMojo.java:346)
        at com.khubla.antlr.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:176)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at `org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)`
```

**Comment by i-walker** [comment]
No need I found the issue :)

**Comment by i-walker** [comment]
@teverett may I get a review on this :)
It doesn't break the previous gramma

**Comment by teverett** [comment]
@i-walker  thanks!

**Pull request merged**
