### PR TITLE
[Snowflake] fix 'and' problem

### PR DESCRIPTION
**Pull request by gaoshihang**

### CODE REVIEW

**Comment by kaby76** [comment]
Could you describe the problem with an example, which this change fixes? Thank you.

**Comment by gaoshihang** [comment]
Hi @kaby76 thanks for your reply.
This PR is related to the issue: https://github.com/antlr/grammars-v4/issues/3787
If 'AND' is a expr, we can't divide the different where condition.
Hopes you can help review this, if have some problem, please tell me.

**Comment by gaoshihang** [comment]
Hi @kaby76 , can you help me review on this? please

**Comment by gaoshihang** [comment]
Seems already fixed by https://github.com/antlr/grammars-v4/commit/51081f9aa1590d2e112ca48a179467eb27e9ab07, close this PR, Thanks!

**Pull request closed without merging**
