### PR TITLE
fix LuaLexerBase;

### PR DESCRIPTION
**Pull request by niu2x**
'\n' ascii is 10, instead of 12

### CODE REVIEW

**Comment by kaby76** [comment]
@teverett This PR corrects a bug in the lua grammar. I think there was a timeout issue for the Dart target. So, maybe the build can be tried again?

**Comment by teverett** [comment]
@niu2x please rebase

**Comment by niu2x** [comment]
> @niu2x please rebase

yes, done

**Comment by kaby76** [comment]
@teverett We need a build of this PR. Ty.

**Comment by teverett** [comment]
@niu2x thanks!

**Pull request merged**
