### PR TITLE
TS grammer - Add module as reserverd and fix 'propertyMemberBase' order

### PR DESCRIPTION
**Pull request by ariel-levy**
- expressions of the sort of `module.export...` broke the parsing
- `'public' modifier must precede 'async' modifier.ts(1029)`

### CODE REVIEW

**Comment by teverett** [comment]
@KvanTTT good to merge?

**Review by KvanTTT — APPROVED** [review]

**Comment by KvanTTT** [comment]
Yes, it's ok.

**Comment by ariel-levy** [comment]
@KvanTTT generally - are multiple small PRs spammy for you? if it's preferable I can accumulate them to 1 PR
(I'm working on something using this grammer and every now and then I get a parsing error that hints a grammer error)

**Comment by KvanTTT** [comment]
Hi! Not spammy at all. Multiple requests are easier for review than a big one.

**Pull request merged**
