### PR TITLE
[java20] Remove target-specific action code and add java8 Character code check in java20

### PR DESCRIPTION
**Pull request by yamin8000**
I have to admit I'm not fluent in Python and ported this from Java and C#. I think `toCodePoint` method is wrong, however, somehow Parser and Lexer are compiled and work.

### CODE REVIEW

**Comment by kaby76** [comment]
This PR needs a couple of fixes.
* There is no such thing as a "Python" target. There is a "Python3" target. There was a "Python2" target until I removed that in Antlr 4.13.1 and from the tester in this repo.
    * Rename the directory ["Python/"](https://github.com/yamin8000/grammars-v4/tree/43908261e9dc2708866994fbd8e25e5b08841c35/java/java20/Python) to "Python3/".
* The desc.xml has not been updated. It still lists ["CSharp;Cpp;Dart;Java"](https://github.com/yamin8000/grammars-v4/blob/43908261e9dc2708866994fbd8e25e5b08841c35/java/java20/desc.xml#L3) as the functioning targets for the grammar.
    * Add ";Python3" to the end of the list in the desc.xml so that it can be tested.

[All the `Character` code checks were added by Parr over 10 years ago with the initial version of java.g4.](https://github.com/antlr/grammars-v4/commit/2b7f8e12f247486d09c592f058c95ca4bc61d3da) This code is supposed to compute the sets of valid characters for Java identifiers, following the Java Language Spec as closely as possible.

Unfortunately, the Java Language Spec defines the characters that make up a Java identifier operationally using `Character`. The problem with that is that if one wants to write a parser for Java in another language, one will need to precompute the sets. I told the Java Language Spec committee this, and they just blew me off.

The "java7" grammar Parr replaced with the initial version of java/ did represent the sets statically, but I think the rule is wrong. The only grammar that does it correctly is java8. There is a program to compute the Unicode sets from the Character API. https://github.com/antlr/grammars-v4/blob/master/java/java8/Java/CodepointRangeScanner.java In theory, that program should be applied to each version of Java, and the rules for identifiers for a specific version of Java tweaked accordingly. But, it's probably safe to just copy [those rules from java8](https://github.com/antlr/grammars-v4/blob/master/java/java8/Java8Lexer.g4#L304-L960) to java20 (and java9). Then, all the target specific code removed.

Could you make the change to java20? We'll deal with the java/ and java9 grammars separately.

**Comment by yamin8000** [comment]
> This PR needs a couple of fixes.
> 
>     * There is no such thing as a "Python" target. There is a "Python3" target. There was a "Python2" target until I removed that in Antlr 4.13.1 and from the tester in this repo.
>       
>       * Rename the directory ["Python/"](https://github.com/yamin8000/grammars-v4/tree/43908261e9dc2708866994fbd8e25e5b08841c35/java/java20/Python) to "Python3/".
> 
>     * The desc.xml has not been updated. It still lists ["CSharp;Cpp;Dart;Java"](https://github.com/yamin8000/grammars-v4/blob/43908261e9dc2708866994fbd8e25e5b08841c35/java/java20/desc.xml#L3) as the functioning targets for the grammar.
>       
>       * Add ";Python3" to the end of the list in the desc.xml so that it can be tested.
> 
> 
> [All the `Character` code checks were added by Parr over 10 years ago with the initial version of java.g4.](https://github.com/antlr/grammars-v4/commit/2b7f8e12f247486d09c592f058c95ca4bc61d3da) This code is supposed to compute the sets of valid characters for Java identifiers, following the Java Language Spec as closely as possible.
> 
> Unfortunately, the Java Language Spec defines the characters that make up a Java identifier operationally using `Character`. The problem with that is that if one wants to write a parser for Java in another language, one will need to precompute the sets. I told the Java Language Spec committee this, and they just blew me off.
> 
> The "java7" grammar Parr replaced with the initial version of java/ did represent the sets statically, but I think the rule is wrong. The only grammar that does it correctly is java8. There is a program to compute the Unicode sets from the Character API. https://github.com/antlr/grammars-v4/blob/master/java/java8/Java/CodepointRangeScanner.java In theory, that program should be applied to each version of Java, and the rules for identifiers for a specific version of Java tweaked accordingly. But, it's probably safe to just copy [those rules from java8](https://github.com/antlr/grammars-v4/blob/master/java/java8/Java8Lexer.g4#L304-L960) to java20 (and java9). Then, all the target specific code removed.
> 
> Could you make the change to java20? We'll deal with the java/ and java9 grammars separately.

I can make those couple of changes/fixes but I'm not sure I fully understood the remainder of your comment or what should I do about it in this PR.

**Comment by kaby76** [comment]
My whole point is that we don't need target specific code!

1. Please remove https://github.com/antlr/grammars-v4/tree/master/java/java20/CSharp
2. Please remove https://github.com/antlr/grammars-v4/tree/master/java/java20/Cpp 
3. Please remove https://github.com/antlr/grammars-v4/tree/master/java/java20/Dart
4. https://github.com/antlr/grammars-v4/tree/master/java/java20/Java
5. Change desc.xml targets to `<targets>CSharp;Cpp;Dart;Go;Java;JavaScript;Python3;TypeScript</targets>`.
6. Replace these lines in Java20Lexer.g4 https://github.com/antlr/grammars-v4/blob/b3c6ab3b7d91f87c37ba48d82764007d0d3b9501/java/java20/Java20Lexer.g4#L284-L300 with these lines of grammar from java8: https://github.com/antlr/grammars-v4/blob/b3c6ab3b7d91f87c37ba48d82764007d0d3b9501/java/java8/Java8Lexer.g4#L304-L960

With your change, there should not be any calls to `Character`, nor any actions `{...}?`.

We do not need any target-specific code, Python3, CSharp, Cpp, Java, etc. With this change, the grammar will parse java code in lab.antlr.org, VSCode, Intellij, etc.

**Comment by yamin8000** [comment]
> My whole point is that we don't need target specific code!
> 
>     1. Please remove https://github.com/antlr/grammars-v4/tree/master/java/java20/CSharp
> 
>     2. Please remove https://github.com/antlr/grammars-v4/tree/master/java/java20/Cpp
> 
>     3. Please remove https://github.com/antlr/grammars-v4/tree/master/java/java20/Dart
> 
>     4. Please remove https://github.com/antlr/grammars-v4/tree/master/java/java20/Java
> 
>     5. Change desc.xml targets to `<targets>CSharp;Cpp;Dart;Go;Java;JavaScript;Python3;TypeScript</targets>`.
> 
>     6. Replace these lines in Java20Lexer.g4 https://github.com/antlr/grammars-v4/blob/b3c6ab3b7d91f87c37ba48d82764007d0d3b9501/java/java20/Java20Lexer.g4#L284-L300
>         with these lines of grammar from java8: https://github.com/antlr/grammars-v4/blob/b3c6ab3b7d91f87c37ba48d82764007d0d3b9501/java/java8/Java8Lexer.g4#L304-L960
> 
>     7. Change the title of this PR to something like "[java20] Remove target-specific action code".
> 
> 
> With these changes, there won't be any calls to `Character`, `toCodePoint`. There won't be any actions `{...}?` in the grammar left. With this change, the grammar will parse java code in lab.antlr.org, VSCode, Intellij, etc.

Right.
I removed the Python3 directory too and applied the changes that you suggested.

**Review by kaby76 — APPROVED** [review]

**Comment by kaby76** [comment]
```
Error: /Users/runner/work/grammars-v4/grammars-v4/java/java20/Generated-CSharp/obj/Debug/net7.0/Java20Lexer.cs(32,36): error CS0246: The type or namespace name 'JavaLexerBase' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/grammars-v4/grammars-v4/java/java20/Generated-CSharp/Test.csproj]
```
Looks like I forgot to mention to remove the to delete the `options { superclass ... }` lines, too.

https://github.com/yamin8000/grammars-v4/blob/0a782a9d1873355f6c7914c8792d7b6a706aa7c9/java/java20/Java20Lexer.g4#L7-L10

The couple of comments afterwards should also go.

https://github.com/yamin8000/grammars-v4/blob/0a782a9d1873355f6c7914c8792d7b6a706aa7c9/java/java20/Java20Lexer.g4#L12-L14

**Comment by yamin8000** [comment]
> ```
> Error: /Users/runner/work/grammars-v4/grammars-v4/java/java20/Generated-CSharp/obj/Debug/net7.0/Java20Lexer.cs(32,36): error CS0246: The type or namespace name 'JavaLexerBase' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/grammars-v4/grammars-v4/java/java20/Generated-CSharp/Test.csproj]
> ```
> 
> Looks like I forgot to mention to delete the `options { superclass ... }` lines, too, since there now is now base class for the lexer needed.
> 
> https://github.com/yamin8000/grammars-v4/blob/0a782a9d1873355f6c7914c8792d7b6a706aa7c9/java/java20/Java20Lexer.g4#L7-L10
> 
> The couple of comments afterwards should also go.
> 
> https://github.com/yamin8000/grammars-v4/blob/0a782a9d1873355f6c7914c8792d7b6a706aa7c9/java/java20/Java20Lexer.g4#L12-L14

I fixed that too.

**Comment by kaby76** [comment]
Looks good except for one problem:
```
ken@DESKTOP-DL44R7B:~/g4-3870/java/java20$ bash ../../_scripts/test.sh
Adding java/java20
Number of grammars before sorting and making unique: 1
Number of grammars after sorting and making unique: 1
Grammars to do are: java/java20
grammars = java/java20
targets = CSharp Cpp Dart Go Java JavaScript PHP Python3 TypeScript
order = grammars
filter = all
Tests now java/java20,CSharp java/java20,Cpp java/java20,Dart java/java20,Go java/java20,Java java/java20,JavaScript java/java20,PHP java/java20,Python3 java/java20,TypeScript

java/java20,CSharp:
 Build 00:00:10
 Test 00:00:07
 Succeeded.

java/java20,Cpp:
 Build 00:00:19
 Test 00:00:06
 Succeeded.

java/java20,Dart:
 Build 00:00:13
 Test 00:00:06
 Succeeded.

java/java20,Go:

========
Build of java/java20 for Go failed.
Downloading antlr4-4.13.0-complete.jar
# example.com/myparser/parser
parser/java20_parser.go:28754:6: NewEmptyStatementContext redeclared in this block
        parser/java20_parser.go:27892:6: other declaration of NewEmptyStatementContext
parser/java20_parser.go:28792:13: cannot use NewEmptyStatementContext(p, p.GetParserRuleContext(), p.GetState()) (value of type *StatementContext) as type IEmptyStatementContext in assignment:
        *StatementContext does not implement IEmptyStatementContext (missing IsEmptyStatementContext method)
parser/java20_parser.go:28792:38: too many arguments in call to NewEmptyStatementContext
        have (*Java20Parser, antlr.ParserRuleContext, int)
        want ()
note: module requires Go 1.20
========

java/java20,Java:
 Build 00:00:05
 Test 00:00:06
 Succeeded.

java/java20,JavaScript:
 Build 00:00:04
 Test 00:00:15
 Succeeded.

java/java20,PHP:
Intentionally skipping grammar java/java20 target PHP.

java/java20,Python3:
 Build 00:00:04
 Test 00:00:31
 Succeeded.

java/java20,TypeScript:
 Build 00:00:11
 Test 00:00:15
 Succeeded.
ken@DESKTOP-DL44R7B:~/g4-3870/java/java20$
```
There is a "symbol conflict" in the grammar for the Go target. Please rename `emptyStatement` in the grammar by add an underscore `'_'` to the name `emptyStatement` like it is done in the java9/ grammar:

https://github.com/antlr/grammars-v4/blob/5660ba571209e7c28c0e36c38414729e5b6db087/java/java9/Java9Parser.g4#L813
https://github.com/antlr/grammars-v4/blob/5660ba571209e7c28c0e36c38414729e5b6db087/java/java9/Java9Parser.g4#L826

There are two places in the grammar to change.

https://github.com/yamin8000/grammars-v4/blob/358ce481a849ec09ea0f903d32a6f52ec55d0f6e/java/java20/Java20Parser.g4#L855
https://github.com/yamin8000/grammars-v4/blob/358ce481a849ec09ea0f903d32a6f52ec55d0f6e/java/java20/Java20Parser.g4#L872

**Comment by yamin8000** [comment]
There's still [a problem](https://github.com/antlr/grammars-v4/actions/runs/7113828646/job/19383666218?pr=3870#step:24:64) with Go target.
```
Error: .\Test.go:194:23: parser.Start undefined (type *parser.Java20Parser has no field or method Start)
```

**Comment by kaby76** [comment]
I have a different version of Go than the one in Github Actions. "start" for a parser rule name doesn't work with Go. It should be renamed to "start_". Make sure to also update the pom.xml file to have `<entryPoint>start_</entryPoint>`. Promise, that should be it.

**Comment by teverett** [comment]
@yamin8000  @kaby76  ok to pull this?

**Comment by yamin8000** [comment]
> @yamin8000  @kaby76  ok to pull this?

Yeah. As far as I know it was done.

**Pull request merged**
