### PR TITLE
Rfc822

### PR DESCRIPTION
**Pull request by teverett**

### CODE REVIEW

**Comment by parrt** [comment]
date time would be great to have a separate grammar. could we break apart? dates are really useful.

**Comment by teverett** [comment]
Current that is what this is; DateTime. If I add more of the RFC, I am happy to break it apart at that time.

**Comment by parrt** [comment]
Maybe we could call it datetime.g4 then? ;)

**Comment by parrt** [comment]
nobody will find anything as Rfc822

**Comment by teverett** [comment]
done

**Comment by parrt** [comment]
awesome. what is khubla.com by the way?

**Pull request merged**
