### PR TITLE
add jsx base java files

### PR DESCRIPTION
**Pull request by cyw3**

### CODE REVIEW

**Comment by cyw3** [comment]
1. add SpreadExpr for htmltag
example:
```js
<FormattedMessage {...messages.editText}/>
```

2. bugfix: '-' is recognized as MINUS and TagName is splited by '-'.
example:
```js
<ul data-object-type="{$objectType}"/>
```

**Comment by teverett** [comment]
@cyw3  ready to pull this?

**Comment by cyw3** [comment]
ready

**Comment by teverett** [comment]
@cyw3 thanks!

**Pull request merged**
