### PR TITLE
Update CPP14.g4

### PR DESCRIPTION
**Pull request by Hyunsu-Lee**
change for using on python script

### CODE REVIEW

**Comment by Marti2203** [comment]
I suggest making two different grammars and changing the selected tests as from what I understand this is ran in java. @teverett @KvanTTT  know better than me.

**Comment by studentmain** [comment]
Split runtime related code to a base class (see javascript grammar), that's the best practice for support multiple runtime.

**Comment by teverett** [comment]
@Hyunsu-Lee please resolve the merge conflicts on this PR.  thank-you.

**Comment by teverett** [comment]
@Hyunsu-Lee This PR has not been looked at since February and will therefore be closed.

**Pull request closed without merging**
