### PR TITLE
Remove _grammar-test

### PR DESCRIPTION
**Pull request by kaby76**
This PR is for https://github.com/antlr/grammars-v4/issues/2818, where we are removing the _grammar-test directory in order to simplify the maintenance. Please see the issue for further details.

### CODE REVIEW

**Comment by teverett** [comment]
Hey @kaby76 before we pull this PR, should we consider a new repo inside Antlr to preserve this?

**Comment by kaby76** [comment]
Perhaps. What would we call this repo? Would we fork inmemantlr and place that under github.com/antlr, the same way ant4test-maven-plugin exists?

**Comment by KvanTTT** [comment]
Let's just accept the PR and remove outdated dependencies that actually aren't supported.

**Comment by teverett** [comment]
@kaby76 that was somewhat the direction i was going.  I am looking at it from the perspective that someone invested time to build out the code and contributed it.  It makes sense for us to remove it from the current repo, however it would be kind to preserve it for the original author, if they ever wanted to return to it.

**Comment by kaby76** [comment]
Ok let's think about this.

**Comment by kaby76** [comment]
If we want to be nice, we should contact the folks who had written or modified this code and ask them what they want to do. Will they maintain this code? Or, can we pitch it? I honestly don't have the energy to maintain _grammar-test. We have two other ways of testing the Java target for these grammars, one I already maintain--trgen--and they both test everything in the examples/ directories, work on 4.11.1, test all grammars with pom's, both in the CI builds, etc.

**Comment by kaby76** [comment]
```
		<profile>
			<id>test</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<modules>
				<module>_grammar-test</module>
			</modules>
		</profile>
```
Actually, the directory `_grammar-test` is listed in the pom.xml, [but not "active"](https://github.com/antlr/grammars-v4/blob/553522db0536ca80e0535351a19bdd8cbcc14e77/pom.xml#L412). Not sure what that means, but it pointed out a bug in [trgen](https://github.com/kaby76/Domemtech.Trash/tree/main/src/trgen), where it would read all "//modules/module" in the root pom.xml, and [proceed to "cd" to there](https://github.com/kaby76/Domemtech.Trash/blob/2115f562beed2cffc9e9f6e8c3c843f8991b5381/src/trgen/Command.cs#L189)--just that it can't if the directory is gone.

**Comment by teverett** [comment]
@parrt could you perhaps make a _grammar_test repo and give me permissions?  I'll do the work to copy the code over.

**Comment by kaby76** [comment]
I think while we are at it, we might want to consider tools for testing and building.

I have [Antlr4BuildTasks](https://github.com/kaby76/Antlr4BuildTasks), which is a great tool for C# builds containing Antlr4 standard grammars. It is a direct substitute for [Antlr4.CodeGenerator](https://www.nuget.org/packages/Antlr4.CodeGenerator/), which contains a version of Antlr4BuildTasks for "Antlr4cs" grammars. I've spent years cleaning out the bugs, and now it works pretty well.

**Comment by KvanTTT** [comment]
> I am looking at it from the perspective that someone invested time to build out the code and contributed it. It makes sense for us to remove it from the current repo, however it would be kind to preserve it for the original author, if they ever wanted to return to it.

Contributions are welcome, but sometimes some things are being outdated and it's not ok to keep them alive only because of somebody invested time some time ago. If necessary, it will be possible to restore removed files from Git history.

> @parrt could you perhaps make a _grammar_test repo and give me permissions? I'll do the work to copy the code over.

I'm not sure such a repo has a lot of sense. Nobody will take care of it. It will be just a new died repository.

**Comment by teverett** [comment]
ok, I've made a local copy of the _grammar-test dir and will commit it to a repo.  I agree with @KvanTTT  that it may end up being a dead repo, however there are other repos kept for archival purposes.   @kaby76 I'm ok with deleting _grammar-test from this repo.

**Comment by kaby76** [comment]
Ok, I'll clean out the remnants of _grammar-test.

**Comment by parrt** [comment]
hi guys. My quick read of this thread is that I don't need to create the repository and you folks have resolved the issue. :)

**Comment by kaby76** [comment]
Closing this PR, and redoing from it scratch with a clean clone/branch create. I cannot get git/github rebasing/synching to work. I have never ever gotten it to do what rebasing doc says what it does. https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase https://git-scm.com/docs/git-rebase

**Comment by KvanTTT** [comment]
What IDE do you use? Probably it makes sense to demonstrate how to manage git easily (git interactive rebase, squash and other commands) in our upcoming video meeting.

**Comment by kaby76** [comment]
Of the dozen or so times I've tried to do "rebasing", this time I decided to do the "rebasing" from Github. After deleting the commits (Github offered to do that on my forked grammars-v4 repo), I used raw git to do a fresh clone, commit and push from the command line on my machine. I think Github just deleted the commits, but did not actually reposition the branch.

**Comment by KvanTTT** [comment]
By the way, I don't like this idea not only because it's outdated and unlikely it will be maintained by anyone but also because there is a lot of duplication. Sorry for my straight English, the code has poor quality.

**Comment by parrt** [comment]
You don't like the idea of this grammar repository or the historical repo I just created? Which code has poor quality? I guess you mean all of the similar test files.  Well, given that they are already built, I'm guessing it's easiest just to leave it. It would also require work to clean up, but it's up to @teverett what he wants to do

**Comment by KvanTTT** [comment]
I mean the code in newly created [_grammar-test](https://github.com/antlr/_grammar-test). I don't see a lot of value in this code even in historical perspective, but it's up to you. Just described my thoughts.

**Pull request closed without merging**
