### PR TITLE
Every script in examples-sql-script directory runs OK.

### PR DESCRIPTION
**Pull request by aniskop**
Implemented:

- sql*plus start command (sta and @@)
- basic drop table statement
- basic create table statement

This makes every script inside examples-sql-script directory parse with no errors.

### CODE REVIEW

**Comment by aniskop** [comment]
PL/SQL grammar after my fixes gives "no errors found, but errors file exists" message during build:

> Failed to execute goal com.khubla.antlr:antlr4test-maven-plugin:1.8:test (test-examples-sql-script) on project plsql: Unable execute mojo: no errors found, but errors file exists /home/travis/build/antlr/grammars-v4/plsql/examples-sql-script/plsql-packages/green_run.sql.errors

Just need to delete all *.errors files and rerun the build. I saw that error when building with Maven on my machine.

**Comment by teverett** [comment]
@aniskop 

This is the current build error:

com.khubla.antlr.antlr4test.AssertErrorsException: no errors found, but errors file exists /home/travis/build/antlr/grammars-v4/plsql/examples-sql-script/plsql-packages/green_run.sql.errors

please remove the file "plsql-packages/green_run.sql.errors" and re-submit the pull request

**Comment by aniskop** [comment]
Removed all .errors files. It's strange they were in main branch.

**Comment by teverett** [comment]
@aniskop please fix the merge conflict.

**Comment by aniskop** [comment]
Yes, doing it right now. I'm new to GitHub and git (but not to PL/SQL), so this will take a little bit time for me. Will try to solve it today. Thanks for your patience.

**Comment by teverett** [comment]
@aniskop plenty of time.

**Comment by KvanTTT** [comment]
And please leave alone MySql parser :)

**Comment by teverett** [comment]
```
[INFO] --- antlr4test-maven-plugin:1.9:test (default) @ mysql ---
java.lang.ClassNotFoundException: MySqlLexer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	
```

**Comment by teverett** [comment]
@aniskop congrats, and thanks for your persistence in getting this to a pull-able state.

**Pull request merged**
