### PR TITLE
MariaDB grammar

### PR DESCRIPTION
**Pull request by uurl**
This PR adds specific grammar for MariaDB.
MySQL grammar is a subset of MariaDB grammar.

To give an example, these instructions work just in MariaDB but not in MySQL

- ALTER TABLE customers ADD COLUMN *IF NOT EXISTS* column_a INT;
- CREATE *OR REPLACE* TABLE `t_table`
- ... DEFINER = *CURRENT_ROLE*{}
- ... IDENTIFIED *VIA*

### CODE REVIEW

**Review by KvanTTT — CHANGES_REQUESTED** [review]
Please move out chages not related to MariaDB grammar (changes related to MySql grammar).

**Comment by uurl** [comment]
Ready @KvanTTT , just changes related to MariaDB

**Comment by KvanTTT** [comment]
Unfortunately, there are a lot of errors related to MariaDB on CI. Please fix them.

**Comment by uurl** [comment]
Ready @KvanTTT

**Comment by KvanTTT** [comment]
Thanks!

**Review by KvanTTT — APPROVED** [review]

**Pull request merged**
