### PR TITLE
plsql: add row limiting clause support to SELECT [12c]

### PR DESCRIPTION
**Pull request by luyseyal**
Support row limiting clauses like:
```
SELECT *
FROM green_table
OFFSET 1 ROW
FETCH FIRST 1 ROWS ONLY
```

FYI, @MilesPerrySEU

### CODE REVIEW

**Comment by luyseyal** [comment]
@KvanTTT Do I need to add the uncommented keywords into the regular_id definition?

**Comment by KvanTTT** [comment]
@madams51703 please take a look at this PR.

**Comment by madams51703** [comment]
@KvanTTT 
I verified the
 SELECT *
FROM green_table
OFFSET 1 ROW
FETCH FIRST 1 ROWS ONLY
query works at livesql.oracle.com ( did that since I can't find the syntax diagram in Oracle's documentation.)

so I am good with it.  I just can't find the syntax diagram.

@luyseyal Can you add the url where the syntax diagram is at just so we know where the syntax diagram is defined?  This new addition just taught me something cool about the language.

**Comment by luyseyal** [comment]
@madams51703 
https://docs.oracle.com/database/121/SQLRF/statements_10002.htm#BABBADDD

**Comment by luyseyal** [comment]
I tried to handle some of the logical options (like, you can't use it with a `FOR UPDATE`) but the code was super ugly and redundant so I gave up.

**Comment by KvanTTT** [comment]
Could you resolve conflicts, please?

**Comment by luyseyal** [comment]
@KvanTTT Done

**Pull request merged**
