### PR TITLE
Add support for theories and logic

### PR DESCRIPTION
**Pull request by i-walker**
Currently, the specs for smtlib do not parse theories and logics in smt this PR adds that feature and runs the tests through GitHub actions. 
I can remove the Github action part from this PR if it does not comply with the maintainers :) 
I also added tests.

### CODE REVIEW

**Comment by i-walker** [comment]
Happy to add anything missing from Travis CI.

**Comment by teverett** [comment]
@i-walker  thanks!

**Comment by teverett** [comment]
@i-walker  can we fix this?

Screen Shot 2020-05-10 at 6 46 48 AM

**Comment by i-walker** [comment]
This might help, but that has to be configured by someone with permissions https://github.com/gitextensions/gitextensions/issues/4916#issuecomment-557509451

**Comment by teverett** [comment]
@i-walker it seems like moving to github actions is a good idea.  Can we remove it for now however, until some of us get up to speed?

**Comment by i-walker** [comment]
For sure should I create a PR or do you got that covered :)

**Comment by teverett** [comment]
@i-walker  I prefer you make the PR since you know what you did.  I'll keep this commit # so I can go back I learn from what you did.

**Comment by i-walker** [comment]
Yes for sure. I'll set up an PR :)

**Comment by teverett** [comment]
Thanks

**Pull request merged**
