### PR TITLE
[Dart2] Fix for Issue 2597

### PR DESCRIPTION
**Pull request by kaby76**
This pull request replaces the [dart2](https://github.com/antlr/grammars-v4/blob/9313307286717cb34f2ff01a3864212f6b853877/dart2/Dart2.g4) grammar with one that is from the [Dart Language Specification](https://github.com/dart-lang/language/blob/master/specification/dartLangSpec.tex), scraped and refactored via script , fixing #2597, #1939 and other problems.

The Dart Language Specification is written in Latex. It is a work-in-progress that currently describes the language approximately version 2.15. The Spec is always playing "catch up",  apparently two years behind the current Dart release. Nevertheless, the CFG contained in it is good enough to parse all the Dart SDK runtime--with a few adjustments that I made.

Most of the changes in the pull request are for the 300+ files of Dart source code from the [Dart SDK](https://github.com/dart-lang/sdk/tree/main/sdk/lib) that I am adding as a regression test suite. The other files are the Dart2 grammar files, a new pom.xml for the split grammar, and the lexer base classes for Java and C#. It is a split grammar because there are semantic predicates in lexer rules. Although 300+ files is a large test suite, it runs very quickly--most tests are 1/2 second or less. I've added the try-dart examples, and a test of operator from the description in #2597. Everything parses.

The grammar is itself written "one rule per line", with the parser rules ordered alphabetically. I prefer this ordering, instead of another, because I can find rules very quickly within a plain text editor or printout. As for the actual changes to the grammar, see the [readme](https://github.com/kaby76/ScrapeDartSpec#readme) for the scraping project.

This grammar is good enough to parse most Dart. My plan is to use the current Dart2 grammar as a bootstrap to scrape the CFG from the
[compiler source](https://github.com/dart-lang/sdk/tree/main/pkg/_fe_analyzer_shared/lib/src/parser)
itself rather than the Spec.

Note: While the Dart Language Team has written [their own Antlr grammar](https://github.com/dart-lang/sdk/blob/main/tools/spec_parser/Dart.g), it parses only half the Dart SDK.

### CODE REVIEW

**Comment by kaby76** [comment]
Very strange, because I tested this just before checkin.
```
$ mvn clean test
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.antlr.grammars:Dart2 >----------------------
[INFO] Building Dart2 grammar 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Dart2 ---
[INFO]
[INFO] --- build-helper-maven-plugin:3.3.0:add-source (add-source) @ Dart2 ---
[INFO] Source directory: C:\msys64\home\Kenne\g-current\issue-2597\dart2\Java added.
[INFO]
[INFO] --- antlr4-maven-plugin:4.10.1:antlr4 (default) @ Dart2 ---
[INFO] ANTLR 4: Processing source directory C:\msys64\home\Kenne\g-current\issue-2597\dart2
[INFO] Processing grammar: Dart2Lexer.g4
[INFO] Processing grammar: Dart2Parser.g4
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Dart2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\msys64\home\Kenne\g-current\issue-2597\dart2\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ Dart2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to C:\msys64\home\Kenne\g-current\issue-2597\dart2\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Dart2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\msys64\home\Kenne\g-current\issue-2597\dart2\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ Dart2 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ Dart2 ---
[INFO] No tests to run.
[INFO]
[INFO] --- antlr4test-maven-plugin:1.21:test (default) @ Dart2 ---
[INFO] Evaluating Scenario: Default Scenario
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\collections.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\escaped_backslash.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\escaped_string.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\escape_sequences.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\regex.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\regex2.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\regex3.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\sdk\sdk\lib\async\async.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\sdk\sdk\lib\async\async_error.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\sdk\sdk\lib\async\broadcast_stream_controller.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\sdk\sdk\lib\async\deferred_load.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\sdk\sdk\lib\async\future.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\sdk\sdk\lib\async\future_impl.dart
[INFO] Parsing :C:\msys64\home\Kenne\g-current\issue-2597\dart2\examples\sdk\sdk\lib\async\schedule_microtask.dart
```

**Comment by kaby76** [comment]
Yep, can't work without committing the grammar files!

**Comment by kaby76** [comment]
```
2022-06-14T02:11:29.3750730Z ---------- Testing grammar ./rfc822/rfc822-datetime ----------
2022-06-14T02:11:29.3829220Z Building
2022-06-14T02:11:29.3832060Z trgen --antlr-tool-path /Users/runner/work/grammars-v4/grammars-v4/antlr4-4.10-complete.jar -t Go --template-sources-directory /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/
2022-06-14T02:11:29.7646330Z /Users/runner/work/grammars-v4/grammars-v4/rfc822/rfc822-datetime/
2022-06-14T02:11:30.2033390Z Prefix to remove /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/
2022-06-14T02:11:30.2034410Z Rendering template file from /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/Go/test.sh to Generated/test.sh
2022-06-14T02:11:30.2773340Z Rendering template file from /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/Go/tester.psm1 to Generated/tester.psm1
2022-06-14T02:11:30.3230890Z Rendering template file from /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/Go/Test.go to Generated/Test.go
2022-06-14T02:11:30.3315880Z Rendering template file from /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/Go/makefile to Generated/makefile
2022-06-14T02:11:30.3333720Z Rendering template file from /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/Go/go.mod to Generated/go.mod
2022-06-14T02:11:30.3344120Z Rendering template file from /Users/runner/work/grammars-v4/grammars-v4/_scripts/templates/Go/antlr_resource/case_changing_stream.go to Generated/antlr_resource/case_changing_stream.go
2022-06-14T02:11:30.3362920Z Copying source file from /Users/runner/work/grammars-v4/grammars-v4/rfc822/rfc822-datetime/datetime.g4 to Generated/parser/datetime.g4
2022-06-14T02:11:30.3372030Z Copying source file from /Users/runner/work/grammars-v4/grammars-v4/rfc822/rfc822-datetime/pom.xml to Generated/pom.xml
2022-06-14T02:11:32.6528960Z go: added github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20220411172017-c7567ba9bb40
2022-06-14T02:11:32.8080500Z ##[error]Test.go:10:5: read /Users/runner/work/grammars-v4/grammars-v4/rfc822/rfc822-datetime/Generated/parser/datetime_parser.go: unexpected NUL in input
2022-06-14T02:11:32.8093070Z Build failed
```
Unclear why Antlr Tool 4.19.1 is producing a "NUL" character in the generated file datetime_parser.go.

**Comment by kaby76** [comment]
Something is royally messed up with the Github boxes. Many connection errors, resulting in build crashes.

**Comment by teverett** [comment]
@kaby76  thanks

**Comment by KvanTTT** [comment]
@kaby76 please fix [`linguist-vendored`](https://github.com/antlr/grammars-v4/blob/master/.gitattributes#L93) git attribute to fix detecting repository's languages. Now it's recognized as Dart but should be ANTLR. Also, see documentation here: https://github.com/github/linguist/blob/master/docs/overrides.md

**Pull request merged**
