### PR TITLE
snowflake - PUBLIC as ID

### PR DESCRIPTION
**Pull request by mlorek**

### CODE REVIEW

**Comment by michael-the1** [comment]
I literally just removed it https://github.com/antlr/grammars-v4/pull/3099. It's not a keyword, right? And it should work with your examples regardless.

**Comment by teverett** [comment]
@mlorek  @michael-the1  good to merge this?

**Comment by michael-the1** [comment]
@mlorek @teverett The new approach with `non_reserved_keywords` looks pretty good to me! I'll also be sure to test it myself tomorrow.

**Review by michael-the1 — APPROVED** [review]
Looks good to me, thank you so much for all your work @mlorek 🙏

**Comment by mlorek** [comment]
#3105 fixed as well

**Comment by teverett** [comment]
@mlorek  there are merge conflicts

**Pull request closed without merging**
