### PR TITLE
improve dependabot config

### PR DESCRIPTION
**Pull request by studentmain**
- [x] we use `java` for Java grammars, not for any code written in java (e.g. #2507)
- [x] use it to update tester's dependency

question:

- [ ] lower the checking frequency to once per week?

### CODE REVIEW

**Comment by studentmain** [comment]
Looks like dependabot can only rebase it's own pr. I'll rebase it by myself later.

**Comment by teverett** [comment]
@studentmain  All good to pull this?

**Comment by studentmain** [comment]
@kaby76 since you mentioned difficulty of manage multiple runtime version, what's your opinion

**Comment by kaby76** [comment]
> @kaby76 since you mentioned difficulty of manage multiple runtime version, what's your opinion

On this particular issue of when to kick off dependabots, I have no opinion because I'm not sure how they work. Whatever you think best.

As far as the upgrade to 4.10, there were a number of places that needed to be modified:
* multiple version strings (for 4.10) for runtimes:
    * [_scripts/templates/Cpp/CMakeLists.txt](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/templates/Cpp/CMakeLists.txt#L9)
    * [_scripts/templates/CSharp/Test.csproj](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/templates/CSharp/Test.csproj#L14)
    * [_scripts/templates/Dart/pubspec.yaml](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/templates/Dart/pubspec.yaml#L7)
    * [_scripts/templates/Go/makefile](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/templates/Go/makefile#L14)
    * [_scripts/templates/JavaScript/package.json](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/templates/JavaScript/package.json#L12)
    * [_scripts/templates/PHP/composer.json](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/templates/PHP/composer.json#L3)
    * [_scripts/templates/Python3/requirements](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/templates/Python3/requirements.txt#L1)
* Multiple strings for tool (for 4.10):
    * [.github/workflows/main.yml](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/.github/workflows/main.yml#L124)
    * [pom.xml](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/pom.xml#L13)
    * [_scripts/regtest.sh](https://github.com/antlr/grammars-v4/blob/2da9920bb4893ec3848692f3d8a080f3a7643ffd/_scripts/regtest.sh#L173)
* Target language version requires (implicitly set up in main.yml).

**Comment by studentmain** [comment]
> @studentmain All good to pull this?

Yes

manual operation is still required, but this at least automated more version string

**Pull request merged**
