### PR TITLE
Golang

### PR DESCRIPTION
**Pull request by fred1268**
Split Golang.g4 into GolangLexer.g4 and GolangParser.g4
Delete Golang.g4 since it is no more necessary
Create the BaseLexer and BaseParser in both Java and Go

This should solve issue #1484 that I created few days ago.

### CODE REVIEW

**Comment by KvanTTT** [comment]
We are also working on it: https://github.com/PositiveTechnologies/grammars-v4/tree/GoLangRefactoring/golang It would be great to merge our changes later.

**Comment by KvanTTT** [comment]
@fred1268 what about CI fixes? Unfortunately, we can not merge this PR without them.

**Comment by fred1268** [comment]
Sorry @KvanTTT . Will try to make it happen shortly. Was pretty busy on other topics.

**Comment by KvanTTT** [comment]
Ok, take your time.

**Comment by fred1268** [comment]
Hello @KvanTTT . Sorry for the delay, I did not even realize that what you asked for was so quick otherwise I would have taken the time to do it earlier.
I hope this will go in the right direction: now at least we do have lexer and parser separated, and all functions are written in Go in addition to Java, on the same model than JavaScript.
Best,
Fred.

**Comment by KvanTTT** [comment]
Thanks a lot!

**Pull request merged**
