### PR TITLE
Fix for 2114 -- this change is work in progress.

### PR DESCRIPTION
**Pull request by kaby76**
This is a change for #2114. I've updated the main.yml with two changes:
* Check the return code from the download of the Antlr JAR. It's already done for getting the name of the latest JAR, but the call to get the JAR doesn't do the check.
* Add retry count and timeout period to the download calls to get the Antlr JAR.

_NB: This is a partial change. I'll try to adjust other places, but I want to see if this works or not._

### CODE REVIEW

**Comment by kaby76** [comment]
The code now has some checks on the Invoke-WebRequest, but it's not complete. I cannot check the response from a Invoke-WebRequest with the -outfile option: it returns a null or empty string result. I tested the code on my local machine without internet, but that didn't duplicate the problem. I suspect that the link is bad, and the file contents received are bogus, which explains why one of the runs said the Antlr JAR was corrupt. The download code should be change to work against Maven Central, not antlr.org. It should also download a hash check to make sure the JAR downloaded is correct.

**Comment by KvanTTT** [comment]
Please use [drafts](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for incompleted requests or at least `[WIP]` suffix at the beginning of the title.

**Comment by kaby76** [comment]
> Please use [drafts](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for incompleted requests or at least `[WIP]` suffix at the beginning of the title.

I will try. I have been trying to look for drafts mode, but I just don't see the choice in the UI button on the website, and I don't use the Git Desktop app to submit PRs. I wish Github would allow changes to the type of PR, but it doesn't--people don't make mistakes?

**Comment by kaby76** [comment]
Apparently there is UI to change the PR to Draft status:
* In github.com, navigate to the PR.
* Use the Find option in the browser software to find the string "Convert to draft" in the webpage. Click on it hyperlinked text, which functions as a button, but isn't.

**Comment by studentmain** [comment]
> cannot check the response from a Invoke-WebRequest with the -outfile option

try `-passthru` option: `$resp = invoke-webrequest $url -outfile $file -passthru`

**Comment by studentmain** [comment]
> work against Maven Central

I can only find the `.pom` file on Maven Central.

**Comment by kaby76** [comment]
> > work against Maven Central
> 
> I can only find the `.pom` file on Maven Central.

Yep, check out that Easter egg to the right, the "Browse" hyper-linked text. (I could go on and on about hyper-text vs. buttons in a GUI a la "switch a PR state to draft" fiasco.) Anyways, the browser opens a new tab at https://repo1.maven.org/maven2/org/antlr/antlr4/4.9.2/ . I'll have to beef up the Antlr4BuildTasks for C# to grab a check file and verify the contents. I don't know what Nuget.exe/dotnet.exe does for a download package.

**Comment by studentmain** [comment]
> 
> 
> > > work against Maven Central
> > 
> > 
> > I can only find the `.pom` file on Maven Central.
> 
> Yep, check out that Easter egg to the right, the "Browse" hyper-linked text. (I could go on and on about hyper-text vs. buttons in a GUI a la "switch a PR state to draft" fiasco.) Anyways, the browser opens a new tab at https://repo1.maven.org/maven2/org/antlr/antlr4/4.9.2/ . I'll have to beef up the Antlr4BuildTasks for C# to grab a check file and verify the contents. I don't know what Nuget.exe/dotnet.exe does for a download package.

I figured it out, I checked `antlr4-master`, but it's `antlr4`...

**Comment by kaby76** [comment]
I'm not sure about these changes. The build seems to have stabilized.

**Comment by studentmain** [comment]
> I'm not sure about these changes. The build seems to have stabilized.

I'll rewrite the download code to use Maven Central API. A `setup-antlr` action is also possible if someone needs it.

**Comment by kaby76** [comment]
I'm closing the PR and Issue off because the change is no longer needed. Downloading from the Internet has not been a problem, and watchdogging the build is now a separate Issue.

**Pull request closed without merging**
