### PR TITLE
added TypeScript target and some modifications

### PR DESCRIPTION
**Pull request by RobEin**
- added TypeScript target
- update to ANTLR 4.13.2
- update to Python 3.12.6

### CODE REVIEW

**Comment by kaby76** [comment]
`update to ANTLR 4.13.2`. Could you describe which targets require 4.13.2 here? There is no version 4.13.2 for the CSharp target.

**Comment by RobEin** [comment]
The two following two parsers require ANTLR 4.13.2:
 - JavaScript target for Python 3 (because of depricated features: [#4562](https://github.com/antlr/antlr4/pull/4562))
 - TypeScript target for Python 3 (because of new features: [#4562](https://github.com/antlr/antlr4/pull/4562))

**Comment by kaby76** [comment]
Now I understand. The JavaScript port requires Antlr 4.13.2 because this PR uses the API [Lexer.setMode()](https://github.com/antlr/antlr4/blob/2a7904a595479954ccfb1c78124fc3d7f5bebcb1/runtime/JavaScript/src/antlr4/Lexer.js#L180-L182). Unfortunately, the build locks all grammars that have a JavaScript port at 4.13.2.  So, the old API [mode()](https://github.com/antlr/antlr4/blob/2a7904a595479954ccfb1c78124fc3d7f5bebcb1/runtime/JavaScript/src/antlr4/Lexer.js#L175-L178) outputs a deprecation warning, which is a breaking change. I don't think there are many JS ports that use the old API, but I will need add per-grammar, per-version testing when specified in the desc.xml.

**Comment by kaby76** [comment]
Please synch with "master" to see whether the build is fixed.

**Comment by teverett** [comment]
@kaby76  ready to merge?

**Comment by kaby76** [comment]
Yes, please merge.

**Comment by teverett** [comment]
@RobEin  thanks!

**Pull request merged**
