### PR TITLE
Closes #2787

### LINKED ISSUE #2787: vba END_PROPERTY incorrect.
Current value `END_PROPERTY: 'END' WS' PROPERTY';` should be corrected to `END_PROPERTY: 'END' WS 'PROPERTY';`

file: [./vba/vba.g4](https://github.com/antlr/grammars-v4/blob/master/vba/vba.g4)

### PR DESCRIPTION
**Pull request by SSlinky**
Typo in grammar caused `End Property` to not be parsed correctly.

### CODE REVIEW

**Comment by KvanTTT** [comment]
@kaby76 yes, it looks like they appeared in result of my inaccurate refactoring about introducting `caseInsensitive` option.

**Comment by kaby76** [comment]
> @kaby76 yes, it looks like they appeared in result of my inaccurate refactoring about introducting `caseInsensitive` option.

Not a problem. You can't make an omelette without breaking eggs.

**Comment by SSlinky** [comment]
@kaby76 good pick up - corrected that too. I've also added examples to test both, @KvanTTT - hopefully what I have done is what you were after.

**Comment by teverett** [comment]
Good to merge?

**Comment by KvanTTT** [comment]
@SSlinky thank you for the contribution and welcome to ANTLR grammars repository!

**Pull request merged**
