### PR TITLE
[PostgreSQL] Swap order of columnDef and tableconstraint in tableelement rule #3033

### PR DESCRIPTION
**Pull request by paulirwin**
See issue #3033

### CODE REVIEW

**Comment by teverett** [comment]
@KvanTTT  good to merge?

**Comment by paulirwin** [comment]
I've done some more testing with this change and it has been working well. Since `tableconstraint` begins with the lexer rule `CONSTRAINT` and `tablelikeclause` begins with the lexer rule `LIKE`, they are not going to accidentally match on anything that should be a `columnDef` (since `CONSTRAINT` and `LIKE` are not valid column names), allowing other valid column names to pass through to the `columnDef` rule as expected.

**Comment by KvanTTT** [comment]
> I've done some more testing with this change and it has been working well. 

Is it possible to add some testing examples to the `examples` directory?

**Comment by paulirwin** [comment]
@KvanTTT I went to go add an example, and confirmed there already is an example that is parsed incorrectly in `create_table.sql`: 

```sql
CREATE TABLE parted (
	a text,
	b int NOT NULL DEFAULT 0,
	CONSTRAINT check_a CHECK (length(a) > 0)
) PARTITION BY LIST (a);
```

`check_a` gets parsed as a `columnDef` rule (as a column named `CONSTRAINT` of type `check_a`) instead of `tableconstraint`. This is likely a problem with other CONSTRAINT table elements in the example.

Let me know if this is insufficient for demonstrating this bug. Thanks!

**Comment by KvanTTT** [comment]
Ok, it's enough. Thanks for the contribution and welcome to ANTLR grammars repository!

**Pull request merged**
