### PR TITLE
Fix for Issue 2149

### PR DESCRIPTION
**Pull request by kaby76**
This is a fix for #2149, where the antlr/antlr4/ grammar would not parse the apt/ and sql/tsql/ grammars in this repository. The grammar antlr/antlr4/ is used in various tools, including [Trash](https://github.com/kaby76/Domemtech.Trash) and [vscode-antlr4](https://github.com/mike-lischke/vscode-antlr4), so it's important to get this working.

There are a number of issues associated with this issue.

* Why are there two Antlr4 grammars? How do they differ, and why do they differ?
* The tool accepts "options" in _optionsSpec_ and _labeledElement_, but grammars-v4/antlr/antlr4/ does not. Should the apt/ and sql/tsql/ grammars be changed so that `options` is renamed to `options_` in the context of _labeledElement_?
* Should the Antlr4 tool be updated to disallow `options` for _labeledElement_?
* Should a tool be created to examine the grammars during CI to warn not to use "options" as an identifier?

Let's examine these questions.

There are two Antlr4 grammars because the grammar for the Antlr4 tool is an Antlr3 grammar, while the grammar in antlr/antlr4/ is an Antlr4 grammar. Since most tool developers want to use the most up-to-date Antlr, a new grammar was created and placed in this Git repo, which is for Antlr4 grammars (grammars-*v4*). Antlr uses the previous major version of the tool to generate the next version. The Antlr4 tool sources could be rewritten to use Antlr4 in the parser generation, but that would involve "non-maintenance work", which will not happen at this point.

How do the grammars differ? Well, first, the grammar in this Git repo is split into lexer and parser grammars. The Antlr4 Tool grammar is a combined grammar. Beyond that, the rules differ significantly. Note, attached are the two Antlr4 grammars in stripped format from Trash:

    git clone https://github.com/antlr/antlr4.git
    cd antlr4/tool/src/org/antlr/v4/parse
    trparse -f ANTLRParser.g -t antlr3 | trconvert | trstrip | trprint > ~/tool.g4
    git clone https://github.com/antlr/grammars-v4.git
    cd grammars-v4/antlr/antlr4
    trparse -f ANTLRv4Parser.g4 -t antlr4 | trstrip | trprint > ~/grv4.g4
    trparse -f ANTLRv4Lexer.g4 -t antlr4 | trstrip | trprint >> ~/grv4.g4

[tool.txt](https://github.com/antlr/grammars-v4/files/6360746/tool.txt)
[grv4.txt](https://github.com/antlr/grammars-v4/files/6360750/grv4.txt)

The difference related to Issue 2149 are for rules OPTIONS, TOKENS_SPEC, and CHANNELS.

Why do they differ so much? At the time the [Antlr4 version of the grammar was create](https://github.com/antlr/grammars-v4/commit/36c7c5a1768dc21c93729a8a33770e18c6065aa0#diff-d5b3cfafc91b37f567bb42d4e8822fb5c848acea229f79ed463fd2a0cdfe01b2), there was no tool to extract the grammar from source. And, even though the conversion from an Antlr3 to Antlr4 grammar involves deletion of unsupported and unnecessary older features in Antlr4, folks tend to make additional transformations, and of course, do not describe what transformations were made. The Antlr4 grammar in this repo was no exception.

Should apt/ and sql/tsql/ be changed with `options` renamed? Possibly, but there is no need and Antlr v4.9.2 allows it.

Should the Antlr4 tool be changed to disallow `options` as an identifier? Possibly, but Antlr is now in "maintenance" mode ([1851](https://github.com/antlr/antlr4/issues/1851#issuecomment-303477052), [2569](https://github.com/antlr/antlr4/issues/2569#issuecomment-541957194), ...). Even if one were to make the change, the development process is somewhat broken: PRs are not reviewed and integrated in a timely fashion (e.g., [2313](2313), 77 PRs currently in the queue, 500+ open issues). At some point, someone should think about a replacement for Antlr.

Should there be a tool to raise a warning or error if an Antlr keyword is used as an identifier? Maybe but I am not adding that here. It may be best to combine that with a symbol conflict check across targets.

This PR performs the minimal: it alters the antlr/antlr4/ grammar to resembly the Antlr4 tool grammar more closely. The rules for lexer symbols `OPTIONS`, `TOKENS`, and `CHANNELS` all follow the same format: a string literal followed by white space, followed by the open curly brace. Thus, when "options {" is encountered, it is tokenized as `OPTIONS`, but in isolation of the open curly, it is tokenized as a RULE_REF. Three lexer mode rules have been deleted because they are now completely unused. I added the two grammars to antlr/antlr4/examples/ for testing.

--Ken

### CODE REVIEW

**Comment by kaby76** [comment]
@mike-lischke At your convenience, could you review the PR? Thanks!

**Review by mike-lischke — APPROVED** [review]
I like the simplifications. Getting rid of target code and the LexerAdapter class is a good approach. To be honest, I don't even know why lexer modes were used in this grammar, in the first place.

**Comment by mike-lischke** [comment]
And I agree with your conclusions @kaby76. Target code gets merged if the target owner(s) agree. Changes to the ANTLR4 tool itself won't be merged anymore.

**Comment by kaby76** [comment]
@mike-lischke Thanks! -Ken

**Comment by kaby76** [comment]
@KvanTTT or @teverett It's ready to merge. Thanks! -Ken

**Comment by teverett** [comment]
@kaby76 thanks

**Pull request merged**
