### PR TITLE
Fix for #2074. Templates for driver code, updated scripts.

### LINKED ISSUE #2074: [CI] Moving to StringTemplate implementation for testing
This is a note on version 3.0.0 of [dotnet-antlr](https://github.com/kaby76/Antlr4BuildTasks/tree/master/dotnet-antlr). The new version replaces the hard-wired implementations for code tests with templated files. While the tool has a set of built-in templates, the [grammars-v4 repo](https://github.com/antlr/grammars-v4) should get its own set of templates so folks can tune the templates or even add new ones. For example, one set of templates would test parsing regressions; a second could set profiling and print out details of performance hogs; a third could be tuned to perform a warm-up parse before a timed parse; a fourth set could drop the "makefile" build files, and set up for a completely different build tool.

All the templates are in the "per-target directory" standard:
* A template directory contains files that are instantiated in the generated output directory.
* Contained in the template directory are sub-directories named after the target, e.g., CSharp, Java, JavaScript, etc. Those files are copied to the generated output directory, but only for the specified target for dotnet-antlr.

Here is the structure of the default templates:

    templates/
        Antlr4cs/
            Program.cs
            Test.csproj
            makefile
        CSharp/
            ErrorListener.cs
            Program.cs
            Test.csproj
            makefile
        Cpp/
        Dart/
            analysis_options.yaml
            cli.dart
            makefile
            pubspec.yaml
        Go/
            Program.go
            makefile
        Java/
            ErrorListener.java
            Program.java
            makefile
        JavaScript/
            index.js
            makefile
            package.json
        Python3/
            Program.py
            makefile
        files
        Arithmetic.g4
 
Driver code is generated by merging the code containing the grammar and sources in grammars-v4 with the template source code. For example, for `dotnet-antlr -m true -t CSharp` in grammars-v4/abb/, the tool will extract from the pom.xml file details about the grammar, copy the source files from grammars-v4/abb/ to Generated/, then copy the template files from templates/CSharp to Generated/. The end result is:

    Generated/
        abbParser.g4       (from the source abb/abbParser.g4)
        abbLexer.g4       (from the source abb/abbLexer.g4)
        ErrorListener.cs  (from the source templates/CSharp/ErrorListener.cs)
        makefile   (from the source templates/CSharp/makefile)
        Program.cs   (from the source templates/CSharp/Program.cs)
        Test.csproj   (from the source templates/CSharp/Test.csproj)

All files in templates/ are [StringTemplate](https://github.com/antlr/stringtemplate4/blob/master/doc/introduction.md) files. To see how it is used, I suggest looking at the default set of templates for the tool [here](https://github.com/kaby76/Antlr4BuildTasks/tree/master/dotnet-antlr/templates). Look closely for template attribute references, which begin with '<' and end with '>'. (To avoid template attribute replacement, escape '<' with a backslash, e.g., '\<'. You only need to do the '<', not the closing '>' symbol.)

Dotnet-antlr will construct and pass to the template evaluator the following attributes:

| Attribute | Type | Default |
| ----- | ----- | ----- |
| antlr_tool_path | string | Ubuntu: "~/Downloads/antlr-4.9.1-complete.jar" Win: Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) + "/Downloads/antlr-4.9.1-complete.jar" |
| cap_start_symbol | string | same as `start_symbol`, but first letter capitalized |
| cli_bash | bool | Ubuntu: true; Win: false |
| cli_cmd | bool | Ubuntu: false; Win: true |
| has_name_space | bool | only true if the pom.xml has non-empty `<packageName>` specified |
| lexer_name | string | from pom.xml `<grammarName>` + "Lexer" |
| name_space | string | value in pom.xml `<packageName>` |
| parser_name | string | from pom.xml `<grammarName>` + "Parser" |
| path_sep_colon | bool | Ubuntu: true; Win: false |
| path_sep_semi | bool | Ubuntu: false; Win: true |
| start_symbol | string | from pom.xml `<entryPoint>` |
| tool_grammar_files | List<string> | computed; names of grammar files with relative path from output directory |
| tool_grammar_tuples | { string GrammarFileName, string GeneratedFileName, string GrammarAutomName } | computed from `tool_grammar_files`, `parser_name`, `lexer_name`. Example: [{ "abbLexer.g4", "abbLexer.cs", "abbLexer" }, ...] |
| version | string | version number of dotnet-antlr |

The dotnet-antlr version 3 tool works pretty well, but I am still polishing the program and cleaning up problems. When it works well with [_scripts/test.ps1](https://github.com/antlr/grammars-v4/blob/master/_scripts/test.ps1), I will submit a PR to integrate the new tool.

--Ken

### PR DESCRIPTION
**Pull request by kaby76**
This PR fixes #2074. I have written a new version of the CI tool [dotnet-antlr](https://github.com/kaby76/Antlr4BuildTasks/tree/master/dotnet-antlr), which uses [Antlr's StringTemplate API](https://github.com/antlr/stringtemplate4) targeted for C#. The template driver code is now contained in _scripts/templates, which has been added with this PR. A brief explanation for how to use the templates is contained in _scripts/templates/readme.md. (__NB, corrected location _scripts/readme.md.__)

I have updated the CI scripts _scripts/regtest.sh and _scripts/test.ps1. Note, test1.ps1 is possibly broken. E.g., it passes the wrong test case path to the program to parse. I tried to fix it but @studentmain will need to update it further.

For regtest.sh, the Bash script now calls Make for all targets. Every target in templates/ includes a makefile that presents the toolchain for the target in a seamless, consistent manner to the regtest.sh script: (1) to build a program, type "make"; (2) to test a program against the examples/* files, type "make test". You will, of course, need to install the appropriate tools for you environment. The makefile could do this for you, but I don't have it programmed to do that with this version of the templates.

--Ken

### CODE REVIEW

**Comment by kaby76** [comment]
(Sorry, some things are still broken.......)

**Comment by kaby76** [comment]
Still broken. Something different between this system and my desktop ubuntu. Debugging....

**Comment by studentmain** [comment]
> Still broken. Something different between this system and my desktop ubuntu. Debugging.... **(It seems it is working now. The PR is ready.)**

There's no change in grammar folder, so no grammar is included. I'm going to fix problems then add other language tests.

**Comment by teverett** [comment]
@kaby76  thanks

**Pull request merged**
