### PR TITLE
Implement full .errors verification in tests

### LINKED ISSUE #2838: Implement full .errors verification in tests
In [grammars-v4 issue 2821](https://github.com/antlr/grammars-v4/issues/2821), I  wrote:

> I'm experimenting now with making `trgen` verify ... the [`.errors`](https://github.com/RossPatterson/grammars-v4/blob/master/_scripts/templates/Java/test.sh#L16-L32)  reference files, as `antlr4test-maven-plugin` does in [AssertErrorsErrorListener](https://github.com/antlr/antlr4test-maven-plugin/blob/master/src/main/java/com/khubla/antlr/antlr4test/AssertErrorsErrorListener.java#L54-L74) ...  I'm interested in the `.errors` capability because it seems like it should be fully supported.

As I said, I've got an experiment in progress to do this.

### PR DESCRIPTION
**Pull request by RossPatterson**
In [grammars-v4 issue 2821](https://github.com/antlr/grammars-v4/issues/2821), I  wrote:

> I'm experimenting now with making `trgen` verify ... the [`.errors`](https://github.com/RossPatterson/grammars-v4/blob/master/_scripts/templates/Java/test.sh#L16-L32)  reference files, as `antlr4test-maven-plugin` does in [AssertErrorsErrorListener](https://github.com/antlr/antlr4test-maven-plugin/blob/master/src/main/java/com/khubla/antlr/antlr4test/AssertErrorsErrorListener.java#L54-L74) ...  I'm interested in the `.errors` capability because it seems like it should be fully supported.

- All the test drivers (_e.g._, `_scripts/*/Program.*`) have been modified to dump out the detected errors to stdout in the expected format, and to only dump the parse tree if there are no errors.  There are currently no cases of an example that has both a `.errors` file and a `.tree` file, and in my opinion, there is no value in being able to check the parse tree if the parse fails.
- All the test scripts (_i.e._, `_scripts/*/test.sh`, `_scripts/*.tester.psm1`) have been modified to check the detected errors against the reference files, and to only check the parse tree if there are no errors.
- The Java test driver has been modified to dump out the errors in UTF-8.  All the other test drivers already did so.
- I have verified that all the grammars that have ".errors" files in their `examples` directory generate all and only those errors.  There was one exception (see below).
- I have run the Go, Dart, Java, and Python3 test targets for all the grammars they support.  They are all functioning correctly.
- I have run the CSharp test target for all the grammars it supports.  It produces an error mismatch for `csharp` example `issue-2612`, as documented in [`antlr4` issue #3700](https://github.com/antlr/antlr4/issues/3700) by @kaby76 on 2022-05-07.  I have added `csharp` to `_scripts/skip-csharp.txt` and `_scripts/skip-csharp.why` until the issue is fixed.  All other grammars function correctly.
- I do not have the setup to test the Antlr4cs, Cpp, Javascript, and PHP targets, and will rely on the CI checks to test those.  The changes were relatively simple, and barring typos, should work.

Fixes #2838.

### CODE REVIEW

**Comment by RossPatterson** [comment]
- [build-cpp](https://github.com/antlr/grammars-v4/actions/runs/3176743759/jobs/5176389029): Syntax error in `ErrorListener.cpp`.  C++ makes the simplest things weird.  Fixed by commit a24c4a433a9482c62b30615bcbe52d92f0811bf9.
- [build-csharp](https://github.com/antlr/grammars-v4/actions/runs/3176743759/jobs/5176389331), [build-php](https://github.com/antlr/grammars-v4/actions/runs/3176743759/jobs/5176390148): Merge error on all the `test.sh` copies.  Fixed by  905e3f472f42dae2d5cf0bfbaf6fa34697f419b4.
- [build-pwsh (*, JavaScript)](https://github.com/antlr/grammars-v4/actions/runs/3176743759/jobs/5176392003): 
  - python/python3alt: "`SyntaxError: Unexpected strict mode reserved word`".  [Existing error](https://github.com/antlr/grammars-v4/actions/runs/3171329768/jobs/5164665386#step:17:6461), now causing test case failure because it doesn't match expected errors.  Opened issue #2858 and added `python/python3alt` to `_scripts/skip-javascript.txt` and `_scripts/skip-javascript.why` (by commit 6c0578965f97c7a004fe0b6b9febf691dc2f1dfd).
  - antlr/antlr4, cpp, cto, dice, edn, logo/logo, vb6: Not capturing error text to stdout.  Fixed by commit fd65eada14fbf181e0320f48727c8f5b9d77dbb9.
- [build-pwsh (windows-latest, Python3)](https://github.com/antlr/grammars-v4/actions/runs/3176743759/jobs/5176391488): Merge error on Python3 `tester.psm1` copy. Fixed by commit a8e608be56b70d004921dbd94793f2eccaec036a.

**Comment by RossPatterson** [comment]
- [build-php](https://github.com/antlr/grammars-v4/actions/runs/3177687812/jobs/5178406516):
  - logo/logo: Error mismatch in  example [`logo_feature_butfail_2.txt`](https://github.com/antlr/grammars-v4/actions/runs/3177687812/jobs/5178406516#step:8:6670).  This is an [existing error](https://github.com/antlr/grammars-v4/actions/runs/3171329768/jobs/5164663975#step:8:6670), now causing test case failure because it doesn't match expected errors.  I opened #2859 and added `logo/logo` to `skip-php.*`.  Fixed by commit b492e8f0e77c7acceb7ca21d226bf718d45761df.
  - python/python3alt: "`PHP Parse error:  syntax error, unexpected identifier "ALREADY_THROWN_TOKEN_TYPE", expecting variable in /home/runner/work/grammars-v4/grammars-v4/python/python3alt/Generated/AltPython3Parser.php on line 727`". 
 [Existing error](https://github.com/antlr/grammars-v4/actions/runs/3171329768/jobs/5164663975#step:8:6086), now causing test case failure because it doesn't match expected errors.  I updated issue #2858 and added `python/python3alt` to `_scripts/skip-php.txt` and `_scripts/skip-php.why` (by commit e9ed25fc737fafecfd6f822e212bbc2349bc02de).

**Review by kaby76 — APPROVED** [review]
Looks good. Thanks for working on this.

**Comment by RossPatterson** [comment]
At this point, I believe this work is complete and ready to merge.  See issue #2838 for summary.

**Comment by teverett** [comment]
@RossPatterson thanks!

**Pull request merged**
