### PR TITLE
PostgreSQL - Making grammar language-agnostic + c#/java support, standard tests

### PR DESCRIPTION
**Pull request by OleksiiKovalov**
**What does this PR do?**
Introduces language-agnostic grammar with Java and c# supplementary classes

**Why?**
Now grammar can be used not only with c# but with Java too
Also - standard build/test processes (mvn test/trgen) are now supported and can be used to test grammar

**How is it checked?**
Using both standard test/build process and custom unit tests.

### CODE REVIEW

**Comment by OleksiiKovalov** [comment]
hi @KvanTTT , please take a look

**Comment by OleksiiKovalov** [comment]
Hi @KvanTTT, 
any news?

**Comment by KvanTTT** [comment]
Hi @OleksiiKovalov, sorry for the delay. I'm too busy at the latest time and I'm in the flow of other tasks. I hope I'll have time this weekend.

**Comment by kaby76** [comment]
@KvanTTT  This grammar is mistagged. It should be tagged PostgreSQL not plsql.

**Comment by OleksiiKovalov** [comment]
hi @KvanTTT , any update?

**Comment by KvanTTT** [comment]
Hi. Ok, let's merge it now and fix possible issues later.

**Pull request merged**
