### PR TITLE
Adding ruleworks grammar.

### PR DESCRIPTION
**Pull request by whcox603**

### CODE REVIEW

**Comment by whcox603** [comment]
Any idea what this failure is about?

Test.ts:199:25 - error TS1003: Identifier expected.

199     const tree = parser.();
     
I am slowly getting a build/test environment setup on my system and I get the same result. I don't see anything that tells what/where the problem is located.

bill

**Comment by teverett** [comment]
@whcox603  i had this exact issue last week.  It needs an EOF.  

Try changing this
`
program
    : TOK_LPAREN program_line* TOK_RPAREN
    ;
`

to 

`
program
    : TOK_LPAREN program_line* TOK_RPAREN EOF
    ;
`

**Comment by kaby76** [comment]
I'll fix the tester to give a betyer warning.

**Comment by whcox603** [comment]
Much better. I updated ruleworks.g4

**Comment by whcox603** [comment]
It looks like the 3 failures are with the Go target, but not much to go on (pun unintended.)

On my system the Go test succeeded. I fixed the conflict with action (renamed to action_).

**Comment by kaby76** [comment]
Dependabot updated the go.mod file to remove the reference to Antlr. So, the code that was there to yank out the version doesn't find one. (The code should have checked for a missing reference so it doesn't try to then do a bogus "go get".)

I updated the Go templates to put the version directly in the build.* scripts. Please sync your PR with master.

**Comment by whcox603** [comment]
Much better. Thanks to you both (@teverett @kaby76) for the assistance.

The coverage is not that great (around 50%), but there were only 3 sample programs provided. I have built the compiler and I will use that to test out some more sample programs. One problem is that the SQL calls only work with VAX rdb, which I don't have access to.

**Comment by teverett** [comment]
What a great contribution.  Thanks @whcox603 .

**Pull request merged**
