### PR TITLE
py changes

### PR DESCRIPTION
**Pull request by teverett**
changes to EOL

@KvanTTT  please review and merge?

### CODE REVIEW

**Comment by teverett** [comment]
@KvanTTT  we're on the same page.  I've had trouble doing that previously on my OS X machine and was going to ask you if you were maybe on Windows and could do it?

**Comment by KvanTTT** [comment]
Have you tried to apply these commands? https://stackoverflow.com/a/11183844/1046374

**Comment by teverett** [comment]
@KvanTTT done

**Comment by KvanTTT** [comment]
Thanks)

**Pull request merged**
