### PR TITLE
[thrift] support thrift namespace annotations

### PR DESCRIPTION
**Pull request by alingse**
the file was from https://github.com/apache/thrift/blob/master/test/ThriftTest.thrift

### CODE REVIEW

**Comment by alingse** [comment]
cc @kaby76

**Review by kaby76 — COMMENTED** [review]
Looks good.

The Thrift Doc [here](https://thrift.apache.org/docs/idl) is not up to date, and is out of sync with the actual Bison grammar [here](https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/thrifty.yy). Please add to the readme.md or Thrift.g4 the link to the Bison grammar so folks can see what else in the .g4 should be updated as the source changes. Thanks.

**Comment by alingse** [comment]
> Looks good.
> 
> The Thrift Doc [here](https://thrift.apache.org/docs/idl) is not up to date, and is out of sync with the actual Bison grammar [here](https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/thrifty.yy). Please add to the readme.md or Thrift.g4 the link to the Bison grammar so folks can see what else in the .g4 should be updated as the source changes. Thanks.

done

**Comment by teverett** [comment]
@alingse  thanks!

**Pull request merged**
