### PR TITLE
WIP: C++ Expression and Template Rework, CQL small fix

### LINKED ISSUE #1753: RightShift lexer rule eclipsing double template end character '>'
I think lexer rule `RightShift : '>>'` unables matching rule `simpletemplateid` in the case where there are more than two levels of imbrication of `simpletemplateid` rule.

For instance, the explicit template instanciation `template class MyTemplate1<MyTemplate2<MyClass>>;` will not be recognized because symbol `>>` is matched with lexeme `RightShift`.

To correct it, I propose to change lexer rule `RightShift : >>` into parser rule `rightshift : '>' '>'` and change every reference to rule `RightShift` into a reference to rule `rightshift`.

Note: This problem might also happen with lexemes `RightShiftAssign`, `LeftShift`, and `LeftShiftAssign` but I think in practice it is impossible.

### PR DESCRIPTION
**Pull request by Marti2203**
Issues related to this : #1793 #1753, #1702 #1754 #1869 
Current state: Not done with Templates

### CODE REVIEW

**Comment by teverett** [comment]
The PR notes that it is not done.  Do you prefer to pull this on to MASTER now or wait?

**Comment by Marti2203** [comment]
I thought it was done, but then I found out that it does not catch #1793

**Comment by Marti2203** [comment]
I would prefer I fix that also and then give a light to pull

**Comment by teverett** [comment]
All good.  Just drop a note here when you're ready.

**Comment by Marti2203** [comment]
Fixing #1724

**Comment by teverett** [comment]
@Marti2203 good to pull this?

**Comment by Marti2203** [comment]
I thought I had fixed the templates issue (A<B<C>> not parser correctly) , but I have. I have fixed the code to use Antlr's left recursion....

**Comment by teverett** [comment]
@Marti2203  @KvanTTT  is this ready to pull?

**Comment by KvanTTT** [comment]
Please remove `WIP` prefix at first.

**Comment by Marti2203** [comment]
@teverett it is not ready, I currently only the templates are left and I am not seeing any proggress with them.

**Pull request closed without merging**
