### PR TITLE
New grammar Sybase Powerbuilder Datawindow

### PR DESCRIPTION
**Pull request by wegoodwin**
Updated the SQLite grammar.  changed error to error_, because golang error is a reserved word.

### CODE REVIEW

**Comment by KvanTTT** [comment]
Please resolve conflicts in request and split sql changes from powerbuilder ones.

**Comment by wegoodwin** [comment]
Hi @KvanTTT,

I am new to git hub and I do not know how to do what you are asking.  Is this something you can help me with?

**Comment by KvanTTT** [comment]
I fixed the title of PR by myself. Thanks!

**Comment by wegoodwin** [comment]
Hi @KvanTTT ,

I appreciate your help.

**Pull request merged**
