### PR TITLE
Fixed algol60 grammar and reworked Arithmetic grammar.

### PR DESCRIPTION
**Pull request by Marti2203**

### CODE REVIEW

**Comment by Marti2203** [comment]
This PR is a fix of the algol60 grammar as it had some issues (#1417 and #1419)

**Comment by Marti2203** [comment]
Reworked Arithmetic grammar so it will use the full power of left recursion.

**Comment by Marti2203** [comment]
I cannot understand this error. The difference is a paragraph?

**Comment by teverett** [comment]
The error:

<pre>
Parsing :/home/travis/build/antlr/grammars-v4/arithmetic/examples/precedence3.txt
java.lang.Exception: Parse tree does not match 'precedence3.txt.tree'. Differences: Diff(EQUAL,"(equation (expression (atom (variable a))) (relop =) (expression (expression (atom (scientific 234))) ^ (expression ( (expression (expression (atom (scientific 4.23))) / (expression (atom (scientific 345)))) ))))"), Diff(DELETE,"¶"), 

</pre>

Is from the test framework, not from Antlr.   There is a file on the source tree here:

https://github.com/antlr/grammars-v4/blob/master/arithmetic/examples/precedence3.txt.tree

That is the "correct" output from parsing precedence3.txt.  You've changed the grammar and the results of parsing precedence3.txt.tree are now different.  Just paste the right results in precedence3.txt.tree and you're good to go.

**Comment by Marti2203** [comment]
I have done that. That is why the first two tests work.

**Comment by KvanTTT** [comment]
> The grammar is reworked a lot to be a proper Antlr grammar without any syntactic sugar (custom actions/ labels/ identifiers).

What's wrong with labels and identifiers? They are natural to Antlr as well as other syntactic constructions. Customs actions are a bit awkward because they are not universal.

**Comment by Marti2203** [comment]
I have no issues, I like them(labels and identifiers) and use them in my grammars, but I try to make the code in these grammars without them.

**Comment by Marti2203** [comment]
In the commit, I have changed the trees which are used for the tests. I understand that the error is from the test framework, but I do not understand what I should remove to have no differences.

**Comment by Marti2203** [comment]
Found the issue. A phantom new line was the issue. Now I am reworking the other trees and I think that everything is okay. Sorry if I am spamming you.

**Comment by teverett** [comment]
@Marti2203  thanks

**Pull request merged**
