### PR TITLE
Python grammars

### PR DESCRIPTION
**Pull request by RobEin**
added Python 2.7.18 parser
added Python 3.11.5 parser
removed tiny-python parser

Thanks,
Robert

### CODE REVIEW

**Review by kaby76 — COMMENTED** [review]
Let's fix some of the problems here with testing.

* This repo uses a coding standard for the grammars, target-specific files, and tests. It cannot find the target-specific code. Please rename all target-specific code directories in the name of the target, not "target_foobar". The test program does not search the directories for target specific code, it has to be told where it is. For example, we could have a CSharp grammar that has examples of .cs files. If it goes looking for that, it will find the test inputs, but also target-specific support files.
    * "target_Java/"=> "Java/"
    * "target_CSharp/" => "CSharp/"
    * "target_Python3/" => "Python3/"
* Change python/python3/desc.xml so that the test files actually points to the directory, i.e., "example" != "example*s*".
```
iff --git a/python/python3_11_5/desc.xml b/python/python3_11_5/desc.xml
index bb9abce5..2b0fd832 100644
--- a/python/python3_11_5/desc.xml
+++ b/python/python3_11_5/desc.xml
@@ -5,6 +5,6 @@
    <test>
       <targets>CSharp;Java;Python3</targets>
       <entry-point>file_input</entry-point>
-      <inputs>example</inputs>
+      <inputs>examples/</inputs>
    </test>
 </desc>
```
This will get things started.

**Comment by RobEin** [comment]
I fixed the directory names.
Thanks,
Robert

**Comment by RobEin** [comment]
I fixed the directory names.
Thanks,
Robert

**Comment by kaby76** [comment]
The python2_7_18 grammar is failing to parse base64.py (https://github.com/antlr/grammars-v4/actions/runs/6369601825/job/17289986916#step:21:105)

**Comment by RobEin** [comment]
Thanks for the feedback.
I fixed the errors.

**Comment by RobEin** [comment]
I am closing this PR and starting a new one.

**Comment by RobEin** [comment]
Sorry, I don't know whether I should close this PR or someone else will.

**Comment by RobEin** [comment]
Yes, it is ready to merge.

**Pull request closed without merging**
