### PR TITLE
OBJ grammar to pass all the documented examples

### PR DESCRIPTION
**Pull request by hakanai**
The grammar for OBJ files didn't really pass any of the real examples, so I have copied a bunch of the real examples from the documentation and rewritten the grammar to cope with all those examples.

### CODE REVIEW

**Comment by hakanai** [comment]
My own experience after using a compiled version for a bit says, did I name all the parser rules badly? I ended up with awkward Java classnames.

**Comment by teverett** [comment]
"error(134): parser/WavefrontOBJ.g4:80:7: symbol type conflicts with generated code in target language or runtime"

please change "type" to "type_"

**Comment by hakanai** [comment]
> "error(134): parser/WavefrontOBJ.g4:80:7: symbol type conflicts with generated code in target language or runtime"
> 
> please change "type" to "type_"

Oof. I wish the compiler for whatever target language that is would deal with that sort of thing.

**Comment by hakanai** [comment]
I tried renaming `type` to `cstype` instead as it was less cringeworthy than `type_`, let's see if it's allowed though.

**Comment by teverett** [comment]
@hakanai  could you please re-submit this PR?  I'm not sure how to restart the checks and am wondering if you could restart the checks by submitting the PR, if they may pass

**Comment by hakanai** [comment]
Resubmitted as #2393.

**Pull request closed without merging**
