### PR TITLE
JavaScript port for PHP grammar

### PR DESCRIPTION
**Pull request by cetfor**
This commit adds JavaScript version of the PhpLexer.g4 so this parser can be used in Node.js.

I'm generating this with `antlr4 -Dlanguage=JavaScript -visitor PhpLexer.g4`. 

Here's my test stub for your reference:

```javascript
console.log(`Analyzing script '${s}'`);
const script = readFile(s);  // this just reads a file from disk, nothing fancy
if (script) {
  const inputStream = new antlr4.InputStream(script);
  const lexer = new PhpLexer(inputStream);
  lexer.strictMode = false;
  const tokens = new antlr4.CommonTokenStream(lexer);
  const parser = new PhpParser(tokens);
  parser.buildParseTrees = true;
  const tree = parser.htmlDocument();

  // Print the LISP-formatted tree
  console.log();
  console.log(tree.toStringTree(parser.ruleNames));

  // Walk the Parse Tree with the Listeners enabled
  const listeners = new FSListener();
  antlr4.tree.ParseTreeWalker.DEFAULT.walk(listeners, tree);
}
```

I am currently getting some exceptions on a few of the `example` PHP files. I've been trying to track these down but I'm hoping to get some help.  If I resolve these I'll update the PR.

File: `strings.php` (addressed in commit a098442)
Throws a `ReferenceError: SkipChannel is not defined`.  

File: `php-js-php.php`
Throws a `TypeError: Cannot read property 's0' of undefined`. 

File: `if.php`
I get interesting issues like `line 3:27 mismatched input ';' expecting ';'`.

I'm by no means an ANTLR expert but I'm having a blast working with it.  I would greatly appreciate any help. Thanks!

### CODE REVIEW

**Comment by KvanTTT** [comment]
Thank you! Could you also apply the modification to lexer from my latest pull request? https://github.com/antlr/grammars-v4/pull/1218

**Comment by cetfor** [comment]
Please see commit a098442 "Addressing SkipChannel issue" and let me know if that sounds reasonable as a means of addressing the `ReferenceError: SkipChannel is not defined`.

I'm still trying to track down the `TypeError: Cannot read property 's0' of undefined` exception while parsing `php-js-php.php`.

**Comment by KvanTTT** [comment]
I'm going to take a look at the issue with `SkipChannel`.

**Comment by KvanTTT** [comment]
Not ready, but let's merge it. I hope, we'll fix it later.

**Pull request merged**
