### PR TITLE
Add Dart2LexerBase.dart for the `dart2` grammar

### PR DESCRIPTION
**Pull request by grosscope**

### CODE REVIEW

**Comment by kaby76** [comment]
Please change the following:

* Rename the directory "dart2/dart/" to "dart2/Dart/". The Dart code really has to be in the name of a directory identical to the name of the target used in the "-Dlanguage=Dart" command. I'll make a change to the build scripts at some point to loosen the case-sensitive requirement.
* Remove the line "dart2" from the [dart-skip.txt file](https://github.com/grosscope/grammars-v4/blob/86ee1885e27c7bc22ffb7b8180c36d050f494269/_scripts/skip-dart.txt#L10) so that the grammar can be tested for Dart. Otherwise, it is "skipped".

Thanks. --kaby76

**Comment by kaby76** [comment]
@teverett This looks good.

**Comment by grosscope** [comment]
Thanks @kaby76, well.. I didn't do that much of testing, but let's hope it will work :smiley:

**Comment by kaby76** [comment]
I just did a test--it works great, 100%! --Ken

**Comment by teverett** [comment]
@grosscope thanks!

**Pull request merged**
