### PR TITLE
Allow "yes" keyword to be used as an identifier

### PR DESCRIPTION
**Pull request by ramanenka**
MySQL permits `yes` keyword to be used as an identifier.

### CODE REVIEW

**Comment by kaby76** [comment]
Please add a test for the change to the [examples/ directory](https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies/examples). Thanks.

**Comment by ramanenka** [comment]
@kaby76 Added an `alter table`  statement to the examples directory. Also duplicated the patch for MariaDB grammar.

**Comment by kaby76** [comment]
The build "aborted" due to a network time-out. The PR looks ok.

**Comment by teverett** [comment]
@ramanenka thanks!

**Pull request merged**
