### PR TITLE
fortran77: continue should only allow single label

### PR DESCRIPTION
**Pull request by BBreiden**

### CODE REVIEW

**Comment by BBreiden** [comment]
I have added an example. Hope this is ok!

**Comment by KvanTTT** [comment]
Unfortunately, there are errors on CI: https://github.com/antlr/grammars-v4/actions/runs/3891113700/jobs/6644828450#step:17:44

**Comment by BBreiden** [comment]
I will try to reproduce this error and try to fix it.

**Comment by BBreiden** [comment]
I was able to reproduce the problem locally and updated the example. Can you pls rerun CI?

**Comment by KvanTTT** [comment]
Thanks for the contribution and welcome to the ANTLR grammars repository!

**Pull request merged**
