### PR TITLE
Don't use java.util.Stack (fixes #3507).

### LINKED ISSUE #3507: [javascript] Don't use `java.util.Stack`
From [official Java docs](https://docs.oracle.com/javase/8/docs/api/java/util/Stack.html):
> A more complete and consistent set of LIFO stack operations is provided by the [Deque](https://docs.oracle.com/javase/8/docs/api/java/util/Deque.html) interface and its implementations, which should be used in preference to this class.

Also methods in `java.util.Stack` are synchronized which leads to a performance penalty in a non-concurrent environment.

### PR DESCRIPTION
**Pull request by ris58h**

### CODE REVIEW

**Comment by kaby76** [comment]
There are other locations where `Stack` is used.
```
06/05-07:39:00 ~/test/grammars-v4
$ grep . -R -e 'Stack[<]' --include='*.java'
./cobol85/java/sub/document/impl/CobolDocumentParserListenerImpl.java:  private final Stack<CobolDocumentContext> contexts = new Stack<CobolDocumentContext>();
./csharp/Java/CSharpLexerBase.java:    protected Stack<Boolean> interpolatedVerbatiums = new Stack<Boolean>();
./csharp/Java/CSharpLexerBase.java:    protected Stack<Integer> curlyLevels = new Stack<Integer>();
./csharp/Java/CSharpPreprocessorParserBase.java:    Stack<Boolean> conditions = new Stack<Boolean>();
./gdscript/Java/GDScriptLexerBase.java:    private java.util.Stack<Integer> indents = new java.util.Stack<>();
./haskell/Java/HaskellBaseLexer.java:    private Stack<Pair<String, Integer>> indentStack = new Stack<>();
./javascript/javascript/Java/JavaScriptLexerBase.java:    private Stack<Boolean> scopeStrictModes = new Stack<Boolean>();
./javascript/jsx/Java/JavaScriptLexerBase.java:    private Stack<Boolean> scopeStrictModes = new Stack<Boolean>();
./javascript/jsx/Java/JavaScriptParserBase.java:        private Stack<String> _tagNames = new Stack<String>();
./javascript/typescript/Java/TypeScriptLexerBase.java:    private Stack<Boolean> scopeStrictModes = new Stack<Boolean>();
./objc/two-step-processing/ObjectiveCPreprocessor.java:    private Stack<Boolean> _conditions = new Stack<Boolean>();
./python/python/Java/PythonLexerBase.java:    private Stack<Integer> _indents = new Stack<>();
./python/python3/Java/Python3LexerBase.java:    private java.util.Stack<Integer> indents = new java.util.Stack<>();
./python/python3/Java/Python3LexerBase.java:        indents = new java.util.Stack<>();
./python/python3-without-actions/src/LexerWithIndentDedentInjector.java:    private Stack<Integer> indentLengths = new Stack<>();
./python/tiny-python/tiny-grammar-without-actions/LexerWithIndentDedentInjector.java:    private Stack<Integer> indentLengths = new Stack<>();
06/05-07:40:21 ~/test/grammars-v4
```
These should be addressed too. What do you think? An Issue should be created.

**Comment by ris58h** [comment]
@kaby76 good point! I'll update the issue and PR.

**Comment by teverett** [comment]
@kaby76  good to merge?

**Comment by kaby76** [comment]
> @kaby76 good to merge?

@teverett This looks fine. Good to go. Thanks.

**Comment by teverett** [comment]
@ris58h  thanks!

**Pull request merged**
